=== bengtmartensson/oldharctoolbox/harctoolbox/tags/milestone-1/dtds/commandnames.dtd
<!ELEMENT commandnames (group+) >

<!ELEMENT group ((group|command|commandref)+) >
<!ATTLIST group
        id ID #REQUIRED
        description CDATA #IMPLIED >

<!ELEMENT command (synonym*,parameter*,comment?) >
<!ATTLIST command
        id ID #REQUIRED
        name CDATA #IMPLIED
        displayname CDATA #IMPLIED
        zone (1|2|3) #IMPLIED
        remark CDATA #IMPLIED
	type (discrete|toggle|cyclic) "discrete"
        description CDATA #IMPLIED >

<!ELEMENT comment (#PCDATA) >

<!ELEMENT synonym (#PCDATA) >
<!ATTLIST synonym
        name CDATA #REQUIRED >

<!ELEMENT parameter EMPTY >
<!ATTLIST parameter
        name    CDATA   #REQUIRED >

<!ELEMENT commandref EMPTY >
<!ATTLIST commandref
	cmd	IDREF	#REQUIRED >

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/src/harc/commandnames.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE commandnames PUBLIC "-//bengt-martensson.de//commandnames//en"
 "../../dtds/commandnames.dtd">
<commandnames>
  <group id="get_commands" description="Command for getting some information by bidirectional communication">
    <command id="get_recordsrc"/>
    <command id="get_channellist"/>
    <command id="get_programs_channel"/>
    <command id="get_programs_event"/>
    <command id="get_programs_eventid"/>
    <command id="get_current_programs"/>
    <command id="get_standby"/>
    <command id="get_power"/>
    <command id="get_volume"/>
    <command id="get_mute"/>
    <command id="get_program"/>
    <command id="get_program_pids"/>
    <command id="get_program_allpids"/>
    <command id="get_subchannels"/>
    <command id="get_playback"/>
    <command id="get_sectionsd"/>
    <command id="get_recordmode"/>
    <command id="get_mode"/>
    <command id="get_date"/>
    <command id="get_time"/>
    <command id="get_rawtime"/>
    <command id="get_info"/>
    <command id="get_version"/>
    <command id="get_settings"/>
    <command id="get_bouquets"/>
    <command id="get_bouquetsender"/>
    <command id="get_bouquetsender_radio"/>
    <command id="get_videoformat"/>
    <command id="get_videooutput"/>
    <command id="get_vcroutput"/>
    <command id="get_scartmode"/>
    <command id="get_status"/>
    <command id="get_zone2_status"/>
    <command id="get_zone3_status"/>
    <command id="get_input"/>
    <command id="get_lamp_hours"/>
    <command id="get_temperatures"/>
    <command id="get_soundfield"/>
    <command id="get_equalizing"/>
    <command id="get_resolution"/>
    <command id="get_title"/>
    <command id="get_artist"/>
    <command id="get_album"/>
    <command id="get_chapter"/>
    <command id="get_elapsed_time"/>
    <command id="get_remaining_time"/>
    <command id="get_chapter_elapsed_time"/>
    <command id="get_chapter_remaining_time"/>
    <command id="get_total_elapsed_time"/>
    <command id="get_total_remaining_time"/>
    <command id="get_disc_type"/>
    <command id="get_audio_type"/>
    <command id="get_subtitle_type"/>
    <command id="get_contents_data1"/>
    <command id="get_contents_data2"/>
    <command id="get_contents_data3"/>
    <command id="get_contents_data4"/>
    <command id="get_contents_data_all"/>
    <command id="get_devices"/>
    <command id="get_net"/>
    <command id="get_ir"/>
    <command id="get_serial"/>
    <command id="get_state"/>
    <command id="get_timers"/>
    <command id="get_configuration"/>
  </group>

  <group id="netcat_commands">
    <command id="talk">
      <parameter name="transmit"/>
    </command>
    <command id="talk_listen"/>
    <command id="talk_listen1"/>
    <command id="talk_listen2"/>
    <command id="talk_listen3"/>
    <command id="listen"/>
    <command id="listen1"/>
    <command id="listen2"/>
    <command id="listen3"/>
  </group>

  <group id="set_commands" description="Command for setting some stuff requiring a parameter">
    <command id="set_volume">
      <parameter name="volume"/>
    </command>
    <command id="set_zone2_volume">
      <parameter name="volume"/>
    </command>
    <command id="set_zone3_volume">
      <parameter name="volume"/>
    </command>
    <command id="set_program_by_id">
      <parameter name="program_id"/>
    </command>
    <command id="set_program_by_name">
      <parameter name="programname"/>
    </command>
    <command id="set_popup_window">
      <parameter name="text"/>
    </command>
    <command id="set_message_window">
      <parameter name="text"/>
    </command>
    <command id="set_resolution">
      <parameter name="resolution"/>
    </command>
    <command id="set_forward_speed">
      <parameter name="speed"/>
    </command>
    <command id="set_reverse_speed">
      <parameter name="speed"/>
    </command>
    <command id="set_repeatmode">
      <parameter name="mode"/>
    </command>
    <command id="set_position">
      <parameter name="position"/>
    </command>
    <command id="set_net">
      <parameter name="configlock"/>
      <parameter name="ip_settings"/>
    </command>
    <command id="set_ir">
      <parameter name="module"/>
      <parameter name="connector"/>
      <parameter name="mode"/>
    </command>
    <command id="set_serial">
      <parameter name="module"/>
      <parameter name="baudrate"/>
      <parameter name="flowcontrol"/>
      <parameter name="parity"/>
    </command>
    <command id="set_state">
      <parameter name="module"/>
      <parameter name="connector"/>
      <parameter name="mode"/>
    </command>
    <command id="send_ir">
      <parameter name="module"/>
      <parameter name="connector"/>
      <parameter name="id"/>
      <parameter name="frequency"/>
      <parameter name="count"/>
      <parameter name="offset"/>
      <parameter name="timings"/>
    </command>
    <command id="stop_ir">
      <parameter name="module"/>
      <parameter name="connector"/>
    </command>
  </group>

  <group id="special" description="some special stuff">
    <command id="execute_script">
      <parameter name="script_name"/>
    </command>
    <command id="execute_plugin">
      <parameter name="plugin_name"/>
    </command>
    <command id="send_key">
      <parameter name="key_name"/>
    </command>
  </group>

  <group id="numerical" description="Numerical keys">
    <command id="cmd_0" name="0"/>
    <command id="cmd_1" name="1"/>
    <command id="cmd_2" name="2"/>
    <command id="cmd_3" name="3"/>
    <command id="cmd_4" name="4"/>
    <command id="cmd_5" name="5"/>
    <command id="cmd_6" name="6"/>
    <command id="cmd_7" name="7"/>
    <command id="cmd_8" name="8"/>
    <command id="cmd_9" name="9"/>
    <command id="cmd_two_digit" displayname="./.."/>
    <command id="cmd_plus10" displayname="+10"/>
  </group>

  <group id="power">
    <!-- Note: there is no, and should be no "power" -->
    <command id="cmd_power_on" displayname="Power on"/>
    <command id="cmd_power_off" displayname="Power off"/>
    <command id="cmd_power_reverse_on" displayname="Power reverse on" remark="For something moving in the 'other' direction, like a blind."/>
    <command id="cmd_power_reverse_off" displayname="Power reverse off"/>
    <command id="cmd_power_off_confirm" displayname="Power off"/>
    <command id="cmd_power_toggle" displayname="Power"/>
    <command id="cmd_power_pulse" displayname="Power pulse"/>
    <command id="cmd_power_dim" displayname="Power dim"/><!-- dumb dimmer -->
    <command id="cmd_dimmer"/><!-- generic -->
    <command id="cmd_standby"/>
    <command id="cmd_standby_on"/>
    <command id="cmd_standby_off"/>
    <command id="cmd_blink_on"/>
    <command id="cmd_blink_off"/>
    <command id="cmd_reboot"/>

    <command id="cmd_zone1_on" zone="1">
      <synonym name="cmd_zone1_power_on"/>
    </command>
    <command id="cmd_zone1_off" zone="1"/>
    <command id="cmd_zone1_toggle" zone="1"/>
    <command id="get_zone1" zone="1"/>
    <command id="cmd_zone2_on" zone="2"/>
    <command id="cmd_zone2_off" zone="2"/>
    <command id="cmd_zone2_toggle" zone="2"/>
    <command id="get_zone2" zone="2"/>
    <command id="cmd_zone3_on" zone="3"/>
    <command id="cmd_zone3_off" zone="3"/>
    <command id="cmd_zone3_toggle" zone="2"/>
    <command id="get_zone3" zone="3"/>
  </group>

  <group id="mode_selection">
    <command id="cmd_vcr_tv" type="toggle"/>
    <command id="cmd_disc_tv" type="toggle"/>
    <command id="cmd_scartmode_on"/>
    <command id="cmd_scartmode_off"/>
    <command id="cmd_tv_mode"/>
    <command id="cmd_radio_mode"/>
    <command id="cmd_ipod_mode"/>
  </group>

  <group id="input_commands">
    <command id="cmd_input_select" type="cyclic">
      <synonym name="input"/>
    </command>
    <command id="cmd_in_tv"/>
    <command id="cmd_in_dtv"/>
    <command id="cmd_in_vcr"/>
    <command id="cmd_in_vcr1"/>
    <command id="cmd_in_vcr2"/>
    <command id="cmd_in_dvd"/>
    <command id="cmd_in_sat"/>
    <command id="cmd_in_dvb_t"/>
    <command id="cmd_in_tv_cbl"/>
    <command id="cmd_in_aux"/>
    <command id="cmd_in_ext1"/>
    <command id="cmd_in_ext2"/>
    <command id="cmd_in_ext3"/>
    <command id="cmd_in_hdp"/>
    <command id="cmd_in_tape"/><!-- Discrete, do not confuse with following -->
    <command id="cmd_in_tape_mon" type="toggle"/>
    <command id="cmd_in_tape1"/>
    <command id="cmd_in_tape2"/>
    <command id="cmd_in_cd"/>
    <command id="cmd_in_cd_r"/>
    <command id="cmd_in_video1"/>
    <command id="cmd_in_video2"/>
    <command id="cmd_in_video3"/>
    <command id="cmd_in_video_aux"/>
    <command id="cmd_in_phono"/>
    <command id="cmd_in_xm"/><!-- North America -->
    <command id="cmd_in_tuner">
      <synonym name="cmd_in_radio"/>
    </command>
    <command id="cmd_in_cable"/>
    <command id="cmd_in_dvr"/>
    <command id="cmd_in_ipod"/>
    <command id="cmd_in_usb"/>
    <command id="cmd_in_net_usb"/>
    <command id="cmd_in_dvd_hdp"/>
    <command id="cmd_in_vcr_dvr"/>
    <command id="cmd_in_net"/>
    <command id="cmd_in_av" remark="typically a SCART input on a TV"/>
    <command id="cmd_in_av1" remark="typically a SCART input on a TV"/>
    <command id="cmd_in_av2" remark="typically a SCART input on a TV"/>
    <command id="cmd_lock_input"/>

    <command id="cmd_video_select"/>

    <command id="cmd_in_video" remark="cvbs"/>
    <command id="cmd_in_component1">
      <synonym name="cmd_in_yuv"/>
    </command>
    <command id="cmd_in_component2"/>
    <command id="cmd_in_hdmi"/>
    <command id="cmd_in_hdmi1"/>
    <command id="cmd_in_hdmi2"/>
    <command id="cmd_in_hdmi3"/>
    <command id="cmd_in_hdmi4"/>
    <command id="cmd_in_vga">
      <synonym name="cmd_in_pc"/>
      <synonym name="cmd_in_computer"/>
    </command>
    <command id="cmd_in_s_video"/>
    <command id="cmd_in_scart"/>
    <command id="cmd_in_front"/>
    <command id="cmd_in_side"/>
    <command id="cmd_input" type="cyclic"/>
