=== bengtmartensson/oldharctoolbox/harctoolbox/tags/milestone-1/dtds/event-action-map.dtd
<!ELEMENT event-action-map (event+) >

<!ELEMENT event (ir-command, action+) >

<!ELEMENT ir-command EMPTY >
<!ATTLIST ir-command
        remote NMTOKEN #REQUIRED
        command NMTOKEN #REQUIRED >

<!ELEMENT action (quit|log-string|exec) >

<!ELEMENT quit EMPTY >

<!ELEMENT log-string (#PCDATA) >

<!ELEMENT exec ( progname, argument*) >
<!ATTLIST exec
        wait (true|false) "true">

<!ELEMENT argument (#PCDATA) >

<!ELEMENT progname EMPTY >
<!ATTLIST progname
        filename CDATA #REQUIRED >

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/release-0.5.0/config/listen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE event-action-map SYSTEM "../dtds/event-action-map.dtd">

<event-action-map>
  <event>
    <ir-command remote="analog_8ch_switch" command="all_off"/>
    <action>
      <quit/>
    </action>
  </event>

  <event>
    <ir-command remote="analog_8ch_switch" command="cmd_4toggle"/>
    <action>
      <log-string>Hello world</log-string>
    </action>
  </event>

  <event>
    <ir-command remote="analog_8ch_switch" command="cmd_5toggle"/>
    <action>
      <exec wait="true">
        <progname filename="xset"/>
        <argument>dpms</argument>
        <argument>force</argument>
        <argument>standby</argument>
      </exec>
    </action>
  </event>

  <event>
    <ir-command remote="analog_8ch_switch" command="cmd_6toggle"/>
    <action>
      <exec wait="true">
        <progname filename="xset"/>
        <argument>dpms</argument>
        <argument>force</argument>
        <argument>on</argument>
      </exec>
    </action>
  </event>
</event-action-map>
