=== bengtmartensson/oldharctoolbox/harctoolbox/tags/release-0.7.0/dtds/irprotocols.dtd
<!-- Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  This file is offered as-is,
     without any warranty.
-->

<!ELEMENT irprotocols (irprotocol)+ >

<!ELEMENT irprotocol (jp1data?,cooked-ccf-string?,parameters?,frequency?,irpnotation-old?,irpnotation-new?,body?) >
<!ATTLIST irprotocol
        id ID #REQUIRED
        name CDATA #REQUIRED >

<!ELEMENT jp1data (protocol,tohex,urc-code*) >

<!ELEMENT protocol EMPTY >
<!ATTLIST protocol
	number CDATA #REQUIRED
	name CDATA #IMPLIED >

<!ELEMENT urc-code (#PCDATA) >
<!ATTLIST urc-code
	cpu CDATA #REQUIRED >

<!ELEMENT cooked-ccf-string (parameterref|complement|plus|minus)+ >
<!ATTLIST cooked-ccf-string
    format CDATA #REQUIRED >

<!ELEMENT tohex EMPTY >
<!ATTLIST tohex
	function NMTOKEN #REQUIRED
	bits NMTOKEN #IMPLIED >

<!ELEMENT frequency EMPTY >
<!ATTLIST frequency
	value NMTOKEN #REQUIRED >

<!ELEMENT body (timings?,pairs?,intro?,repeat?) >

<!ELEMENT timings (timing)+ >

<!ELEMENT timing EMPTY >
<!ATTLIST timing
	id ID #REQUIRED
	cycles CDATA #REQUIRED >

<!ELEMENT pairs (pair)+ >

<!ELEMENT pair ((one, zero)|(zero, one)) >
<!ATTLIST pair
	id ID #REQUIRED >

<!ELEMENT coded_number (xor|mask|minus|plus|complement|parameterref|constant) >
<!ATTLIST coded_number
	direction (msb|lsb) #REQUIRED
	zero  IDREF	#REQUIRED
	one   IDREF	#REQUIRED
	two   IDREF 	#IMPLIED
	three IDREF 	#IMPLIED
	bits  CDATA 	#REQUIRED >

<!ELEMENT xor (mask|minus|plus|complement|parameterref|constant)+ >

<!ELEMENT mask (mask|minus|plus|complement|parameterref|constant) >
<!ATTLIST mask
          mask CDATA #REQUIRED
          shift CDATA "0" >

<!ELEMENT intro ((one|zero|coded_number)+,(zero|zeropadding))? >

<!ELEMENT repeat ((one|zero|coded_number)+,(zero|zeropadding))? >

<!ELEMENT one EMPTY >
<!ATTLIST one
	timing IDREF #REQUIRED >

<!ELEMENT zero EMPTY >
<!ATTLIST zero
	timing IDREF #REQUIRED >

<!ELEMENT zeropadding EMPTY >
<!ATTLIST zeropadding
	timing IDREF #REQUIRED >

<!ELEMENT parameters (parameter)+ >

<!ELEMENT parameter (default?) >
<!ATTLIST parameter
	id ID #REQUIRED
	name NMTOKEN #IMPLIED
	bits NMTOKEN #REQUIRED >

<!ELEMENT default (constant|minus|plus|complement|mask|parmeterref) >

<!ELEMENT complement (minus|plus|parameterref|mask) >
<!ATTLIST complement
    bits NMTOKEN #REQUIRED >

<!ELEMENT minus (constant|parameterref)+ >

<!ELEMENT parameterref EMPTY >
<!ATTLIST parameterref
	parameter IDREF #REQUIRED >

<!ELEMENT constant EMPTY >
<!ATTLIST constant
	value NMTOKEN #REQUIRED >

<!ELEMENT irpnotation-new (#PCDATA) >

<!ELEMENT irpnotation-old (#PCDATA) >

=== bengtmartensson/oldharctoolbox/protocols/rc6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="rc6" id="rc6">
<!--
DecodeIR says:
 RC6 is the name used for the first member of the RC6 family of
  protocols. Technically this is RC6-0-16, but DecodeIr will always display
  that as simply "RC6"
-->
<!--  http://www.sbprojects.com/knowledge/ir/rc6.htm -->
<jp1data>
    <protocol number="00 58" name="RC6"/>
    <tohex function="reverse-invert" bits="8"/>
  </jp1data>
  <cooked-ccf-string format="6000 0073 0000 0002 FIXME %04x %04x">
    <parameterref parameter="deviceno"/>
    <parameterref parameter="subdevice"/>
    <parameterref parameter="cmdno"/>
  </cooked-ccf-string>
  <parameters>
    <parameter id="deviceno" bits="8"/><!-- Philips: system -->
    <parameter id="subdevice" bits="5"/>
    <parameter id="cmdno" bits="8"/>
    <parameter id="toggle" bits="1"/>
  </parameters>
  <frequency value="36000"/>
  <irpnotation-new>
{36k,444,msb}&lt;-1,1|1,-1>(6,-2,1:1,0:3,&lt;-2,2|2,-2>(T:1),D:8,F:8,^107m)+ 
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="16"/>
      <timing id="t2" cycles="32"/>
      <timing id="t6" cycles="96"/>
      <timing id="ttotal" cycles="3852"/>
    </timings>
    <pairs>
      <pair id="p0">
        <zero timing="t1"/>
        <one timing="t1"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
      <pair id="q0">
        <zero timing="t2"/>
        <one timing="t2"/>
      </pair>
      <pair id="q1">
        <one timing="t2"/>
        <zero timing="t2"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <one timing="t6"/>
      <zero timing="t2"/>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="1"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="3">
	<constant value="0"/>
      </coded_number>
      <coded_number direction="msb" zero="q0" one="q1" bits="1">
	<parameterref parameter="toggle"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="8">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="8">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <zeropadding timing="ttotal"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/milestone-1/protocols/f12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<!-- 
Reference: http://www.sbprojects.com/knowledge/ir/nrc17.htm,
 see also http://www.hifi-remote.com/forums/viewtopic.php?t=1044
 -->
<irprotocol name="nrc17" id="nrc17">
  <jp1data>
    <protocol number="00 xx" name="F12"/>
    <tohex function="reverse-invert" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="3"/>
    <parameter id="subdevice" bits="1">
      <default>
	<constant value="1"/>
      </default>
    </parameter>
    <parameter id="cmdno" bits="8"/>
  </parameters>
  <frequency value="38000"/>
  <irpnotation-old>
Device=5.0
Function=0..255
Protocol=F12
Frequency=38000
Time Base=425
Zero=1,-3
One=3,-1
Form=D:3,S:1,F:8,-80,D:3,S:1,F:8,-80
  </irpnotation-old>
  <irpnotation-new>
protocol={38k,410}&lt;1,-3|3,-1>(D:3,C:1,F:8,^129)+
static=c,0
user=d,Device
user=f,Function
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="16"/>
      <timing id="t3" cycles="48"/>
      <timing id="t129" cycles="2064"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t3"/>
      </pair>
      <pair id="p1">
        <one timing="t3"/>
        <zero timing="t1"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <coded_number direction="lsb" zero="p0" one="p1" bits="3">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="1">
	<parameterref parameter="subdevice"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <zeropadding timing="t129"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/protocols/nokia12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="nokia" id="nokia">
  <jp1data>
    <protocol number="00 ed" name="Nokia"/>
    <tohex function="id" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="4"/>
    <parameter id="cmdno" bits="8"/>
  </parameters>
  <frequency value="36000"/>
  <irpnotation-new>
{36k,msb}&lt;164,-276|164,-445|164,-614|164,-783&gt;(412,-276,D:4,F:8,164,-???)+
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t164" cycles="6"/>
      <timing id="t276" cycles="10"/>
      <timing id="t445" cycles="16"/>
      <timing id="t614" cycles="22"/>
      <timing id="t783" cycles="28"/>
      <timing id="t412" cycles="15"/>
      <timing id="t_end" cycles="4050"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t164"/>
        <zero timing="t276"/>
      </pair>
      <pair id="p1">
        <one timing="t164"/>
        <zero timing="t445"/>
      </pair>
      <pair id="p2">
        <one timing="t164"/>
        <zero timing="t614"/>
      </pair>
      <pair id="p3">
        <one timing="t164"/>
        <zero timing="t783"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <one timing="t412"/>
      <zero timing="t276"/>
      <coded_number direction="msb" zero="p0" one="p1" two="p2" three="p3" bits="4">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" two="p2" three="p3" bits="8">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <one timing="t164"/>
      <zero timing="t_end"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/protocols/sony12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="panasonic" id="panasonic">
  <jp1data>
    <protocol number="001F or 00C9 or 00CD" name="panasonic"/>
    <tohex function="reverse-invert" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="5"/>
    <parameter id="cmdno" bits="7"/>
  </parameters>
  <frequency value="40000"/>
  <irpnotation-new>
<![CDATA[
{40k,600}<1,-1|2,-1>(4,-1,F:7,D:5,^45m)+
]]>
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="24"/>
      <timing id="t2" cycles="48"/>
      <timing id="t4" cycles="96"/>
      <timing id="t45m" cycles="1800"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
      <pair id="p1">
        <one timing="t2"/>
        <zero timing="t1"/>
      </pair>
    </pairs>
    <intro>
      <one timing="t4"/>
      <zero timing="t1"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="7">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="5">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <zeropadding timing="t45m"/>
    </intro>
    <repeat/>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/protocols/denon_k.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="denon_k" id="denon_k">
  <jp1data>
    <protocol number="00 xx" name="Denon-K"/>
    <tohex function="reverse_complement" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="4"/>
    <parameter id="subdevice" bits="4"/>
    <parameter id="cmdno" bits="12"/>
  </parameters>
  <frequency value="37000"/>
  <irpnotation-new>
protocol={37k,432}&lt;1,-1|1,-3>(8,-4,84:8,50:8,0:4,D:4,S:4,F:12,((D*16)^S^(F*16)^((F::4)%8)):8,1,-173)+
user=d,Device
user=s,Subdevice
user=f,Function
  </irpnotation-new>
<!--
        super(0x0070, new pulse_pair(0x0010, 0x0010),
                new pulse_pair(0x0010, 0x0030), "");
        repeat_sequence.setleadin(new pulse_pair(0x0080, 0x0040));
        repeat_sequence.setdata(array_lsb(84, 8));
        repeat_sequence.appenddata(array_lsb(50, 8));
        repeat_sequence.appenddata(array_lsb(0, 4));
        repeat_sequence.appenddata(array_lsb(device, 4));
        repeat_sequence.appenddata(array_lsb(subdevice, 4));
        repeat_sequence.appenddata(array_lsb(command, 12));
        //System.err.println(device*16);
        //System.err.println(subdevice + 16*(command%16));
        //System.err.println(command/16);
        // See page 6.
        int chksum = (device * 16) ^ (subdevice + 16 * (command % 16)) ^ (command / 16);

        repeat_sequence.appenddata(array_lsb(chksum, 8));
        repeat_sequence.setleadout(new pulse_pair(0x0010, 0x0acd));
 -->
  <body>
    <timings>
      <timing id="t1" cycles="16"/>
      <timing id="t3" cycles="48"/>
      <timing id="t8" cycles="128"/>
      <timing id="t4" cycles="64"/>
      <timing id="t173" cycles="2768"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t3"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <!-- 8, -->
      <one timing="t8"/>
      <!-- //-4, -->
      <zero timing="t4"/>
      <!-- 84:8, -->
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<constant value="84"/>
      </coded_number>
      <!--50:8, -->
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<constant value="50"/>
      </coded_number>
      <!-- 0:4, -->
      <coded_number direction="lsb" zero="p0" one="p1" bits="4">
	<constant value="0"/>
      </coded_number>
      <!-- D:4, -->
      <coded_number direction="lsb" zero="p0" one="p1" bits="4">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <!-- S:4, -->
      <coded_number direction="lsb" zero="p0" one="p1" bits="4">
	<parameterref parameter="subdevice"/>
      </coded_number>
      <!-- F:12, -->
      <coded_number direction="lsb" zero="p0" one="p1" bits="12">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <!--((D*16)^S^(F*16)^((F::4)%8)):8 -->
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<xor>
	  <!--  (device * 16) -->
	  <mask shift="4">
	    <parameterref parameter="deviceno"/>
	  </mask>
	  <!-- ^ (subdevice -->
	  <parameterref parameter="subdevice"/>
	  <!-- + 16 * (command % 16)) ^ --> 
	  <mask mask="15" shift="4">
	    <parameterref parameter="cmdno"/>
	  </mask>
	  <!-- (command / 16); -->
	  <mask shift="-4">
	    <parameterref parameter="cmdno"/>
	  </mask>
       </xor>
      </coded_number>
      <!-- 1,-->
      <one timing="t1"/>
      <!-- -173 -->
      <zero timing="t173"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/harctoolbox/trunk/protocols/intertechno.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="intertechno" id="intertechno">
<jp1data>
    <protocol number="xx" name=""/>
    <tohex function="reverse_complement" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" name="house" bits="4"/>
    <parameter id="subdevice" name="deviceaddress" bits="4"/>
    <parameter id="cmdno" name="command" bits="1"/>
    <!-- power_on = 0, power_off = 1 -->
  </parameters>
  <frequency value="38000"/>
  <body>
    <timings>
      <timing id="t1" cycles="14"/>
      <timing id="t3" cycles="42"/>
      <timing id="tend" cycles="409"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t3"/>
      </pair>
      <pair id="p1">
        <one timing="t3"/>
        <zero timing="t1"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="0"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<mask mask="1" shift="0">
	  <parameterref parameter="deviceno"/>
	</mask>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="0"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<mask mask="2" shift="-1">
	  <parameterref parameter="deviceno"/>
	</mask>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="0"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<mask mask="4" shift="-2">
	  <parameterref parameter="deviceno"/>
	</mask>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="0"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<mask mask="8" shift="-3">
	  <parameterref parameter="deviceno"/>
	</mask>
      </coded_number>

      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="0"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<mask mask="1" shift="0">
	  <parameterref parameter="subdevice"/>
	</mask>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="0"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<mask mask="2" shift="-1">
	  <parameterref parameter="subdevice"/>
	</mask>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="0"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<mask mask="4" shift="-2">
	  <parameterref parameter="subdevice"/>
	</mask>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="0"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<mask mask="8" shift="-3">
	  <parameterref parameter="subdevice"/>
	</mask>
      </coded_number>

      <coded_number direction="msb" zero="p0" one="p1" bits="7">
	<constant value="10"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <one timing="t1"/>
      <zero timing="tend"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/2012-06-07/protocols/samsung36.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="samsung36" id="samsung36">
  <jp1data>
    <protocol number="01 B5" name="Samsung36"/>
    <tohex function="reverse" bits="8"/>
    <urc-code cpu="HCS08">20 15 22 48 31 8F 45 08 04 00 F9 02 E1 00 F9 00 F9 77 83 08 CE 08 C8 4E 63 64 33 64 B6 62 62 B7 62 AE 04 39 64 39 63 39 62 5B F8 3C A9 6E 11 7D CC FF 7A</urc-code>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="8"/>
    <parameter id="subdevice" bits="8">
      <default>
	<constant value="0"/>
      </default>
    </parameter>
    <parameter id="E" bits="4">
      <default><!-- not implemented -->
	<constant value="1"/>
      </default>
    </parameter>
    <parameter id="cmdno" bits="8"/>
  </parameters>
  <frequency value="38000"/>
  <irpnotation-old>
    // Device=32.0
    // define E=1
    // Function=0..255
    // Frequency=38000
    // One=498,-1498
    // Zero=498,-498
    // Form=;4488,-4492,d:8,s:8,498,-4498,e:4,f:8,-68,~f:8,498,-59154
    // Note: we use function/command with the other bit direction than in .irp.
  </irpnotation-old>
  <body>
    <timings>
      <timing id="t1" cycles="19"/>
      <timing id="t3" cycles="57"/>
      <timing id="tab" cycles="171"/>
      <timing id="taa" cycles="170"/>
      <timing id="t900" cycles="2304"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t3"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <one timing="tab"/>
      <zero timing="taa"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="subdevice"/>
      </coded_number>
      <one timing="t1"/>
      <zero timing="tab"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="4">
	<!--parameterref parameter="E"/-->
        <constant value="7"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="8">
	  <parameterref parameter="cmdno"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="8">
        <complement bits="8">
	  <parameterref parameter="cmdno"/>
        </complement>
      </coded_number>
      <one timing="t1"/>
      <zero timing="t900"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/protocols/rc5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="rc5" id="rc5">
  <jp1data>
    <protocol number="00 E8" name="RC5"/>
    <tohex function="reverse-invert" bits="8"/>
  </jp1data>
  <cooked-ccf-string format="5000 0073 0000 0001 %04x %04x">
    <parameterref parameter="deviceno"/>
    <parameterref parameter="cmdno"/>
  </cooked-ccf-string>
  <parameters>
    <parameter id="deviceno" bits="5"/><!-- Philips: system -->
    <parameter id="cmdno" bits="7"/>
    <parameter id="toggle" bits="1"/>
  </parameters>
  <frequency value="36000"/>
  <irpnotation-new>
protocol={36k,889,msb}&lt;1,-1|-1,1>(1:1,~F:1:6,T:1,D:5,F:6,^128)+
user=d,Device
user=f,Function
user=t,Toggle
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="32"/>
      <timing id="ttotal" cycles="4096"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
      <pair id="p1">
        <zero timing="t1"/>
        <one timing="t1"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="1"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<complement bits="1">
	  <mask mask="64" shift="-6">
	    <parameterref parameter="cmdno"/>
	  </mask>
	</complement>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<parameterref parameter="toggle"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="5">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="6">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <zeropadding timing="ttotal"/>
    </repeat>
  </body>
</irprotocol>
