=== bengtmartensson/oldharctoolbox/harctoolbox/tags/release-0.7.0/dtds/irprotocols.dtd
<!-- Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  This file is offered as-is,
     without any warranty.
-->

<!ELEMENT irprotocols (irprotocol)+ >

<!ELEMENT irprotocol (jp1data?,cooked-ccf-string?,parameters?,frequency?,irpnotation-old?,irpnotation-new?,body?) >
<!ATTLIST irprotocol
        id ID #REQUIRED
        name CDATA #REQUIRED >

<!ELEMENT jp1data (protocol,tohex,urc-code*) >

<!ELEMENT protocol EMPTY >
<!ATTLIST protocol
	number CDATA #REQUIRED
	name CDATA #IMPLIED >

<!ELEMENT urc-code (#PCDATA) >
<!ATTLIST urc-code
	cpu CDATA #REQUIRED >

<!ELEMENT cooked-ccf-string (parameterref|complement|plus|minus)+ >
<!ATTLIST cooked-ccf-string
    format CDATA #REQUIRED >

<!ELEMENT tohex EMPTY >
<!ATTLIST tohex
	function NMTOKEN #REQUIRED
	bits NMTOKEN #IMPLIED >

<!ELEMENT frequency EMPTY >
<!ATTLIST frequency
	value NMTOKEN #REQUIRED >

<!ELEMENT body (timings?,pairs?,intro?,repeat?) >

<!ELEMENT timings (timing)+ >

<!ELEMENT timing EMPTY >
<!ATTLIST timing
	id ID #REQUIRED
	cycles CDATA #REQUIRED >

<!ELEMENT pairs (pair)+ >

<!ELEMENT pair ((one, zero)|(zero, one)) >
<!ATTLIST pair
	id ID #REQUIRED >

<!ELEMENT coded_number (xor|mask|minus|plus|complement|parameterref|constant) >
<!ATTLIST coded_number
	direction (msb|lsb) #REQUIRED
	zero  IDREF	#REQUIRED
	one   IDREF	#REQUIRED
	two   IDREF 	#IMPLIED
	three IDREF 	#IMPLIED
	bits  CDATA 	#REQUIRED >

<!ELEMENT xor (mask|minus|plus|complement|parameterref|constant)+ >

<!ELEMENT mask (mask|minus|plus|complement|parameterref|constant) >
<!ATTLIST mask
          mask CDATA #REQUIRED
          shift CDATA "0" >

<!ELEMENT intro ((one|zero|coded_number)+,(zero|zeropadding))? >

<!ELEMENT repeat ((one|zero|coded_number)+,(zero|zeropadding))? >

<!ELEMENT one EMPTY >
<!ATTLIST one
	timing IDREF #REQUIRED >

<!ELEMENT zero EMPTY >
<!ATTLIST zero
	timing IDREF #REQUIRED >

<!ELEMENT zeropadding EMPTY >
<!ATTLIST zeropadding
	timing IDREF #REQUIRED >

<!ELEMENT parameters (parameter)+ >

<!ELEMENT parameter (default?) >
<!ATTLIST parameter
	id ID #REQUIRED
	name NMTOKEN #IMPLIED
	bits NMTOKEN #REQUIRED >

<!ELEMENT default (constant|minus|plus|complement|mask|parmeterref) >

<!ELEMENT complement (minus|plus|parameterref|mask) >
<!ATTLIST complement
    bits NMTOKEN #REQUIRED >

<!ELEMENT minus (constant|parameterref)+ >

<!ELEMENT parameterref EMPTY >
<!ATTLIST parameterref
	parameter IDREF #REQUIRED >

<!ELEMENT constant EMPTY >
<!ATTLIST constant
	value NMTOKEN #REQUIRED >

<!ELEMENT irpnotation-new (#PCDATA) >

<!ELEMENT irpnotation-old (#PCDATA) >

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/release-0.5.0/protocols/nrc17.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<!-- 
Reference: http://www.sbprojects.com/knowledge/ir/nrc17.htm,
 see also http://www.hifi-remote.com/forums/viewtopic.php?t=1044
 -->
<irprotocol name="nrc17" id="nrc17">
  <jp1data>
    <protocol number="00 bd" name="NRC17"/>
    <tohex function="reverse_complement" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="4"/>
    <parameter id="subdevice" bits="4"/>
    <parameter id="cmdno" bits="8"/>
  </parameters>
  <frequency value="38000"/>
  <body>
    <timings>
      <timing id="t1" cycles="19"/>
      <timing id="t5" cycles="95"/>
      <timing id="t_end_intro" cycles="760"/>
      <timing id="t_end_repeat" cycles="3000"/>
    </timings>
    <pairs>
      <pair id="p0">
        <zero timing="t1"/>
        <one timing="t1"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
    </pairs>
    <intro>
      <one timing="t1"/>
      <zero timing="t5"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="1">
	<constant value="1"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<constant value="254"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<constant value="255"/>
      </coded_number>
      <zero timing="t_end_intro"/>
    </intro>
    <repeat>
      <one timing="t1"/>
      <zero timing="t5"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="1">
	<constant value="1"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="4">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="4">
	<parameterref parameter="subdevice"/>
      </coded_number>
      <zero timing="t_end_repeat"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/2011-06-05/protocols/panasonic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="panasonic" id="panasonic">
  <jp1data>
    <protocol number="00C9" name="panasonic"/> <!-- 001F 00C9 00CD -->
    <tohex function="reverse_complement" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="8"/>
    <parameter id="subdevice" bits="8"/>
    <parameter id="cmdno" bits="8"/>
  </parameters>
  <frequency value="37000"/>
  <irpnotation-new>
<![CDATA[
IRP notation: {37k,432}<1,-1,1,-3>(8,-4,2:8,32:8,D:8,S:8,F:8,(D^S^F):8,1,-173)+ 
]]>
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="16"/>
      <timing id="t3" cycles="48"/>
      <timing id="t8" cycles="128"/>
      <timing id="t4" cycles="64"/>
      <timing id="t173" cycles="1384"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t3"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <one timing="t8"/>
      <zero timing="t4"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<constant value="2"/><!-- OEM code1 for Kaseiko -->
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<constant value="32"/><!-- OEM code2 for Kaseiko -->
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="subdevice"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<xor>
	  <parameterref parameter="deviceno"/>
	  <parameterref parameter="subdevice"/>
	  <parameterref parameter="cmdno"/>
	</xor>
      </coded_number>
      <one timing="t1"/>
      <zero timing="t173"/>
     </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/snapshot-0.5.2/protocols/apple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<!-- Created from IRWidget dumps and -->
<!-- http://www.hifi-remote.com/forums/viewtopic.php?t=5317 -->
<irprotocol name="apple" id="apple">
  <!--jp1data>
    <protocol number="00 5A" name="apple"/>
    <tohex function="reverse_complement" bits="8"/>
  </jp1data-->
  <parameters>
    <parameter id="deviceno" bits="8"/>
    <parameter id="cmdno" bits="8"/>
  </parameters>
  <frequency value="37683"/>
  <body>
    <timings>
      <timing id="t1" cycles="22"/>
      <timing id="t2" cycles="21"/>
      <timing id="t3" cycles="65"/>
      <timing id="t16" cycles="342"/>
      <timing id="t8" cycles="173"/>
      <timing id="t78" cycles="1516"/>
      <timing id="t4" cycles="86"/>
      <timing id="t173" cycles="3680"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t2"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t3"/>
      </pair>
    </pairs>
    <intro>
      <one timing="t16"/>
      <zero timing="t8"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<constant value="238"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<constant value="135"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <one timing="t1"/>
      <zero timing="t78"/>
    </intro>
    <repeat>
      <one timing="t16"/>
      <zero timing="t4"/>
      <one timing="t1"/>
      <zero timing="t173"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/protocols/nec1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="nec1" id="nec1">
  <jp1data>
    <protocol number="00 5A" name="NEC1"/>
    <tohex function="reverse-invert" bits="8"/>
  </jp1data>
  <cooked-ccf-string format="900A 006D 0000 0001 %02x%02x %02x%02x">
    <parameterref parameter="deviceno"/>
    <parameterref parameter="subdevice"/>
    <parameterref parameter="cmdno"/>
    <complement bits="8">
      <parameterref parameter="cmdno"/>
    </complement>
  </cooked-ccf-string>
  <parameters>
    <parameter id="deviceno" bits="8"/>
    <parameter id="subdevice" bits="8">
      <default>
        <complement bits="8">
	  <parameterref parameter="deviceno"/>
        </complement>
      </default>
    </parameter>
    <parameter id="cmdno" bits="8"/>
  </parameters>
  <frequency value="38400"/>
  <irpnotation-new>
protocol={38.4k,564}&lt;1,-1|1,-3>(16,-8,D:8,S:8,F:8,~F:8,1,-78,(16,-4,1,-173)*)
user=d,Device
user=s,Subdevice
user=f,Function
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="21"/>
      <timing id="t3" cycles="63"/>
      <timing id="t16" cycles="336"/>
      <timing id="t8" cycles="168"/>
      <timing id="t78" cycles="1638"/>
      <timing id="t4" cycles="84"/>
      <timing id="t173" cycles="3633"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t3"/>
      </pair>
    </pairs>
    <intro>
      <one timing="t16"/>
      <zero timing="t8"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="subdevice"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
        <complement bits="8">
	  <parameterref parameter="cmdno"/>
        </complement>
      </coded_number>
      <one timing="t1"/>
      <zero timing="t78"/>
    </intro>
    <repeat>
      <one timing="t16"/>
      <zero timing="t4"/>
      <one timing="t1"/>
      <zero timing="t173"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/last_as_harc/protocols/pioneer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="pioneer" id="pioneer">
  <jp1data>
    <protocol number="00 E2" name="Pioneer"/>
    <tohex function="reverse_complement" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="8"/>
    <parameter id="subdevice" bits="8">
      <default>
        <complement bits="8">
	  <parameterref parameter="deviceno"/>
        </complement>
      </default>
    </parameter>
    <parameter id="cmdno" bits="8"/>
  </parameters>
  <frequency value="40000"/>
  <irpnotation-new>
Protocol={40k,564}&lt;1,-1|1,-3>(16,-8,D:8,S:8,F:8,~F:8,1,-78)+
user=d,Device
user=s,Subdevice
user=f,Function
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="23"/>
      <timing id="t3" cycles="68"/>
      <timing id="t16" cycles="360"/>
      <timing id="t8" cycles="180"/>
      <timing id="t78" cycles="1730"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t3"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <one timing="t16"/>
      <zero timing="t8"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="subdevice"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
        <complement bits="8">
	  <parameterref parameter="cmdno"/>
        </complement>
      </coded_number>
      <one timing="t1"/>
      <zero timing="t78"/>
    </repeat>
  </body>
<!--
	super(0x0068, new pulse_pair(0x0017, 0x0017),
	      new pulse_pair(0x0017, 0x0044), "command_name");
	repeat_sequence.setleadin(new pulse_pair(0x0169, 0x00b4));
	repeat_sequence.setdata(array_lsb(device, 8));
	repeat_sequence.appenddata(array_lsb(subdevice, 8));
	repeat_sequence.appenddata(array_lsb(command, 8));
	repeat_sequence.appenddata(invert_bitarray(array_lsb(command, 8)));
	repeat_sequence.setleadout(new pulse_pair(0x0017, 0x06e0));
-->
</irprotocol>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/2012-06-07/protocols/denon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="denon" id="denon">
  <!-- Called Sharp by Denon (the firm) ... -->
  <jp1data>
    <protocol number="00 9C" name="Denon"/>
    <tohex function="reverse_complement" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="5"/>
    <parameter id="cmdno" bits="8"/>
  </parameters>
  <frequency value="38000"/>
  <irpnotation-new>
protocol={38k,264}&lt;1,-3|1,-7>(D:5,F:8,0:2,1,-165,D:5,~F:8,3:2,1,-165)+
user=d,Device
user=f,Function
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="10"/>
      <timing id="t3" cycles="30"/>
      <timing id="t7" cycles="70"/>
      <timing id="t165" cycles="1650"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t3"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t7"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <coded_number direction="lsb" zero="p0" one="p1" bits="5">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="2">
	<constant value="0"/>
      </coded_number>
      <one timing="t1"/>
      <zero timing="t165"/>
      <coded_number direction="lsb" zero="p0" one="p1" bits="5">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="8">
        <complement bits="8">
	  <parameterref parameter="cmdno"/>
        </complement>
      </coded_number>
      <coded_number direction="lsb" zero="p0" one="p1" bits="2">
	<constant value="3"/>
      </coded_number>
      <one timing="t1"/>
      <zero timing="t165"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/protocols/rc5x.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="rc5x" id="rc5x">
  <!-- DecodeIR:
  What we call "Device" is really the "System". What we call Subdevice is really
  the "Command". What we call "OBC" is really the "Data". If you are using
  ProntoEdit to create the RC5 signals directly, that GUI uses that correct
  (System, Command and Data) Philips terminolgy.
  -->
  <jp1data>
    <protocol number="00 F2" name="RC5x"/>
    <tohex function="reverse-invert" bits="8"/>
  </jp1data>
  <cooked-ccf-string format="FIXME 5000 0073 0000 0001 %04x %04x">
    <parameterref parameter="deviceno"/>
    <parameterref parameter="cmdno"/>
  </cooked-ccf-string>
  <parameters>
    <parameter id="deviceno" name="system" bits="6"/>
    <parameter id="subdevice" name="command" bits="7"/>
    <parameter id="cmdno" name="data" bits="6"/>
    <parameter id="toggle" bits="1"/>
  </parameters>
  <frequency value="36000"/>
  <irpnotation-new>
RC5:  {36k,msb,889}&lt;1,-1|-1,1>(1:1,~F:1:6,T:1,D:5,F:6,^128)+
RC5x: {36k,msb,889}&lt;1,-1|-1,1>(1:1,~S:1:6,T:1,D:6,-4,S:6,F:6,^114m)+
(should be D:5 instead of D:6)
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="32"/>
      <timing id="t4" cycles="128"/>
      <timing id="ttotal" cycles="4104"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t1"/>
      </pair>
      <pair id="p1">
        <zero timing="t1"/>
        <one timing="t1"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="1"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<complement bits="1">
	  <mask mask="64" shift="-6">
	    <parameterref parameter="subdevice"/>
	  </mask>
	</complement>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<parameterref parameter="toggle"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="5">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <zero timing="t4"/>
      <coded_number direction="msb" zero="p0" one="p1" bits="6">
	<parameterref parameter="subdevice"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="6">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <zeropadding timing="ttotal"/>
    </repeat>
  </body>
</irprotocol>

=== bengtmartensson/oldharctoolbox/protocols/recs80.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irprotocol PUBLIC "-//bengt-martensson.de//irprotocols//en"
 "../dtds/irprotocols.dtd">
<irprotocol name="recs80" id="recs80">
<!--  http://www.sbprojects.com/knowledge/ir/recs80.htm -->
<jp1data>
    <protocol number="0045" name="RECS80"/>
    <tohex function="reverse-invert" bits="8"/>
  </jp1data>
  <parameters>
    <parameter id="deviceno" bits="3"/>
    <parameter id="cmdno" bits="6"/>
    <parameter id="toggle" bits="1"/>
  </parameters>
  <frequency value="38000"/>
  <irpnotation-new>
<![CDATA[
{38k,158,msb}<1,-31|1,-47>(1:1,T:1,D:3,F:6,1,-45m)+
]]>
  </irpnotation-new>
  <body>
    <timings>
      <timing id="t1" cycles="6"/>
      <timing id="t31" cycles="186"/>
      <timing id="t47" cycles="282"/>
      <timing id="t45m" cycles="1710"/>
    </timings>
    <pairs>
      <pair id="p0">
        <one timing="t1"/>
        <zero timing="t31"/>
      </pair>
      <pair id="p1">
        <one timing="t1"/>
        <zero timing="t47"/>
      </pair>
    </pairs>
    <intro/>
    <repeat>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<constant value="1"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="1">
	<parameterref parameter="toggle"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="3">
	<parameterref parameter="deviceno"/>
      </coded_number>
      <coded_number direction="msb" zero="p0" one="p1" bits="6">
	<parameterref parameter="cmdno"/>
      </coded_number>
      <one timing="t1"/>
      <zeropadding timing="t45m"/>
    </repeat>
  </body>
</irprotocol>
