=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/dtds/devices.dtd
<!-- Presently, id's for devices are not supported -->

<!ELEMENT devices (device)+ >

<!ELEMENT device (attributes?,aliases?,jp1data?,commandset+) >
<!ATTLIST device
        id ID #REQUIRED
        name CDATA #REQUIRED
        vendor CDATA #IMPLIED
        vendorurl CDATA #IMPLIED
        model CDATA #REQUIRED
        pingable_on (yes|no) #IMPLIED
        pingable_standby (yes|no) #IMPLIED
        type     (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|dumb|undefined) "undefined"
        alt_type (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|dumb|undefined) "undefined" >

<!ELEMENT attributes (attribute|has-attribute)+ >

<!ELEMENT attribute EMPTY >
<!ATTLIST attribute
	name NMTOKEN #REQUIRED
	value CDATA #IMPLIED >

<!ELEMENT has-attribute EMPTY >
<!ATTLIST has-attribute
	name NMTOKEN #REQUIRED
	value (yes|no) "yes" >

<!ELEMENT aliases (alias+) >

<!ELEMENT alias EMPTY >
<!ATTLIST alias
	name NMTOKEN #REQUIRED
        command NMTOKEN #REQUIRED >

<!ELEMENT jp1data (setupcode|fixed_data)+ >

<!ELEMENT setupcode EMPTY >
<!ATTLIST setupcode
	value CDATA #REQUIRED >

<!ELEMENT fixed_data EMPTY >
<!ATTLIST fixed_data
	data CDATA #REQUIRED >

<!ELEMENT commandset (commandgroup|commandgroupref|command)+ >
<!ATTLIST commandset
        type (ir|rf433|rf868|www|web_api|tcp|udp|serial|bluetooth|on_off|ip) "ir"
        ifattribute CDATA #IMPLIED
        protocol NMTOKEN #IMPLIED
        prefix CDATA ""
        suffix CDATA ""
        portnumber CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        subdevice CDATA #IMPLIED
        fixed_data CDATA #IMPLIED
        toggle (yes|no) "no"
        wol (yes|no) "no"
        name CDATA #IMPLIED
        original_remote CDATA #IMPLIED
        remotename NMTOKEN #IMPLIED
        delay_between_chars CDATA "0"
 	pseudo_power_on NMTOKEN #IMPLIED
 	delay_between_reps CDATA "0"
 	remark CDATA #IMPLIED >

<!ELEMENT commandgroup (commandgroup|command)+ >
<!ATTLIST commandgroup
        id ID #IMPLIED
        name CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        description CDATA #IMPLIED >

<!ELEMENT commandgroupref EMPTY >
<!ATTLIST commandgroupref
        commandgroup IDREF #REQUIRED >

<!-- For now, there are no more than one argument accepted -->
<!ELEMENT command ((toggle_pair|ccf)?,remark?,argument*,returnvalues?) >
<!ATTLIST command
        cmdref NMTOKEN #REQUIRED
        cmdno CDATA #IMPLIED
        name CDATA #IMPLIED
	zone (1|2|3|record) #IMPLIED
        type (discrete|toggle|cyclic) #IMPLIED
	remark CDATA #IMPLIED
        ifattribute NMTOKEN #IMPLIED
        wakeup (yes|no) #IMPLIED
        transmit CDATA #IMPLIED
        expected_response CDATA #IMPLIED
        response_ending CDATA #IMPLIED
        returntype CDATA #IMPLIED
        returnwidth CDATA #IMPLIED
        returncontent CDATA #IMPLIED
        response_lines CDATA #IMPLIED >

<!ELEMENT returnvalues (syntax?,semantics?,description?) >

<!ELEMENT syntax (returntype*) >
<!ATTLIST syntax
	parse CDATA #IMPLIED >

<!ELEMENT semantics (table) >
<!ELEMENT returntype EMPTY >
<!ATTLIST returntype
	type (string|texttable|decimal_integer|hexadecimal_integer|hh:mm:ss|dd.mm.yyyy|tv_radio|0_1|on_off|percent|4:3_16:9|dbox_videoformat|dbox_videooutput) #REQUIRED
	length CDATA #IMPLIED >

<!ELEMENT table (entry+,default?) >
<!ATTLIST table
	index (string|number|hexnumber) "string" >

<!ELEMENT entry EMPTY >
<!ATTLIST entry
	value CDATA #REQUIRED
	desc CDATA "" >

<!ELEMENT default EMPTY >
<!ATTLIST default
	desc CDATA "" >

<!ELEMENT remark (#PCDATA) >

<!ELEMENT argument (description)? >
<!ATTLIST argument
        name CDATA #REQUIRED
        semantic CDATA #IMPLIED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT ccf (#PCDATA) >
<!ATTLIST ccf
	toggle (0|1) #IMPLIED >

<!ELEMENT toggle_pair (ccf, ccf) >

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/pioneer_dvd525.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<devices>
  <device id="pioneer_dvd525" name="Pioneer DVD 525" vendor="Pioneer" model="DVD525" type="dvd">
    <commandset type="ir" protocol="xxx" toggle="no" deviceno="0" remotename="pioneer_dvd525">
<!--
stop		F1 Q 000 R 1110 S L
pause		F1 Q 111 R 0000 S L
prev		F1 Q 101 R 0100 S L
next		F1 Q 001 R 1100 S L
play		F1 Q 011 R 1000 S L
power_toggle	F2 Q 100 R 0110 S L A B T 0011110111000010L
open		F2 Q 100 R 0110 S L A B T 0110110110010010L
rewind		F1 Q 110 R 0010 S L
fast_forward	F1 Q 010 R 1010 S L
step_forward	F2 Q 100 R 0110 S L A B T 1110110100010010L
step_back	F2 Q 100 R 0110 S L A B T 0001110111100010L
up		F2 Q 100 R 0110 S L A B T 0100111110110000L
down		F2 Q 100 R 0110 S L A B T 1100111100110000L
left		F2 Q 100 R 0110 S L A B T 1100011000111001L
OK		F2 Q 100 R 0110 S L A B T 1111011100001000L
top		F2 Q 100 R 0110 S L A B T 0010110111010010L
return		F2 Q 100 R 0110 S L A B T 0010111111010000L
menu		F2 Q 100 R 0110 S L A B T 1001110101100010L
setup		F2 Q 100 R 0110 S L A B T 0000110111110010L
right		F2 Q 100 R 0110 S L A B T 0010011011011001L
1		F2 Q 100 R 0110 S L A B T 1000010101111010L
2		F2 Q 100 R 0110 S L A B T 0100010110111010L
3		F2 Q 100 R 0110 S L A B T 1100010100111010L
4		F2 Q 100 R 0110 S L A B T 0010010111011010L
5		F2 Q 100 R 0110 S L A B T 1010010101011010L
6		F2 Q 100 R 0110 S L A B T 0110010110011010L
7		F2 Q 100 R 0110 S L A B T 1110010100011010L
8		F2 Q 100 R 0110 S L A B T 0001010111101010L
9		F2 Q 100 R 0110 S L A B T 1001010101101010L
0		F2 Q 100 R 0110 S L A B T 0000010111111010L
???		F2 Q 100 R 0110 S L A B T 1010011101011000L
display		F2 Q 100 R 0110 S L A B T 1100011100111000L
two_dig 	F2 Q 100 R 0110 S L A B T 1111110100000010L
search mode	F2 Q 100 R 0110 S L A B T 1100110100110010L
vnr		F2 Q 100 R 0110 S L A B T 0000110011110011L
cond memory	F2 Q 100 R 0110 S L A B T 1000110101110010L
last memory	F2 Q 100 R 0110 S L A B T 0110111110010000L
subtitles	F2 Q 100 R 0110 S L A B T 0110110010010011L
angle		F2 Q 100 R 0110 S L A B T 1010110101010010L
audio		F2 Q 100 R 0110 S L A B T 0111110110000010L
random		F2 Q 100 R 0110 S L A B T 0111111110000000L
repeat		F2 Q 100 R 0110 S L A B T 0010011111011000L
program		F2 Q 100 R 0110 S L A B T 0011011111001000L
A-B		F2 Q 100 R 0110 S L A B T 0001011111101000L
power_on	F3 Q 100 R 0110 S L A B T 0101110110100010L
power_off	F3 Q 100 R 0110 S L A B T 1101110100100010L
-->
      <command cmdref="cmd_0"                   cmdno="0x98"/>
      <command cmdref="cmd_1"                   cmdno="0x08"/>
      <command cmdref="cmd_2"                   cmdno="0x88"/>
      <command cmdref="cmd_3"                   cmdno="0x48"/>
      <command cmdref="cmd_4"                   cmdno="0xc8"/>
      <command cmdref="cmd_5"                   cmdno="0x28"/>
      <command cmdref="cmd_6"                   cmdno="0xa8"/>
      <command cmdref="cmd_7"                   cmdno="0x68"/>
      <command cmdref="cmd_8"                   cmdno="0xe8"/>
      <command cmdref="cmd_9"                   cmdno="0x18"/>
      <command cmdref="cmd_a_b"                 cmdno="0x12"/>
      <command cmdref="cmd_a_srd"               cmdno="0x79"/>
      <command cmdref="cmd_angle"               cmdno="0x09"/>
      <command cmdref="cmd_audio"               cmdno="0xcc"/>
      <command cmdref="cmd_audio_only" 		cmdno="0x87"/>
      <command cmdref="cmd_clear" name="cancel"	cmdno="0xc1"/>
      <command cmdref="cmd_depth_enh"           cmdno="0x1b"/>
      <command cmdref="cmd_display"             cmdno="0x49"/>
      <command cmdref="cmd_double_remaster"	cmdno="0x97"/>
      <command cmdref="cmd_down" 		cmdno="0x61"/>
      <command cmdref="cmd_fast_forward" 	cmdno="0xa0"/>
      <command cmdref="cmd_group" 		cmdno="0x07"/>
      <command cmdref="cmd_left" 		cmdno="0xe1"/>
      <command cmdref="cmd_marker" 		cmdno="0x71"/>
      <command cmdref="cmd_menu" 		cmdno="0x01"/>
      <command cmdref="cmd_next" 		cmdno="0x52"/>
      <command cmdref="cmd_ok" 			cmdno="0x41"/>
      <command cmdref="cmd_open_close" 		cmdno="0x80"/>
      <command cmdref="cmd_still_advance" 	cmdno="0x60"/>
      <command cmdref="cmd_play" 		cmdno="0x50"/>
      <command cmdref="cmd_play_mode" 		cmdno="0xb1"/>
      <command cmdref="cmd_pos_mem" 		cmdno="0x62"/>
      <command cmdref="cmd_power_off" 		cmdno="0xfc"/>
      <command cmdref="cmd_power_on" 		cmdno="0x7c"/>
      <command cmdref="cmd_power_toggle" 	cmdno="0xbc"/>
      <command cmdref="cmd_previous" 		cmdno="0x92"/>
      <command cmdref="cmd_repeat" 		cmdno="0x31"/>
      <command cmdref="cmd_return" 		cmdno="0x81"/>
      <command cmdref="cmd_rewind" 		cmdno="0x20"/>
      <command cmdref="cmd_right" 		cmdno="0x11"/>
      <command cmdref="cmd_setup" 		cmdno="0x29"/>
      <command cmdref="cmd_sleep" 		cmdno="0xd7"/>
      <command cmdref="cmd_special" 		cmdno="0xa2"/>
      <command cmdref="cmd_stop" 		cmdno="0x00"/>
      <command cmdref="cmd_subtitle" 		cmdno="0x89"/>
      <command cmdref="cmd_title" 		cmdno="0xd9"/>
      <command cmdref="cmd_two_digit" name="./.." cmdno="0x91"/>
      <command cmdref="cmd_up" 			cmdno="0xa1"/>
      <command cmdref="cmd_vss" 		cmdno="0x79"/>
      <command cmdref="cmd_zoom" 		cmdno="0x83"/>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/door_toggle_memory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="door_toggle_memory" vendor="generic" name="open/close door with
    only one command, and memory, as well as a sensor" model="generic" type="dumb">
    <attributes>
      <has-attribute name="memory"/>
      <has-attribute name="forget" value="no"/>
    </attributes>
    <aliases>
      <alias name="open_close" command="power_pulse"/>
    </aliases>
    <commandset type="on_off">
      <command cmdref="cmd_power_on"/>
      <command cmdref="cmd_power_off"/>
      <command cmdref="cmd_power_toggle"/>
      <command cmdref="cmd_power_pulse"/>
      <command cmdref="get_state">
	<returnvalues>
	  <semantics>
	    <table>
	      <entry value="on" desc="closed"/>
	      <entry value="off" desc="open"/>
	    </table>
	  </semantics>
	</returnvalues>
      </command>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/2012-06-07/devices/pioneer_cld925.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="pioneer_cld925" name="Pioneer CLD-925" vendor="Pioneer" model="CLD-925" type="ld">
  <jp1data>
    <setupcode value="1059"/>
  </jp1data>
  <commandset type="ir" protocol="pioneer" deviceno="168" remotename="pioneer_cld925" original_remote="cu-cld115">
    <command cmdref="power_toggle"		cmdno="28"/>
    <command cmdref="power_on"			cmdno="26"/>
    <command cmdref="power_off"			cmdno="27"/>
    <command cmdref="open_close"		cmdno="25"/><!-- was 22 -->
    <command cmdref="digital_sound"		cmdno="12"/>
    <command cmdref="analog_sound"		cmdno="30"/>
    <command cmdref="repeat"			cmdno="68"/>
    <command cmdref="a_b"			cmdno="72"/>
    <command cmdref="display"			cmdno="67"/>
    <command cmdref="cmd_1"			cmdno="1"/>
    <command cmdref="cmd_2"			cmdno="2"/>
    <command cmdref="cmd_3"			cmdno="3"/>
    <command cmdref="clear"			cmdno="69"/>
    <command cmdref="program"			cmdno="76"/>
    <command cmdref="cmd_4"			cmdno="4"/>
    <command cmdref="cmd_5"			cmdno="5"/>
    <command cmdref="cmd_6"			cmdno="6"/>
    <command cmdref="plus10"			cmdno="31"/>
    <command cmdref="chapter_time"		cmdno="19"/>
    <command cmdref="cmd_7"			cmdno="7"/>
    <command cmdref="cmd_8"			cmdno="8"/>
    <command cmdref="cmd_9"			cmdno="9"/>
    <command cmdref="cmd_0"			cmdno="0"/>
    <command cmdref="memory_play"		cmdno=""/>
    <command cmdref="speed_down"		cmdno="85"/>
    <command cmdref="speed_up"			cmdno="88"/>
    <command cmdref="step_back"			cmdno="80"/>
    <command cmdref="step_forward"		cmdno="84"/>
    <command cmdref="shuffle"			cmdno="94"/>
    <command cmdref="intro"	name="hilite intro" cmdno="90"/>
    <command cmdref="previous"			cmdno="83"/>
    <command cmdref="next"			cmdno="82"/>
    <command cmdref="rewind"			cmdno="17"/>
    <command cmdref="play"			cmdno="23"/>
    <!--command cmdref="play"			cmdno="22"/-->
    <command cmdref="fast_forward"		cmdno="16"/>
    <command cmdref="side_a"			cmdno="77"/>
    <command cmdref="side_b"			cmdno="78"/>
    <command cmdref="stop"			cmdno="23"/>
    <command cmdref="pause_toggle"		cmdno="24"/>
    <command cmdref="aspectratio_16_9"		cmdno="18"/>
    <!--
    Disc Side Toggle*,021,,enter,23 - +10,not on OEM remote,,,,,,,
    edit,029,,up arrow,51 - Multi-Speed +,,,,,,,,
    Audio,030,,down arrow,50 - Multi-Speed -,,,,,,,,
    Jog Forward*,032,,right arrow,66 - Multi-Speed >,not on OEM remote,,,,,,,63 - step +
    Jog Forward x2*,033,,select,21 - edit,not on OEM remote,,,,,,,
    Jog Forward x3*,034,,sleep,,not on OEM remote,,,,,,,
    Jog Forward x4*,035,,pip,,not on OEM remote,,,,,,,
    Jog Reverse*,036,,info,47 - Display,not on OEM remote,,,,,,,
    Jog Reverse x2*,037,,swap,52 - Repeat A*,not on OEM remote,,,,,,,
    Jog Reverse x3*,038,,move,48 - Repeat (B),not on OEM remote,,,,,,,
    Jog Reverse x4*,039,,play,18 - play,not on OEM remote,,,,,,,
    shuttle forward,040,,pause,19 - pause,,,,,,,,
    shuttle forward x2,041,,rewind,14 - rewind,,,,,,,,
    shuttle forward x3,042,,fwd,13 - fast forward,,,,,,,,
    shuttle forward x4,043,,stop,17 - Stop/Eject,,,,,,,,
    shuttle back,044,,record,,,,,,,,,
    shuttle back x2,045,,exit,49 - Clear,,,,,,,,
    shuttle back x3,046,,surround,,,,,,,,,
    shuttle back x4,047,,input,,,,,,,,,
    Frame/Time Search*,065,,com/skip,,not on OEM remote,,,,,,,
    search memory*,066,,shift-right,,not on OEM remote,,,,,,,
    Display,067,,pip freeze,,,,,,,,,
    Repeat (B),068,,slow,,,,,,,,,
    Clear,069,,eject,,,,,,,,,
    Multi-Speed -,070,,slow+,,,,,,,,,
    Multi-Speed +,071,,slow-,,,,,,,,,
    Repeat A*,072,,x2,,not on OEM remote,,,,,,,
    2/R ch*,073,,center,,not on OEM remote,,,,,,,
    Stereo*,074,,rear,,not on OEM remote,,,,,,,
    1/L ch*,075,,phantom1,,not on OEM remote,,,,,,,
    Program,076,,phantom2,,,,,,,,,
    step -,080,,phantom6,,,,,,,,,
    Skip >>|,082,,phantom7,,,,,,,,,
    Skip |<<,083,,phantom8,,,,,,,,,
    step +,084,,phantom9,,,,,,,,,
    Multi-Speed <,085,,phantom10,,,,,,,,,
    D*,087,,setup,,not on OEM remote,,,,,,,
    Multi-Speed >,088,,light,,,,,,,,,
    still / strobe*,091,,home theater,,not on OEM remote,,,,,,,
    digital effect*,092,,M1,,not on OEM remote,,,,,,,
    1shot memory*,093,,M2,,not on OEM remote,,,,,,,
    random play,094,,M3,,,,,,,,,
    -->
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/2012-06-07/devices/sony_tv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="sony_tv" name="Sony TV" vendor="Sony" model="Generic" type="tv">
  <commandset type="ir" protocol="sony12" deviceno="1" remotename="sony_tv">
    <command cmdref="volume_up"			cmdno="0x12"/>
    <command cmdref="volume_down"		cmdno="0x13"/>
    <command cmdref="channel_up"		cmdno="0x10"/>
    <command cmdref="channel_down"		cmdno="0x11"/>
    <command cmdref="in_av"			cmdno="0x25"/>
    <command cmdref="mute_toggle"		cmdno="0x14"/>
    <command cmdref="power_toggle"		cmdno="0x15"/>
    <command cmdref="power_on"			cmdno="0x2e"/>
    <command cmdref="power_off"			cmdno="0x2f"/>
    <command cmdref="contrast_up"		cmdno="0x18"/>
    <command cmdref="contrast_down" 		cmdno="0x19"/>
    <command cmdref="color_up"			cmdno="0x1a"/>
    <command cmdref="color_down"		cmdno="0x1b"/>
    <command cmdref="color_up"			cmdno="0x1e"/>
    <command cmdref="color_down"		cmdno="0x1f"/>
    <command cmdref="info"			cmdno="0x3a"/>
    <command cmdref="cmd_1"			cmdno="0x00"/>
    <command cmdref="cmd_2"			cmdno="0x01"/>
    <command cmdref="cmd_3"			cmdno="0x02"/>
    <command cmdref="cmd_4"			cmdno="0x03"/>
    <command cmdref="cmd_5"			cmdno="0x04"/>
    <command cmdref="cmd_6"			cmdno="0x05"/>
    <command cmdref="cmd_7"			cmdno="0x06"/>
    <command cmdref="cmd_8"			cmdno="0x07"/>
    <command cmdref="cmd_9"			cmdno="0x08"/>
    <command cmdref="cmd_0"			cmdno="0x09"/>
    <command cmdref="two_digit"			cmdno="0x39"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/philips_vr1100.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="philips_vr1100" name="Philips VCR VR1100" vendor="Philips" model="VR1100" type="vcr">
  <jp1data>
    <setupcode value="1234"/>
  </jp1data>
  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="5" remotename="philips_vr1100">
    <command cmdref="cmd_0" 				cmdno="0"/>
    <command cmdref="cmd_1" 				cmdno="1"/>
    <command cmdref="cmd_2" 				cmdno="2"/>
    <command cmdref="cmd_3" 				cmdno="3"/>
    <command cmdref="cmd_4" 				cmdno="4"/>
    <command cmdref="cmd_5" 				cmdno="5"/>
    <command cmdref="cmd_6" 				cmdno="6"/>
    <command cmdref="cmd_7" 				cmdno="7"/>
    <command cmdref="cmd_8" 				cmdno="8"/>
    <command cmdref="cmd_9" 				cmdno="9"/>
    <command cmdref="cmd_power_toggle" name="power"	cmdno="12"/>
    <command cmdref="cmd_in_tv"				cmdno="63"/>
    <command cmdref="cmd_vcr_tv" 			cmdno="62"/>
    <command cmdref="cmd_previous" 			cmdno="37"/>
    <command cmdref="cmd_next" 				cmdno="38"/>
    <command cmdref="cmd_still_advance" 		cmdno="41"/>
    <command cmdref="cmd_open" 				cmdno="45"/>
    <command cmdref="cmd_clear" 			cmdno="49"/>
    <command cmdref="cmd_play" 				cmdno="53"/>
    <command cmdref="cmd_rewind" 			cmdno="50"/>
    <command cmdref="cmd_fast_forward" 			cmdno="52"/>
    <command cmdref="cmd_stop" 				cmdno="54"/>
    <command cmdref="cmd_channel_up" 			cmdno="32"/>
    <command cmdref="cmd_channel_down" 			cmdno="33"/>
    <command cmdref="cmd_record_toggle"			cmdno="55"/>
    <command cmdref="cmd_info" 				cmdno="15"/>
    <command cmdref="cmd_smart_picture" 		cmdno="70"/>
    <command cmdref="cmd_ok" 				cmdno="87"/>
    <command cmdref="cmd_skip_search" 			cmdno="106"/>
    <command cmdref="cmd_rec_end_search" 		cmdno="117"/>
    <command cmdref="cmd_menu" 				cmdno="82"/>
    <command cmdref="cmd_timer" 			cmdno="69"/>
    <command cmdref="cmd_turbo_timer" 			cmdno="28"/>
    <command cmdref="cmd_lp_sp" 			cmdno="58"/>
    <command cmdref="cmd_I_II" 				cmdno="35"/>
    <command cmdref="cmd_standby" 			cmdno="6"/>

    <!-- power_on = standby + power_toggle -->
    <!-- power_off = standby + standby -->
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/philips_28ml8805.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="philips_28ml8805" name="Philips TV 28ML8805" vendor="Philips" model="28ML8805" type="tv">
  <jp1data>
    <setupcode value="1234"/>
  </jp1data>
  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="0"
    remotename="philips_28ml8805">
    <command cmdref="cmd_0" 				cmdno="0"/>
    <command cmdref="cmd_1" 				cmdno="1"/>
    <command cmdref="cmd_2" 				cmdno="2"/>
    <command cmdref="cmd_3" 				cmdno="3"/>
    <command cmdref="cmd_4" 				cmdno="4"/>
    <command cmdref="cmd_5" 				cmdno="5"/>
    <command cmdref="cmd_6" 				cmdno="6"/>
    <command cmdref="cmd_7" 				cmdno="7"/>
    <command cmdref="cmd_8" 				cmdno="8"/>
    <command cmdref="cmd_9" 				cmdno="9"/>
    <command cmdref="cmd_power_off" name="power"	cmdno="12"/>
    <command cmdref="cmd_tv_mode"			cmdno="63"/>
    <command cmdref="cmd_channel_up" 			cmdno="32"/>
    <command cmdref="cmd_channel_down" 			cmdno="33"/>
    <command cmdref="cmd_mute_toggle" name="mute"	cmdno="13"/>
    <command cmdref="cmd_last_channel" 			cmdno="34"/>
    <command cmdref="cmd_volume_up" 			cmdno="16"/>
    <command cmdref="cmd_volume_down" 			cmdno="17"/>
    <command cmdref="cmd_PP" 				cmdno="14"/>
    <command cmdref="cmd_info" 				cmdno="15"/>
    <command cmdref="cmd_brightness_down" 		cmdno="19"/>
    <command cmdref="cmd_brightness_up" 		cmdno="18"/>
    <command cmdref="cmd_aspectratio"	 		cmdno="126"/>
    <command cmdref="cmd_menu" 				cmdno="82"/>
    <command cmdref="cmd_up" 				cmdno="80"/>
    <command cmdref="cmd_down" 				cmdno="81"/>
    <command cmdref="cmd_red" 				cmdno="107"/>
    <command cmdref="cmd_green" 			cmdno="108"/>
    <command cmdref="cmd_yellow" 			cmdno="109"/>
    <command cmdref="cmd_blue" 				cmdno="110"/>
    <command cmdref="cmd_white" 			cmdno="111"/>
    <command cmdref="cmd_menu_off" 			cmdno="83"/>
    <command cmdref="cmd_I_II" 				cmdno="35"/>
    <command cmdref="cmd_teletext" 			cmdno="60"/>
    <command cmdref="cmd_teletext_freeze" 		cmdno="41"/>
    <command cmdref="cmd_teletext_reveal" 		cmdno="44"/>
    <command cmdref="cmd_teletext_hide" 		cmdno="45"/>
    <command cmdref="cmd_teletext_translucent" 		cmdno="46"/>
    <command cmdref="cmd_teletext_doubleheight" 	cmdno="43"/>
    <command cmdref="cmd_teletext_time" 		cmdno="42"/>
    <command cmdref="cmd_PIP" 				cmdno="88"/>
    <command cmdref="cmd_PIP_source" 			cmdno="95"/>
    <command cmdref="cmd_PIP_exchange" 			cmdno="90"/>
    <command cmdref="cmd_PIP_freeze" 			cmdno="101"/>
    <command cmdref="cmd_PIP_position" 			cmdno="89"/>
    <command cmdref="cmd_PIP_ch_down" 			cmdno="103"/>
    <command cmdref="cmd_PIP_ch_up" 			cmdno="102"/>
    <command cmdref="cmd_freeze_toggle"			cmdno="93"/>
    <command cmdref="cmd_DNR" 				cmdno="97"/>
    <command cmdref="cmd_special" 			cmdno="94"/>
  </commandset>

  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="12"
    remotename="philips_28ml8805" pseudo_power_on="cmd_in_aux">
    <command cmdref="cmd_in_aux"		 	cmdno="63"/>
  </commandset>
  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="5" remotename="philips_28ml8805">
    <command cmdref="cmd_in_vcr"			cmdno="63"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/release-0.7.0/devices/onkyo_tx_sv9041.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="onkyo_tx_sv9041" name="Onkyo TX-SV9041" vendor="Onkyo" model="tx_sv9041" type="receiver">
  <commandset type="ir" protocol="nec1" deviceno="210" subdevice="109" remotename="onkyo_tx_sv9041">
    <command cmdref="power_toggle" cmdno="4"/>
    <command cmdref="sleep" cmdno="93"/>
    <command cmdref="main_spk_toggle" cmdno="89"/>
    <command cmdref="zone2_spk_toggle" cmdno="90"/>
    <command cmdref="zone2_source" cmdno="204"/>
    <command cmdref="in_tape1" cmdno="8"/>
    <command cmdref="in_phono" cmdno="10"/>
    <command cmdref="in_cd" cmdno="9"/>
    <command cmdref="zone2_volume_up" cmdno="194"/>
    <command cmdref="in_tuner" cmdno="11"/>
    <command cmdref="in_tape2" cmdno="7"/>
    <command cmdref="in_video1" cmdno="15"/>
    <command cmdref="in_video2" cmdno="14"/>
    <command cmdref="in_video3" cmdno="13"/>
    <command cmdref="zone2_volume_down" cmdno="195"/>
    <command cmdref="tuner_class_preset" cmdno="74"/>
    <command cmdref="channel_up" cmdno="0"/>
    <command cmdref="channel_down" cmdno="1"/>
    <command cmdref="mute_toggle" cmdno="5"/>
    <command cmdref="center_up" cmdno="128"/>
    <command cmdref="center_down" cmdno="129"/>
    <command cmdref="rear_up" cmdno="66"/>
    <command cmdref="rear_down" cmdno="67"/>
    <command cmdref="volume_up" cmdno="2"/>
    <command cmdref="volume_down" cmdno="3"/>
    <command cmdref="test_mode" cmdno="154"/>
    <command cmdref="surround_mode" cmdno="76"/>
    <command cmdref="delay_time" cmdno="83"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/snapshot-0.5.2/devices/netcat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="netcat" name="Pseudo device" model="-">
  <commandset type="tcp" suffix="\r">
    <command cmdref="talk" transmit="$1" response_lines="0">
      <argument name="transmit"/>
    </command>
    <command cmdref="talk_listen" transmit="$1" response_lines="-1">
      <argument name="transmit"/>
    </command>
    <command cmdref="talk_listen1" transmit="$1" response_lines="1">
      <argument name="transmit"/>
    </command>
    <command cmdref="talk_listen2" transmit="$1" response_lines="2">
      <argument name="transmit"/>
    </command>
    <command cmdref="talk_listen3" transmit="$1" response_lines="3">
      <argument name="transmit"/>
    </command>
  </commandset>
  <commandset type="tcp" suffix="">
    <command cmdref="listen" transmit="" response_lines="-1"/>
    <command cmdref="listen1" transmit="" response_lines="1"/>
    <command cmdref="listen2" transmit="" response_lines="2"/>
    <command cmdref="listen3" transmit="" response_lines="3"/>
  </commandset>
</device>
