=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/dtds/devices.dtd
<!-- Presently, id's for devices are not supported -->

<!ELEMENT devices (device)+ >

<!ELEMENT device (attributes?,aliases?,jp1data?,commandset+) >
<!ATTLIST device
        id ID #REQUIRED
        name CDATA #REQUIRED
        vendor CDATA #IMPLIED
        vendorurl CDATA #IMPLIED
        model CDATA #REQUIRED
        pingable_on (yes|no) #IMPLIED
        pingable_standby (yes|no) #IMPLIED
        type     (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|dumb|undefined) "undefined"
        alt_type (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|dumb|undefined) "undefined" >

<!ELEMENT attributes (attribute|has-attribute)+ >

<!ELEMENT attribute EMPTY >
<!ATTLIST attribute
	name NMTOKEN #REQUIRED
	value CDATA #IMPLIED >

<!ELEMENT has-attribute EMPTY >
<!ATTLIST has-attribute
	name NMTOKEN #REQUIRED
	value (yes|no) "yes" >

<!ELEMENT aliases (alias+) >

<!ELEMENT alias EMPTY >
<!ATTLIST alias
	name NMTOKEN #REQUIRED
        command NMTOKEN #REQUIRED >

<!ELEMENT jp1data (setupcode|fixed_data)+ >

<!ELEMENT setupcode EMPTY >
<!ATTLIST setupcode
	value CDATA #REQUIRED >

<!ELEMENT fixed_data EMPTY >
<!ATTLIST fixed_data
	data CDATA #REQUIRED >

<!ELEMENT commandset (commandgroup|commandgroupref|command)+ >
<!ATTLIST commandset
        type (ir|rf433|rf868|www|web_api|tcp|udp|serial|bluetooth|on_off|ip) "ir"
        ifattribute CDATA #IMPLIED
        protocol NMTOKEN #IMPLIED
        prefix CDATA ""
        suffix CDATA ""
        portnumber CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        subdevice CDATA #IMPLIED
        fixed_data CDATA #IMPLIED
        toggle (yes|no) "no"
        wol (yes|no) "no"
        name CDATA #IMPLIED
        original_remote CDATA #IMPLIED
        remotename NMTOKEN #IMPLIED
        delay_between_chars CDATA "0"
 	pseudo_power_on NMTOKEN #IMPLIED
 	delay_between_reps CDATA "0"
 	remark CDATA #IMPLIED >

<!ELEMENT commandgroup (commandgroup|command)+ >
<!ATTLIST commandgroup
        id ID #IMPLIED
        name CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        description CDATA #IMPLIED >

<!ELEMENT commandgroupref EMPTY >
<!ATTLIST commandgroupref
        commandgroup IDREF #REQUIRED >

<!-- For now, there are no more than one argument accepted -->
<!ELEMENT command ((toggle_pair|ccf)?,remark?,argument*,returnvalues?) >
<!ATTLIST command
        cmdref NMTOKEN #REQUIRED
        cmdno CDATA #IMPLIED
        name CDATA #IMPLIED
	zone (1|2|3|record) #IMPLIED
        type (discrete|toggle|cyclic) #IMPLIED
	remark CDATA #IMPLIED
        ifattribute NMTOKEN #IMPLIED
        wakeup (yes|no) #IMPLIED
        transmit CDATA #IMPLIED
        expected_response CDATA #IMPLIED
        response_ending CDATA #IMPLIED
        returntype CDATA #IMPLIED
        returnwidth CDATA #IMPLIED
        returncontent CDATA #IMPLIED
        response_lines CDATA #IMPLIED >

<!ELEMENT returnvalues (syntax?,semantics?,description?) >

<!ELEMENT syntax (returntype*) >
<!ATTLIST syntax
	parse CDATA #IMPLIED >

<!ELEMENT semantics (table) >
<!ELEMENT returntype EMPTY >
<!ATTLIST returntype
	type (string|texttable|decimal_integer|hexadecimal_integer|hh:mm:ss|dd.mm.yyyy|tv_radio|0_1|on_off|percent|4:3_16:9|dbox_videoformat|dbox_videooutput) #REQUIRED
	length CDATA #IMPLIED >

<!ELEMENT table (entry+,default?) >
<!ATTLIST table
	index (string|number|hexnumber) "string" >

<!ELEMENT entry EMPTY >
<!ATTLIST entry
	value CDATA #REQUIRED
	desc CDATA "" >

<!ELEMENT default EMPTY >
<!ATTLIST default
	desc CDATA "" >

<!ELEMENT remark (#PCDATA) >

<!ELEMENT argument (description)? >
<!ATTLIST argument
        name CDATA #REQUIRED
        semantic CDATA #IMPLIED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT ccf (#PCDATA) >
<!ATTLIST ccf
	toggle (0|1) #IMPLIED >

<!ELEMENT toggle_pair (ccf, ccf) >

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/rc5_cd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="rc5_cd" name="Canonical RC5 CD-Player" vendor="" model="" type="cd">
    <commandset type="ir" protocol="rc5" deviceno="20" toggle="yes" remotename="rc5_cd">
      <command cmdref="cmd_0" 				cmdno="0"/>
      <command cmdref="cmd_1" 				cmdno="1"/>
      <command cmdref="cmd_2" 				cmdno="2"/>
      <command cmdref="cmd_3" 				cmdno="3"/>
      <command cmdref="cmd_4" 				cmdno="4"/>
      <command cmdref="cmd_5" 				cmdno="5"/>
      <command cmdref="cmd_6" 				cmdno="6"/>
      <command cmdref="cmd_7" 				cmdno="7"/>
      <command cmdref="cmd_8" 				cmdno="8"/>
      <command cmdref="cmd_9" 				cmdno="9"/>
      <command cmdref="cmd_power_toggle" 		cmdno="12"/>
      <command cmdref="cmd_in_cd"			cmdno="63"/>
      <command cmdref="cmd_previous" 			cmdno="33"/>
      <command cmdref="cmd_next" 			cmdno="32"/>
      <command cmdref="cmd_play" 			cmdno="53"/>
      <command cmdref="cmd_rewind" 			cmdno="50"/>
      <command cmdref="cmd_fast_forward" 		cmdno="52"/>
      <command cmdref="cmd_stop" 			cmdno="54"/>
      <command cmdref="cmd_pause_toggle" 		cmdno="48"/>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/snapshot-0.5.2/devices/denon_asd_3n.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<!-- Status: tested(??) -->
<device id="denon_asd_3n" name="Denon iPod dock" vendor="Denon" model="asd_3n" type="misc_audio">
  <commandset type="ir" protocol="denon_k" deviceno="2" subdevice="3" remotename="denon_asd_3n" original_remote="Denon RC-1088">
    <command cmdref="browse_remote" name="browse/remote"	cmdno="45"/>
    <command cmdref="power_toggle"	name="power"		cmdno="71"/>
    <command cmdref="previous"				cmdno="5"/>
    <command cmdref="play_pause"	name="play/pause"	cmdno="1"/>
    <command cmdref="next"					cmdno="4"/>
    <command cmdref="title"		name="top"		cmdno="23"/>
    <command cmdref="favorites" name="favorites/all music"	cmdno="72"/>
    <command cmdref="right"					cmdno="28"/>
    <command cmdref="left"					cmdno="27"/>
    <command cmdref="up"					cmdno="25"/>
    <command cmdref="down"					cmdno="26"/>
    <command cmdref="ok"					cmdno="24"/>
    <command cmdref="radio_mode"	name="internet radio"	cmdno="75"/>
    <command cmdref="ipod_mode"	name="iPod"		cmdno="76"/>
    <command cmdref="shuffle"	name="random"		cmdno="16"/>
    <command cmdref="repeat"				cmdno="17"/>
    <command cmdref="memory"				cmdno="80"/>
    <command cmdref="mute_toggle"	name="mute"		cmdno="77"/>
    <command cmdref="volume_up"				cmdno="2"/>
    <command cmdref="volume_down"				cmdno="3"/>
    <command cmdref="page_down"				cmdno="73"/>
    <command cmdref="page_up"				cmdno="74"/>

    <command cmdref="stop"					cmdno="8"/>
<!--
    <command cmdref="search_plus"				cmdno="21"/>
    <command cmdref="search_plus"				cmdno="22"/>
    <command cmdref="search_plus"				cmdno="31"/>
    <command cmdref="page_search"				cmdno="34"/>
-->
    <command cmdref="cmd_return"				cmdno="35"/>
    <command cmdref="browse_mode"				cmdno="46"/>
    <command cmdref="remote_mode"				cmdno="47"/>
    <command cmdref="shuffle_songs"				cmdno="64"/>
    <command cmdref="shuffle_albums"			cmdno="65"/>
    <command cmdref="shuffle_off"				cmdno="66"/>
    <command cmdref="repeat_one"				cmdno="67"/>
    <command cmdref="repeat_all"				cmdno="68"/>
    <command cmdref="repeat_off"				cmdno="69"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/trunk/devices/mce_vrc-1100.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<!-- experimental -->
<device id="mce_vrc-1100" name="MCE" vendor="Microsoft" model="" type="other">
  <commandset type="ir" protocol="OrtekMCE" deviceno="21">
    <command cmdref="browse_mode"	cmdno="5"/>
    <command cmdref="power_toggle"	cmdno="3"/>
    <command cmdref="yellow"		cmdno="6"/>
    <command cmdref="blue"		cmdno="7"/>
    <command cmdref="green"		cmdno="4"/>
    <command cmdref="red"		cmdno="2"/>
    <command cmdref="tv_mode"		cmdno="14"/>
    <command cmdref="picture_mode"	cmdno="15"/>
    <command cmdref="movie_mode"	cmdno="12"/>
    <command cmdref="music_mode"	cmdno="10"/>
    <command cmdref="rewind"		cmdno="13"/>
    <command cmdref="play"		cmdno="11"/>
    <command cmdref="fast_forward"	cmdno="9"/>
    <command cmdref="previous"		cmdno="8"/>
    <command cmdref="next"		cmdno="17"/>
    <command cmdref="stop"		cmdno="16"/>
    <command cmdref="pause_toggle"	cmdno="20"/>
    <command cmdref="record_toggle"	cmdno="19"/>
    <command cmdref="cmd_return"	cmdno="22"/>
    <command cmdref="info"		cmdno="18"/>
    <command cmdref="up"		cmdno="21"/>
    <command cmdref="left"		cmdno="23"/>
    <command cmdref="ok"		cmdno="34"/>
    <command cmdref="right"		cmdno="33"/>
    <command cmdref="down"		cmdno="32"/>
    <command cmdref="volume_up"		cmdno="50"/>
    <command cmdref="mute_toggle"	cmdno="48"/>
    <command cmdref="channel_up"	cmdno="47"/>
    <command cmdref="volume_down"	cmdno="51"/>
    <command cmdref="start"		cmdno="46"/>
    <command cmdref="channel_down"	cmdno="49"/>
    <command cmdref="cmd_1"		cmdno="52"/>
    <command cmdref="cmd_2"		cmdno="36"/>
    <command cmdref="cmd_3"		cmdno="31"/>
    <command cmdref="cmd_4"		cmdno="53"/>
    <command cmdref="cmd_5"		cmdno="35"/>
    <command cmdref="cmd_6"		cmdno="30"/>
    <command cmdref="cmd_7"		cmdno="45"/>
    <command cmdref="cmd_8"		cmdno="37"/>
    <command cmdref="cmd_9"		cmdno="38"/>
    <command cmdref="star"		cmdno="43"/>
    <command cmdref="cmd_0"		cmdno="42"/>
    <command cmdref="hash"		cmdno="40"/>
    <command cmdref="close"		cmdno="44"/>
    <command cmdref="clear"		cmdno="41"/>
    <command cmdref="select"		cmdno="39"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/last_as_harc/devices/avcontrol5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
"../dtds/devices.dtd">
<device id="avcontrol5" name="AVControl 5" vendor="Vicanco" model="avc5" type="misc_audio">
  <commandset type="ir" protocol="recs80" toggle="yes" deviceno="5" remotename="avcontrol5">
    <command cmdref="in_tv"		cmdno="13"/>
    <command cmdref="in_vcr"		cmdno="1"/>
    <command cmdref="in_dvd"		cmdno="3"/>
    <command cmdref="in_sat"		cmdno="7"/>
    <command cmdref="in_dvb_t"		cmdno="2"/>
    <command cmdref="in_aux"		cmdno="9"/>
    <command cmdref="lock_input"	cmdno="10"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/philips_37pfl9603.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="philips_37pfl9603" name="Philips TV 37PFL9603" vendor="Philips" model="37PFL9603" type="tv" pingable_on="yes" pingable_standby="no">
  <jp1data>
    <setupcode value="1234"/>
  </jp1data>
  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="0"
    remotename="philips_37pfl9603">
    <command cmdref="cmd_0" 				cmdno="0"/>
    <command cmdref="cmd_1" 				cmdno="1"/>
    <command cmdref="cmd_2" 				cmdno="2"/>
    <command cmdref="cmd_3" 				cmdno="3"/>
    <command cmdref="cmd_4" 				cmdno="4"/>
    <command cmdref="cmd_5" 				cmdno="5"/>
    <command cmdref="cmd_6" 				cmdno="6"/>
    <command cmdref="cmd_7" 				cmdno="7"/>
    <command cmdref="cmd_8" 				cmdno="8"/>
    <command cmdref="cmd_9" 				cmdno="9"/>
    <command cmdref="cmd_power_toggle" name="power"	cmdno="12"/>
    <!--command cmdref="cmd_tv_mode"			cmdno="63"/-->
    <command cmdref="cmd_channel_up" 			cmdno="32"/>
    <command cmdref="cmd_channel_down" 			cmdno="33"/>
    <command cmdref="cmd_mute_toggle" name="mute"	cmdno="13"/>
    <command cmdref="cmd_last_channel" 			cmdno="34"/>
    <command cmdref="cmd_volume_up" 			cmdno="16"/>
    <command cmdref="cmd_volume_down" 			cmdno="17"/>
    <command cmdref="cmd_PP" 				cmdno="14"/>
    <command cmdref="cmd_info" 				cmdno="15"/>
    <command cmdref="cmd_brightness_down" 		cmdno="19"/>
    <command cmdref="cmd_brightness_up" 		cmdno="18"/>
    <command cmdref="cmd_aspectratio"	 		cmdno="126"/>
    <command cmdref="cmd_menu" 				cmdno="82"/>
    <command cmdref="cmd_up" 				cmdno="80"/>
    <command cmdref="cmd_down" 				cmdno="81"/>
    <command cmdref="cmd_red" 				cmdno="107"/>
    <command cmdref="cmd_green" 			cmdno="108"/>
    <command cmdref="cmd_yellow" 			cmdno="109"/>
    <command cmdref="cmd_blue" 				cmdno="110"/>
    <command cmdref="cmd_white" 			cmdno="111"/>
    <command cmdref="cmd_menu_off" 			cmdno="83"/>
    <command cmdref="cmd_I_II" 				cmdno="35"/>
    <command cmdref="cmd_teletext" 			cmdno="60"/>
    <command cmdref="cmd_teletext_freeze" 		cmdno="41"/>
    <command cmdref="cmd_teletext_reveal" 		cmdno="44"/>
    <command cmdref="cmd_teletext_hide" 		cmdno="45"/>
    <command cmdref="cmd_teletext_translucent" 		cmdno="46"/>
    <command cmdref="cmd_teletext_doubleheight" 	cmdno="43"/>
    <command cmdref="cmd_teletext_time" 		cmdno="42"/>
    <command cmdref="cmd_PIP" 				cmdno="88"/>
    <command cmdref="cmd_PIP_source" 			cmdno="95"/>
    <command cmdref="cmd_PIP_exchange" 			cmdno="90"/>
    <command cmdref="cmd_PIP_freeze" 			cmdno="101"/>
    <command cmdref="cmd_PIP_position" 			cmdno="89"/>
    <command cmdref="cmd_PIP_ch_down" 			cmdno="103"/>
    <command cmdref="cmd_PIP_ch_up" 			cmdno="102"/>
    <!--command cmdref="cmd_freeze_toggle"			cmdno="93"/-->
    <!--command cmdref="cmd_DNR" 				cmdno="97"/-->
    <!--command cmdref="cmd_special" 			cmdno="94"/-->

    <command cmdref="cmd_in_ext2" 			cmdno="57"/>
    <command cmdref="cmd_power_on" 			cmdno="63"/>
    <command cmdref="cmd_power_off" 			cmdno="61"/>

    <command cmdref="cmd_input"				cmdno="56"/>
  </commandset>

  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="12"
    remotename="philips_37pfl9603" pseudo_power_on="cmd_in_aux">
    <command cmdref="cmd_in_aux"		 	cmdno="63"/>
  </commandset>
  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="5" remotename="philips_37pfl9603">
    <command cmdref="cmd_in_vcr"			cmdno="63"/>
  </commandset>

  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="3" remotename="philips_37pfl9603">
<!--
Notes=Dummy device to support RC-5 commands on Philips TV discrete input selection for remotes w/o 2 byte code support (e.g. URC-6131).\n\nFunctions for this device\:\nav1\nav3\nhdmi1\nhdmi3\nside\nambilight discrete on\nambilight discrete off\nformat auto
-->

    <command cmdref="cmd_in_ext1"			cmdno="4"/>
    <command cmdref="cmd_in_ext3"			cmdno="56"/>
    <command cmdref="cmd_in_hdmi1"			cmdno="57"/>
    <command cmdref="cmd_in_hdmi2"			cmdno="123"/>
    <command cmdref="cmd_in_hdmi3"			cmdno="6"/>
    <!--command cmdref="cmd_tv_mode"			cmdno="72"/-->
    <command cmdref="cmd_in_side"			cmdno="58"/>
    <command cmdref="cmd_light_on"			cmdno="40"/>
    <command cmdref="cmd_light_off"			cmdno="41"/>
    <!--command cmdref="cmd_aspectratio_automatic"		cmdno="61"/-->
  </commandset>

  <commandset type="ip" wol="no">
    <command cmdref="ping"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/trunk/devices/sony_mdp650.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="sony_mdp_650" name="Sony MDP-650" vendor="Sony" model="MDP-650" type="ld">
  <commandset type="ir" protocol="sony12" deviceno="6" remotename="sony_mdp_650" original_remote="rmt-m14">
    <command cmdref="open_close"			cmdno="0x16"/>
    <command cmdref="disc_tv"				cmdno="0x2a"/>
    <command cmdref="power_toggle"			cmdno="0x15"/>
    <command cmdref="clear"				cmdno="0x0f"/>
    <command cmdref="frame_time"			cmdno="0x0c"/>
    <command cmdref="program"				cmdno="0x30"/>
    <command cmdref="repeat"				cmdno="0x29"/>
    <command cmdref="info"				cmdno="0x3a"/>
    <command cmdref="cmd_1"				cmdno="0x00"/>
    <command cmdref="cmd_2"				cmdno="0x01"/>
    <command cmdref="cmd_3"				cmdno="0x02"/>
    <command cmdref="cmd_1_all"				cmdno="0x47"/>
    <command cmdref="av_time"				cmdno="0x28"/>
    <command cmdref="cmd_4"				cmdno="0x03"/>
    <command cmdref="cmd_5"				cmdno="0x04"/>
    <command cmdref="cmd_6"				cmdno="0x05"/>
    <command cmdref="shuffle"				cmdno="0x41"/>
    <command cmdref="a_b"				cmdno="0x38"/>
    <command cmdref="cmd_7"				cmdno="0x06"/>
    <command cmdref="cmd_8"				cmdno="0x07"/>
    <command cmdref="cmd_9"				cmdno="0x08"/>
    <command cmdref="auto_pgm"				cmdno="0x45"/>
    <command cmdref="file"				cmdno="0x48"/>
    <command cmdref="two_digit"				cmdno="0x39"/>
    <command cmdref="cmd_0"				cmdno="0x09"/>
    <command cmdref="search_next"			cmdno="0x0b"/>
    <!--command cmdref="cmd_back"			cmdno="0x44"/-->
    <command cmdref="cmd_return"			cmdno="0x44"/>
    <command cmdref="custom_index"			cmdno="0x49"/>
    <command cmdref="analog_sound"			cmdno="0x40"/>
    <command cmdref="audio_monitor"			cmdno="0x17"/>
    <command cmdref="cx"				cmdno="0x32"/>
    <command cmdref="speed_down"			cmdno="0x24"/>
    <command cmdref="speed_up"				cmdno="0x23"/>
    <command cmdref="auto_pause"			cmdno="0x46"/>
    <command cmdref="speed_set_down"			cmdno="0x22"/>
    <command cmdref="speed_set_up"			cmdno="0x21"/>
    <command cmdref="intro"				cmdno="0x68"/>
    <command cmdref="step_back"				cmdno="0x2c"/>
    <command cmdref="step_forward"			cmdno="0x2b"/>
    <command cmdref="memory_play"			cmdno="0x25"/>
    <command cmdref="previous"				cmdno="0x35"/>
    <command cmdref="next"				cmdno="0x34"/>
    <command cmdref="stop"				cmdno="0x18"/>
    <command cmdref="play"				cmdno="0x1a"/>
    <command cmdref="pause_toggle"			cmdno="0x19"/>
    <command cmdref="ff"				cmdno="0x1f"/>
    <command cmdref="rewind"				cmdno="0x1f"/>
    <command cmdref="fff"				cmdno="0x1c"/>
    <command cmdref="rrr"				cmdno="0x1b"/>
    <command cmdref="power_on"				cmdno="0x2e"/>
    <command cmdref="power_off"				cmdno="0x2f"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/rc5_tv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="rc5_tv" name="Canonical RC5 TV" vendor="" model="" type="tv">
    <commandset type="ir" protocol="rc5" deviceno="0" remotename="rc5_tv" toggle="yes">
      <command cmdref="cmd_0" 				cmdno="0"/>
      <command cmdref="cmd_1" 				cmdno="1"/>
      <command cmdref="cmd_2" 				cmdno="2"/>
      <command cmdref="cmd_3" 				cmdno="3"/>
      <command cmdref="cmd_4" 				cmdno="4"/>
      <command cmdref="cmd_5" 				cmdno="5"/>
      <command cmdref="cmd_6" 				cmdno="6"/>
      <command cmdref="cmd_7" 				cmdno="7"/>
      <command cmdref="cmd_8" 				cmdno="8"/>
      <command cmdref="cmd_9" 				cmdno="9"/>
      <command cmdref="cmd_power_toggle" 		cmdno="12"/>
      <command cmdref="cmd_in_tv"			cmdno="63"/>
      <command cmdref="cmd_channel_up" 			cmdno="32"/>
      <command cmdref="cmd_channel_down" 		cmdno="33"/>
      <command cmdref="cmd_mute_toggle" 		cmdno="13"/>
      <command cmdref="cmd_last_channel" 		cmdno="34"/>
      <command cmdref="cmd_volume_up" 			cmdno="16"/>
      <command cmdref="cmd_volume_down" 		cmdno="17"/>
      <command cmdref="cmd_PP" 				cmdno="14"/>
      <command cmdref="cmd_info" 			cmdno="15"/>
      <command cmdref="cmd_brightness_down" 		cmdno="19"/>
      <command cmdref="cmd_brightness_up" 		cmdno="18"/>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/cyberhome-ch_dvd_402.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<device id="cyberhome-ch_dvd_402" name="Cyberhome DVD 402" vendor="Cyberhome" model="402" type="dvd">
  <commandset type="ir" protocol="nec1" toggle="no" deviceno="114" subdevice="205" remotename="cyberhome_dvd_402">
    <command cmdref="cmd_power_toggle" 	cmdno="14"/>
    <command cmdref="cmd_open_close" 	cmdno="26"/>
    <command cmdref="cmd_title" 	cmdno="64"/>
    <command cmdref="cmd_menu" 		cmdno="2"/>
    <command cmdref="cmd_setup" 	cmdno="65"/>
    <command cmdref="cmd_display" 	cmdno="80"/>
    <command cmdref="cmd_audio" 	cmdno="22"/>
    <command cmdref="cmd_angle" 	cmdno="84"/>
    <command cmdref="cmd_mute_toggle" 	cmdno="7"/>
    <command cmdref="cmd_goto"	 	cmdno="18"/>
    <command cmdref="cmd_subtitle" 	cmdno="88"/>

    <command cmdref="cmd_up" 		cmdno="68"/>
    <command cmdref="cmd_down" 		cmdno="29"/>
    <command cmdref="cmd_left" 		cmdno="28"/>
    <command cmdref="cmd_right" 	cmdno="72"/>
    <command cmdref="cmd_ok" 		cmdno="92"/>

    <command cmdref="cmd_rewind" 	cmdno="31"/>
    <command cmdref="cmd_fast_forward" 	cmdno="93"/>
    <command cmdref="cmd_play" 		cmdno="6"/>
    <command cmdref="cmd_previous" 	cmdno="24"/>
    <command cmdref="cmd_next" 		cmdno="25"/>
    <command cmdref="cmd_pause_toggle"	cmdno="89"/>
    <command cmdref="cmd_still_advance" cmdno="27"/>
    <command cmdref="cmd_stop" 		cmdno="30"/>

    <command cmdref="cmd_0" 		cmdno="73"/>
    <command cmdref="cmd_1" 		cmdno="19"/>
    <command cmdref="cmd_2" 		cmdno="16"/>
    <command cmdref="cmd_3" 		cmdno="17"/>
    <command cmdref="cmd_4" 		cmdno="15"/>
    <command cmdref="cmd_5" 		cmdno="12"/>
    <command cmdref="cmd_6" 		cmdno="13"/>
    <command cmdref="cmd_7" 		cmdno="11"/>
    <command cmdref="cmd_8" 		cmdno="8"/>
    <command cmdref="cmd_9" 		cmdno="9"/>
    <command cmdref="cmd_plus10"	cmdno="77"/>
    <command cmdref="cmd_clear" 	cmdno="81"/>

    <command cmdref="cmd_program"	cmdno="21"/>
    <command cmdref="cmd_repeat" 	cmdno="3"/>
    <command cmdref="cmd_a_b" 		cmdno="4"/>
    <command cmdref="cmd_intro"		cmdno="69"/>
    <command cmdref="cmd_zoom" 		cmdno="23"/>
    <command cmdref="cmd_effect_toggle"	cmdno="5"/>
    <command cmdref="cmd_marker" 	cmdno="85"/>
    <command cmdref="cmd_return" 	cmdno="10"/>
  </commandset>
</device>
