=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/dtds/devices.dtd
<!-- Presently, id's for devices are not supported -->

<!ELEMENT devices (device)+ >

<!ELEMENT device (attributes?,aliases?,jp1data?,commandset+) >
<!ATTLIST device
        id ID #REQUIRED
        name CDATA #REQUIRED
        vendor CDATA #IMPLIED
        vendorurl CDATA #IMPLIED
        model CDATA #REQUIRED
        pingable_on (yes|no) #IMPLIED
        pingable_standby (yes|no) #IMPLIED
        type     (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|dumb|undefined) "undefined"
        alt_type (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|dumb|undefined) "undefined" >

<!ELEMENT attributes (attribute|has-attribute)+ >

<!ELEMENT attribute EMPTY >
<!ATTLIST attribute
	name NMTOKEN #REQUIRED
	value CDATA #IMPLIED >

<!ELEMENT has-attribute EMPTY >
<!ATTLIST has-attribute
	name NMTOKEN #REQUIRED
	value (yes|no) "yes" >

<!ELEMENT aliases (alias+) >

<!ELEMENT alias EMPTY >
<!ATTLIST alias
	name NMTOKEN #REQUIRED
        command NMTOKEN #REQUIRED >

<!ELEMENT jp1data (setupcode|fixed_data)+ >

<!ELEMENT setupcode EMPTY >
<!ATTLIST setupcode
	value CDATA #REQUIRED >

<!ELEMENT fixed_data EMPTY >
<!ATTLIST fixed_data
	data CDATA #REQUIRED >

<!ELEMENT commandset (commandgroup|commandgroupref|command)+ >
<!ATTLIST commandset
        type (ir|rf433|rf868|www|web_api|tcp|udp|serial|bluetooth|on_off|ip) "ir"
        ifattribute CDATA #IMPLIED
        protocol NMTOKEN #IMPLIED
        prefix CDATA ""
        suffix CDATA ""
        portnumber CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        subdevice CDATA #IMPLIED
        fixed_data CDATA #IMPLIED
        toggle (yes|no) "no"
        wol (yes|no) "no"
        name CDATA #IMPLIED
        original_remote CDATA #IMPLIED
        remotename NMTOKEN #IMPLIED
        delay_between_chars CDATA "0"
 	pseudo_power_on NMTOKEN #IMPLIED
 	delay_between_reps CDATA "0"
 	remark CDATA #IMPLIED >

<!ELEMENT commandgroup (commandgroup|command)+ >
<!ATTLIST commandgroup
        id ID #IMPLIED
        name CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        description CDATA #IMPLIED >

<!ELEMENT commandgroupref EMPTY >
<!ATTLIST commandgroupref
        commandgroup IDREF #REQUIRED >

<!-- For now, there are no more than one argument accepted -->
<!ELEMENT command ((toggle_pair|ccf)?,remark?,argument*,returnvalues?) >
<!ATTLIST command
        cmdref NMTOKEN #REQUIRED
        cmdno CDATA #IMPLIED
        name CDATA #IMPLIED
	zone (1|2|3|record) #IMPLIED
        type (discrete|toggle|cyclic) #IMPLIED
	remark CDATA #IMPLIED
        ifattribute NMTOKEN #IMPLIED
        wakeup (yes|no) #IMPLIED
        transmit CDATA #IMPLIED
        expected_response CDATA #IMPLIED
        response_ending CDATA #IMPLIED
        returntype CDATA #IMPLIED
        returnwidth CDATA #IMPLIED
        returncontent CDATA #IMPLIED
        response_lines CDATA #IMPLIED >

<!ELEMENT returnvalues (syntax?,semantics?,description?) >

<!ELEMENT syntax (returntype*) >
<!ATTLIST syntax
	parse CDATA #IMPLIED >

<!ELEMENT semantics (table) >
<!ELEMENT returntype EMPTY >
<!ATTLIST returntype
	type (string|texttable|decimal_integer|hexadecimal_integer|hh:mm:ss|dd.mm.yyyy|tv_radio|0_1|on_off|percent|4:3_16:9|dbox_videoformat|dbox_videooutput) #REQUIRED
	length CDATA #IMPLIED >

<!ELEMENT table (entry+,default?) >
<!ATTLIST table
	index (string|number|hexnumber) "string" >

<!ELEMENT entry EMPTY >
<!ATTLIST entry
	value CDATA #REQUIRED
	desc CDATA "" >

<!ELEMENT default EMPTY >
<!ATTLIST default
	desc CDATA "" >

<!ELEMENT remark (#PCDATA) >

<!ELEMENT argument (description)? >
<!ATTLIST argument
        name CDATA #REQUIRED
        semantic CDATA #IMPLIED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT ccf (#PCDATA) >
<!ATTLIST ccf
	toggle (0|1) #IMPLIED >

<!ELEMENT toggle_pair (ccf, ccf) >

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/sanyo_plv_z2000.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="sanyo_plv_z2000" name="Sanyo PLV-Z2000" vendor="Sanyo" model="PLV-Z2000" type="projector">
    <jp1data>
      <setupcode value="0735"/>
    </jp1data>
    <commandset type="ir" protocol="nec1" deviceno="51" subdevice="0" remotename="sanyo_plv_z2000">
      <!-- Interesting reference:-->
      <!-- http://www.remotecentral.com/cgi-bin/mboard/rc-discrete/thread.cgi?3694 -->

      <command cmdref="cmd_power_toggle"		cmdno="0"/>
      <command cmdref="cmd_logo" 			cmdno="60"/>
      <command cmdref="cmd_color_temp" 			cmdno="21"/>
      <command cmdref="cmd_sharpness" 			cmdno="20"/>
      <command cmdref="cmd_img_preset_up"		cmdno="14"/>
      <command cmdref="cmd_in_hdmi2" 			cmdno="19"/>
      <command cmdref="cmd_in_s_video" 			cmdno="62"/>
      <command cmdref="cmd_lamp_mode" 			cmdno="24"/>
      <command cmdref="cmd_video_mute_toggle"		cmdno="139"/>
      <command cmdref="cmd_freeze_toggle"		cmdno="67"/>
      <command cmdref="cmd_menu" 			cmdno="28"/>
      <command cmdref="cmd_reset" 			cmdno="25"/>
      <command cmdref="cmd_up" 				cmdno="140"/>
      <command cmdref="cmd_down" 			cmdno="141"/>
      <command cmdref="cmd_right" 			cmdno="29"/>
      <command cmdref="cmd_left" 			cmdno="30"/>
      <command cmdref="cmd_ok" 				cmdno="15"/>
      <command cmdref="cmd_aspectratio"	 		cmdno="130"/>
      <command cmdref="cmd_image" 			cmdno="12"/>
      <command cmdref="cmd_img_user_up"			cmdno="13"/>
      <command cmdref="cmd_in_hdmi1" 			cmdno="55"/>
      <command cmdref="cmd_in_vga" name="Computer"	cmdno="56"/>
      <command cmdref="cmd_in_component2" 		cmdno="129"/>
      <command cmdref="cmd_in_component1" 		cmdno="131"/>
      <command cmdref="cmd_contrast" 			cmdno="49"/>
      <command cmdref="cmd_color" 			cmdno="50"/>
      <command cmdref="cmd_brightness" 			cmdno="48"/>
      <command cmdref="cmd_in_video" 			cmdno="61"/>
      <command cmdref="cmd_info" 			cmdno="22"/>
      <command cmdref="cmd_return" 			cmdno="18"/>

      <command cmdref="cmd_power_on" 			cmdno="0xa0"/>
      <command cmdref="cmd_power_off" 			cmdno="0xa1"/>
      <command cmdref="cmd_power_off_confirm"		cmdno="0xa2"/>
    </commandset>
    <commandset type="serial" protocol="rs232_9600_8n1" prefix="C" suffix="\r">
      <command cmdref="cmd_power_on" 			transmit="00"/>
      <command cmdref="cmd_power_off" 			transmit="01"/>
      <command cmdref="cmd_power_off_confirm" 		transmit="02"/>
      <command cmdref="cmd_power_mgmt_on"		transmit="2A"/>
      <command cmdref="cmd_power_mgmt_off"		transmit="2B"/>

      <command cmdref="cmd_video_mute_on" 		transmit="0D"/>
      <command cmdref="cmd_video_mute_off" 		transmit="0E"/>
      <command cmdref="cmd_freeze_on"			transmit="43"/>
      <command cmdref="cmd_freeze_off"			transmit="44"/>
      <command cmdref="cmd_osd_off" name="cmd_display_clear" transmit="1E"/>

      <command cmdref="cmd_aspectratio_4_3"		transmit="0F"/>
      <command cmdref="cmd_aspectratio_16_9" 		transmit="10"/>
      <command cmdref="cmd_aspectratio_zoom"		transmit="2C"/>
      <command cmdref="cmd_aspectratio_nat_wide1"	transmit="2D"/>
      <command cmdref="cmd_aspectratio_nat_wide2"	transmit="2E"/>
      <command cmdref="cmd_aspectratio_caption_in"	transmit="63"/>
      <command cmdref="cmd_aspectratio_full_through"	transmit="65"/>
      <command cmdref="cmd_aspectratio_normal_through"	transmit="66"/>

      <command cmdref="cmd_img_living" 			transmit="11"/>
      <command cmdref="cmd_img_creative_cinema" 	transmit="12"/>
      <command cmdref="cmd_img_pure_cinema"	 	transmit="13"/>
      <command cmdref="cmd_img_vivid"		 	transmit="18"/>
      <command cmdref="cmd_img_brilliant_cinema" 	transmit="19"/>
      <command cmdref="cmd_img_dynamic"		 	transmit="1A"/>
      <command cmdref="cmd_img_natural"		 	transmit="1B"/>
      <command cmdref="cmd_img1"		 	transmit="14"/>
      <command cmdref="cmd_img2"		 	transmit="15"/>
      <command cmdref="cmd_img3"		 	transmit="16"/>
      <command cmdref="cmd_img4"		 	transmit="17"/>
      <command cmdref="cmd_img5"			transmit="36"/>
      <command cmdref="cmd_img6"			transmit="37"/>
      <command cmdref="cmd_img7"			transmit="38"/>
      <command cmdref="cmd_img_logo_off"		transmit="7A"/>
      <command cmdref="cmd_img_logo_default"		transmit="7B"/>
      <command cmdref="cmd_img_logo_user"		transmit="7C"/>
      <command cmdref="cmd_img_logo_capture"		transmit="7D"/>
      <command cmdref="cmd_img_my_pic_on"		transmit="7E"/>
      <command cmdref="cmd_img_my_pic_off"		transmit="7F"/>
      <command cmdref="cmd_auto_pc_adj"			transmit="89"/>

      <command cmdref="cmd_menu_on"		 	transmit="1C"/>
      <command cmdref="cmd_menu_off"		 	transmit="1D"/>
      <command cmdref="cmd_right"			transmit="3A"/>
      <command cmdref="cmd_left"			transmit="3B"/>
      <command cmdref="cmd_up"				transmit="3C"/>
      <command cmdref="cmd_down"			transmit="3D"/>
      <command cmdref="cmd_ok"				transmit="3F"/>
      <command cmdref="cmd_reset"			transmit="40"/>
      <command cmdref="cmd_return"			transmit="3D"/>

      <command cmdref="cmd_in_video"			transmit="23"/>
      <command cmdref="cmd_in_s_video"			transmit="24"/>
      <command cmdref="cmd_in_component1"		transmit="25"/>
      <command cmdref="cmd_in_component2"		transmit="26"/>
      <command cmdref="cmd_in_vga"			transmit="50"/>
      <command cmdref="cmd_in_scart" remark="through VGA" transmit="50"/>
      <command cmdref="cmd_in_hdmi1"			transmit="53"/>
      <command cmdref="cmd_in_hdmi2"			transmit="54"/>
      <command cmdref="cmd_d5_control_on"		transmit="67"/>
      <command cmdref="cmd_d5_control_off"		transmit="68"/>

      <command cmdref="cmd_factory_reset" name="cmd_factory_default" transmit="4C"/>

      <command cmdref="cmd_lamp_auto1"			transmit="72"/>
      <command cmdref="cmd_lamp_auto2"			transmit="73"/>
      <command cmdref="cmd_lamp_normal"			transmit="74"/>
      <command cmdref="cmd_lamp_eco"			transmit="75"/>

      <command cmdref="cmd_setup_cealing_on"		transmit="76"/>
      <command cmdref="cmd_setup_cealing_off"		transmit="77"/>
      <command cmdref="cmd_setup_rear_on"		transmit="78"/>
      <command cmdref="cmd_setup_rear_off"		transmit="79"/>

      <command cmdref="get_status" transmit="R0" response_lines="1">
	<returnvalues>
	  <syntax parse="%2x\r">
	    <returntype type="hexadecimal_integer" length="2"/>
	  </syntax>
	  <semantics>
	    <table index="string">
	      <entry value="00" desc="Power On"/>
	      <entry value="80" desc="Standby"/>
	      <entry value="40" desc="Processing Countdown"/>
	      <entry value="20" desc="Processing Cooling down"/>
	      <entry value="10" desc="Power Failure"/>
	      <entry value="28" desc="Processing cooling down due to abnormal temperature"/>
	      <entry value="88" desc="Standby after cooling down due to abnormal temperature"/>
	      <entry value="24" desc="Processing power save/Cooling down"/>
	      <entry value="04" desc="Power save"/>
	      <entry value="21" desc="Processing cooling down after OFF due to lamp failure"/>
	      <entry value="81" desc="Standby after cooling down due to lamp failure"/>
	      <default desc="Unknown"/>
	    </table>
	  </semantics>
	</returnvalues>
      </command>
      <command cmdref="get_input" transmit="R1" response_lines="1">
	<returnvalues>
	  <syntax>
	    <returntype type="decimal_integer" length="1"/>
	  </syntax>
	  <semantics>
	    <table>
	      <entry value="0" desc="Video"/>
	      <entry value="1" desc="S-Video"/>
	      <entry value="2" desc="Component1"/>
	      <entry value="3" desc="Component2"/>
	      <entry value="4" desc="HDMI1"/>
	      <entry value="5" desc="HDMI2"/>
	      <entry value="6" desc="VGA"/>
	      <entry value="7" desc="Computer(SCART)"/>
	    </table>
	  </semantics>
	</returnvalues>
      </command>
      <command cmdref="get_lamp_hours" transmit="R3" response_lines="1">
	<returnvalues>
	  <syntax>
	    <returntype type="decimal_integer" length="5"/>
	  </syntax>
	</returnvalues>
      </command>
      <command cmdref="get_settings" transmit="R4" response_lines="1">
	<returnvalues>
	  <syntax>
	    <returntype type="decimal_integer" length="2"/>
	  </syntax>
	  <semantics>
	    <table>
	      <entry value="11" desc="Normal"/>
	      <entry value="10" desc="Ceiling, rear on"/>
	      <entry value="01" desc="Rear on"/>
	      <entry value="11" desc="Ceiling on"/>
	    </table>
	  </semantics>
	</returnvalues>
      </command>
      <command cmdref="get_temperatures" transmit="R6" response_lines="1">
	<returnvalues>
	  <syntax>
	    <returntype type="decimal_integer"/>
	    <returntype type="decimal_integer"/>
	    <returntype type="decimal_integer"/>
	  </syntax>
	</returnvalues>
      </command>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/last_as_harc/devices/rc5_tape.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="rc5_tape" name="Canonical RC5 TAPE-Player" vendor="" model="" type="tape">
  <jp1data>
    <setupcode value="1557"/>
  </jp1data>
    <commandset type="ir" protocol="rc5" deviceno="18" toggle="yes" remotename="rc5_tape">
      <command cmdref="cmd_0" 				cmdno="0"/>
      <command cmdref="cmd_1" 				cmdno="1"/>
      <command cmdref="cmd_2" 				cmdno="2"/>
      <command cmdref="cmd_3" 				cmdno="3"/>
      <command cmdref="cmd_4" 				cmdno="4"/>
      <command cmdref="cmd_5" 				cmdno="5"/>
      <command cmdref="cmd_6" 				cmdno="6"/>
      <command cmdref="cmd_7" 				cmdno="7"/>
      <command cmdref="cmd_8" 				cmdno="8"/>
      <command cmdref="cmd_9" 				cmdno="9"/>
      <command cmdref="power_toggle" 		cmdno="12"/>
      <command cmdref="in_tape"			cmdno="63"/>
      <command cmdref="previous" 			cmdno="33"/>
      <command cmdref="next" 			cmdno="32"/>
      <command cmdref="play" 			cmdno="53"/>
      <command cmdref="rewind" 			cmdno="50"/>
      <command cmdref="fast_forward" 		cmdno="52"/>
      <command cmdref="stop" 			cmdno="54"/>
      <command cmdref="pause_toggle" 		cmdno="48"/>
      <command cmdref="record_on" 			cmdno="55"/>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/2011-06-05/devices/humax-s-hd3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<device id="humax-prhd1000c" name="Humax PR-HD1000C" vendor="Humax" model="prhd1000c" type="cable">
  <delays>
    <delay type="intra_command" delay="200"/>
  </delays>
  <jp1data>
    <setupcode value="1916"/>
  </jp1data>
  <commandset type="ir" protocol="mcd" toggle="yes" deviceno="38" subdevice="72"
    pseudo_power_on="cmd_0">
    <command cmdref="cmd_0"		 cmdno="0"/>
    <command cmdref="cmd_1"		 cmdno="1"/>
    <command cmdref="cmd_2"		 cmdno="2"/>
    <command cmdref="cmd_3"		 cmdno="3"/>
    <command cmdref="cmd_4"		 cmdno="4"/>
    <command cmdref="cmd_5"		 cmdno="5"/>
    <command cmdref="cmd_6"		 cmdno="6"/>
    <command cmdref="cmd_7"		 cmdno="7"/>
    <command cmdref="cmd_8"		 cmdno="8"/>
    <command cmdref="cmd_9"		 cmdno="9"/>
    <command cmdref="tv_mode"		 cmdno="166"/>
    <command cmdref="key_esc" name="sky" cmdno="131"/>
    <command cmdref="power_toggle"	 cmdno="12"/>
    <command cmdref="search"		 cmdno="64"/>
    <command cmdref="key_backspace"	 cmdno="58"/>
    <command cmdref="epg"		 cmdno="204"/>
    <command cmdref="menu"		 cmdno="84"/>
    <command cmdref="select"		 cmdno="240"/>
    <command cmdref="info"		 cmdno="15"/>
    <command cmdref="up"		 cmdno="88"/>
    <command cmdref="left"		 cmdno="90"/>
    <command cmdref="ok"		 cmdno="92"/>
    <command cmdref="right"		 cmdno="91"/>
    <command cmdref="down"		 cmdno="89"/>
    <command cmdref="volume_up"		 cmdno="16"/>
    <command cmdref="cmd_return"	 cmdno="85"/>
    <command cmdref="channel_up"	 cmdno="30"/>
    <command cmdref="volume_down"	 cmdno="17"/>
    <command cmdref="mute_toggle"	 cmdno="13"/>
    <command cmdref="channel_down"	 cmdno="31"/>
    <command cmdref="record_toggle"	 cmdno="55"/>
    <command cmdref="archive"		 cmdno="213"/>
    <command cmdref="stop"		 cmdno="49"/>
    <command cmdref="rewind"		 cmdno="33"/>
    <command cmdref="play"		 cmdno="56"/>
    <command cmdref="fast_forward"	 cmdno="32"/>
    <command cmdref="setup"		 cmdno="70"/>
    <command cmdref="zoom"		 cmdno="216"/>
    <command cmdref="help"		 cmdno="129"/>
    <command cmdref="teletext_on"	 cmdno="60"/>
    <command cmdref="red"		 cmdno="109"/>
    <command cmdref="green"		 cmdno="110"/>
    <command cmdref="yellow"		 cmdno="111"/>
    <command cmdref="blue"		 cmdno="112"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/snapshot-0.5.1/devices/canon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="canon" name="Canon EOS 450D" model="EOS-450D" type="camera">
    <description>Canon EOS 450D, and probably a lot of other Canon models.</description>
    <comment>References: http://www.doc-diy.net/photo/rc-1_hacked/</comment>
  <commandset type="ir" remotename="canon" protocol="raw_ccf">
    <command cmdref="trigger">
      <ccf>0000 007e 0002 0000 0010 00f0 0010 00f0</ccf>
    </command>
    <command cmdref="delayed_trigger">
      <ccf>0000 007e 0002 0000 0010 00af 0010 00af</ccf>
    </command>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/snapshot-0.5.2/devices/lamp_fs20_dimmer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="lamp_fs20_dimmer" name="Generic electrical consumer with FS20 dimmer" model="generic" type="ha">
    <commandset type="on_off">
      <command cmdref="power_on"/>
      <command cmdref="power_off"/>
      <command cmdref="power_toggle"/>
      <command cmdref="dim_up"/>
      <command cmdref="dim_down"/>
      <command cmdref="get_status"/>
      <command cmdref="set_power">
        <argument name="value" semantic="Power value in percent"/>
      </command>
      <command cmdref="dim_off_time">
        <argument name="time"/>
      </command>
      <command cmdref="dim_value_time">
        <argument name="value"/>
        <argument name="time"/>
      </command>
      <command cmdref="dim_max_time">
        <argument name="time"/>
      </command>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/panasonic_ptae_500.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<device id="panasonic_dvd_s75" name="Panasonic DVD S75" vendor="Panasonic" model="S75" type="projector">
  <commandset type="ir" protocol="panasonic2" toggle="no" deviceno="128" subdevice="72" remotename="panasonic_ptae_500">
    <command cmdref="cmd_power_toggle" cmdno="61"/>
    <command cmdref="cmd_in_video" cmdno="3"/>
    <command cmdref="cmd_menu" cmdno="122"/>
    <command cmdref="cmd_up" cmdno="90"/>
    <command cmdref="cmd_left" cmdno="92"/>
    <command cmdref="cmd_right" cmdno="93"/>
    <command cmdref="cmd_down" cmdno="91"/>
    <command cmdref="cmd_ok" cmdno="114"/>
    <command cmdref="cmd_normal" cmdno="97"/>
    <command cmdref="cmd_freeze_toggle" cmdno="2"/>
    <command cmdref="cmd_aspectratio" cmdno="222"/>
    <command cmdref="cmd_shutter" cmdno="145"/>
    <command cmdref="cmd_input" cmdno="109"/>
    <command cmdref="cmd_in_component1" cmdno="128"/>
    <command cmdref="cmd_in_vga" cmdno="6"/>
    <command cmdref="cmd_img_user" cmdno="129"/>
    <command cmdref="cmd_keystone" cmdno="81"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/mypowerbox.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="mypowerbox" name="mypowerbox" vendor="Bengt Martensson" model="xyz" type="ha">
    <commandset type="ir" protocol="rc5" deviceno="12" toggle="no" remotename="mypowerbox">
      <command cmdref="cmd_all_off" cmdno="0"/>
      <command cmdref="cmd_1toggle" cmdno="1"/>
      <command cmdref="cmd_2toggle" cmdno="2"/>
      <command cmdref="cmd_3toggle" cmdno="3"/>
      <command cmdref="cmd_4toggle" cmdno="4"/>
      <command cmdref="cmd_5toggle" cmdno="5"/>
      <command cmdref="cmd_6toggle" cmdno="6"/>
      <command cmdref="cmd_7toggle" cmdno="7"/>
      <command cmdref="cmd_8toggle" cmdno="8"/>
      <command cmdref="cmd_all_on" cmdno="9"/>

      <command cmdref="cmd_1on" cmdno="11"/>
      <command cmdref="cmd_2on" cmdno="12"/>
      <command cmdref="cmd_3on" cmdno="13"/>
      <command cmdref="cmd_4on" cmdno="14"/>
      <command cmdref="cmd_5on" cmdno="15"/>
      <command cmdref="cmd_6on" cmdno="16"/>
      <command cmdref="cmd_7on" cmdno="17"/>
      <command cmdref="cmd_8on" cmdno="18"/>

      <command cmdref="cmd_1off" cmdno="21"/>
      <command cmdref="cmd_2off" cmdno="22"/>
      <command cmdref="cmd_3off" cmdno="23"/>
      <command cmdref="cmd_4off" cmdno="24"/>
      <command cmdref="cmd_5off" cmdno="25"/>
      <command cmdref="cmd_6off" cmdno="26"/>
      <command cmdref="cmd_7off" cmdno="27"/>
      <command cmdref="cmd_8off" cmdno="28"/>
    </commandset>
    <commandset type="serial" protocol="rs232_2400_8n1">
      <command cmdref="cmd_all_off" transmit="C\rA\r"/>
      <command cmdref="cmd_1toggle" transmit="T\r1\r"/>
      <command cmdref="cmd_2toggle" transmit="T\r2\r"/>
      <command cmdref="cmd_3toggle" transmit="T\r3\r"/>
      <command cmdref="cmd_4toggle" transmit="T\r4\r"/>
      <command cmdref="cmd_5toggle" transmit="T\r5\r"/>
      <command cmdref="cmd_6toggle" transmit="T\r6\r"/>
      <command cmdref="cmd_7toggle" transmit="T\r7\r"/>
      <command cmdref="cmd_8toggle" transmit="T\r8\r"/>
      <command cmdref="cmd_all_on"  transmit="S\rA\r"/>

      <command cmdref="cmd_1on" transmit="S\r1\r"/>
      <command cmdref="cmd_2on" transmit="S\r2\r"/>
      <command cmdref="cmd_3on" transmit="S\r3\r"/>
      <command cmdref="cmd_4on" transmit="S\r4\r"/>
      <command cmdref="cmd_5on" transmit="S\r5\r"/>
      <command cmdref="cmd_6on" transmit="S\r6\r"/>
      <command cmdref="cmd_7on" transmit="S\r7\r"/>
      <command cmdref="cmd_8on" transmit="S\r8\r"/>

      <command cmdref="cmd_1off" transmit="C\r1\r"/>
      <command cmdref="cmd_2off" transmit="C\r2\r"/>
      <command cmdref="cmd_3off" transmit="C\r3\r"/>
      <command cmdref="cmd_4off" transmit="C\r4\r"/>
      <command cmdref="cmd_5off" transmit="C\r5\r"/>
      <command cmdref="cmd_6off" transmit="C\r6\r"/>
      <command cmdref="cmd_7off" transmit="C\r7\r"/>
      <command cmdref="cmd_8off" transmit="C\r8\r"/>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/devices/sony_tv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="sony_tv" name="Sony TV" vendor="Sony" model="Generic" type="tv">
  <commandset type="ir" protocol="sony12" deviceno="1" remotename="sony_tv">
    <command cmdref="cmd_volume_up"		cmdno="0x12"/>
    <command cmdref="cmd_volume_down"		cmdno="0x13"/>
    <command cmdref="cmd_channel_up"		cmdno="0x10"/>
    <command cmdref="cmd_channel_down"		cmdno="0x11"/>
    <command cmdref="cmd_av"			cmdno="0x25"/>
    <command cmdref="cmd_mute_toggle"		cmdno="0x14"/>
    <command cmdref="cmd_power_toggle"		cmdno="0x15"/>
    <command cmdref="cmd_power_on"		cmdno="0x2e"/>
    <command cmdref="cmd_power_off"		cmdno="0x2f"/>
    <command cmdref="cmd_contrast_up"		cmdno="0x18"/>
    <command cmdref="cmd_contrast_down" 	cmdno="0x19"/>
    <command cmdref="cmd_color_up"		cmdno="0x1a"/>
    <command cmdref="cmd_color_down"		cmdno="0x1b"/>
    <command cmdref="cmd_color_up"		cmdno="0x1e"/>
    <command cmdref="cmd_color_down"		cmdno="0x1f"/>
    <command cmdref="cmd_info"			cmdno="0x3a"/>
    <command cmdref="cmd_1"			cmdno="0x00"/>
    <command cmdref="cmd_2"			cmdno="0x01"/>
    <command cmdref="cmd_3"			cmdno="0x02"/>
    <command cmdref="cmd_4"			cmdno="0x03"/>
    <command cmdref="cmd_5"			cmdno="0x04"/>
    <command cmdref="cmd_6"			cmdno="0x05"/>
    <command cmdref="cmd_7"			cmdno="0x06"/>
    <command cmdref="cmd_8"			cmdno="0x07"/>
    <command cmdref="cmd_9"			cmdno="0x08"/>
    <command cmdref="cmd_0"			cmdno="0x09"/>
    <command cmdref="cmd_two_digit"		cmdno="0x39"/>
  </commandset>
</device>
