=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/dtds/macros.dtd
<!ELEMENT macros (description?,(macro|menu|macros)+) >
<!ATTLIST macros
	name	ID	#REQUIRED
        visibility (public|private) "public" >

<!ELEMENT macro (description?,prerequisites?,(true|false|match|command|select-src|delay|message|macrocall|cond|set-variable)+,jump?) >
<!ATTLIST       macro
        name    ID #REQUIRED
        visibility (public|private) "public" >

<!ELEMENT delay EMPTY >

<!ATTLIST delay
        duration NMTOKEN #REQUIRED >

<!ELEMENT message (#PCDATA) >
<!ATTLIST message
        class   (debug|info|critical|confirm) "info" >

<!ELEMENT description (#PCDATA) >

<!ELEMENT command (argument*) >
<!ATTLIST command
        device  NMTOKEN #REQUIRED
        command CDATA #REQUIRED
        count   NMTOKEN "1"
        toggle  (0|1|yes|no) "no" >

<!ELEMENT select-src EMPTY >
<!ATTLIST select-src
	device NMTOKEN #REQUIRED
	src NMTOKEN #REQUIRED
	zone NMTOKEN #IMPLIED
	connectiontype NMTOKEN #IMPLIED
	mediatype (audio_only|video_only|audio_video) "audio_video" >        

<!ELEMENT argument (#PCDATA) >

<!ELEMENT jump EMPTY >
<!ATTLIST jump
        class 		(device|macro|home) "device"
        pagegroup       NMTOKEN #REQUIRED
        page            NMTOKEN #REQUIRED >

<!ELEMENT prerequisites (prerequisite*) >

<!ELEMENT prerequisite (#PCDATA) >
<!ATTLIST prerequisite
        device  NMTOKEN #IMPLIED
        state   NMTOKEN #IMPLIED >

<!ELEMENT macrocall EMPTY >
<!ATTLIST macrocall
        macro IDREF #REQUIRED >

<!ELEMENT cond (clause+) >

<!ELEMENT clause ((true|false|match|message|command|select|macrocall|delay|code|cond)+) >

<!ELEMENT match ((match|message|command|select|macrocall|delay|code|cond)+) >
<!ATTLIST match
        regexp CDATA #REQUIRED >

<!--ELEMENT test (true|false|(command,expected-response)) -->

<!ELEMENT expected-response EMPTY >
<!ATTLIST expected-response
	regexp CDATA #REQUIRED >

<!ELEMENT true EMPTY >
<!ELEMENT false EMPTY >

<!ELEMENT menu (description?,macrocall*) >
<!ATTLIST menu
        name    CDATA   #REQUIRED
        id      ID      #REQUIRED
        nuke-prefix CDATA #IMPLIED >

<!ELEMENT code (#PCDATA) >
<!ATTLIST code
        wait (true|false) "true" >

<!ELEMENT set-variable EMPTY >
<!ATTLIST set-variable
        name    CDATA   #REQUIRED
        value   CDATA   #REQUIRED >

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/release-0.5.0/config/macros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE macros PUBLIC "-//bengt-martensson.de//macros//en" "../dtds/macros.dtd">
<macros name="mymacs">
    <description>Convention:
watch-DEVICE: turn to DEVICE for audio and video,
listen-DEVICE: turn to DEVICE for audio, leaving video alone (as far as possible)
look-DEVICE: turn to DEVICE for video, leave audio alone as far as
possible.

In macro names, we prefer hyphens (-) over underscores (_).

Macros are uniquely identified by their name. The folder structure ist just
imposing some visually pleasing order for humans. In particular, macros do not
inherit private-ness from a containing folder.

Use generic names ("amp") when the macro is generic, specific names when the
function is specific.
    </description>
    <macros visibility="private" name="testmacros">
        <macro name="testdelay">
            <message>Starting...</message>
            <delay duration="10000"/>
            <message>..finished</message>
        </macro>
    </macros>

    <macros name="Master-AV-macros">
        <description>Macros for Master Audio- and Video</description>
        <macros name="Receivermacros">
            <description>Macros for setting volume to a preset value</description>
            <macro name="louder">
                <description>Turn up the volume slightly.</description>
                <command device="amp" command="volume_up" count="10"/>
            </macro>
            <macro name="quieter">
                <command device="amp" command="volume_down" count="10"/>
            </macro>
            <macro name="volume-loud">
                <description>Somewhat loud (-20 dB)</description>
                <command device="amp" command="set_volume">
                    <argument>60</argument>
                </command>
            </macro>
            <macro name="volume-normal">
                <description>-27 dB</description>
                <command device="amp" command="set_volume">
                    <argument>53</argument>
                </command>
            </macro>
            <macro name="volume-room">
                <description>-35 dB</description>
                <command device="amp" command="set_volume">
                    <argument>45</argument>
                </command>
            </macro>
            <macro name="volume-quiet">
                <description>-42 dB</description>
                <command device="amp" command="set_volume">
                    <argument>38</argument>
                </command>
            </macro>
            <macro name="volume-feeble">
                <description>Very quiet (-50 dB)</description>
                <command device="amp" command="set_volume">
                    <argument>30</argument>
                </command>
            </macro>
            <macro name="volume-faint">
                <description>Barely audible (-65 dB)</description>
                <command device="amp" command="set_volume">
                    <argument>15</argument>
                </command>
            </macro>
      
            <macro name="volume-standard">
                <description>"Standard" volume, whatever that means</description>
                <delay duration="1"/>
                <macrocall macro="volume-room"/>
            </macro>
      
            <macro name="desk-amp-on">
                <description>Turn on the desk amplifier</description>
                <command device="yamaha_desk" command="power_on"/>
            </macro>
      
            <macro name="desk-amp-off">
                <description>Turn on the desk amplifier</description>
                <command device="yamaha_desk" command="power_off"/>
            </macro>

            <macro name="volume-mute-on">
                <description>Master mute</description>
                <command device="amp" command="mute_on"/>
            </macro>

            <macro name="volume-mute-off">
                <description>Master mute</description>
                <command device="amp" command="mute_off"/>
            </macro>

            <macro visibility="private" name="assure-amp-on">
                <cond>
                    <clause>
                        <match regexp="PWSTANDBY">
                            <command device="amp" command="get_power"/>
                        </match>
                        <command device="amp" command="power_on"/>
                        <delay duration="5000"/>
                        <true/>
                    </clause>
                </cond>
            </macro>

            <macro visibility="private" name="assure-external-input">
                <cond>
                    <clause>
                        <match regexp="SDEXT.IN-1">
                            <command device="amp" command="get_input_mode"/>
                        </match>
                    </clause>
                    <clause>
                        <command device="amp" command="input_mode_ext_in"/>
                    </clause>
                </cond>
            </macro>

            <macro visibility="private" name="assure-hdmi-input">
                <cond>
                    <clause>
                        <match regexp="SDHDMI">
                            <command device="amp" command="get_input_mode"/>
                        </match>
                    </clause>
                    <clause>
                        <command device="amp" command="input_mode_hdmi"/>
                    </clause>
                </cond>
            </macro>


        </macros> <!-- receiver-macros -->
    </macros>

    <macros name="AV-output-macros">


        <macros name="projector-macros">
            <macro visibility="private" name="projector_ison">
                <description>Returns true if the projector is on</description>
                <match regexp="00|04">
                    <command device="projector" command="get_status"/>
                </match>
            </macro>

      <!-- Debugging -->
            <macro visibility="private" name="test4projector">
                <description>Investigates if the projector is on</description>
                <cond>
                    <clause>
                        <macrocall macro="projector_ison"/>
                        <message class="confirm">The projector is on!</message>
                    </clause>
                    <clause>
                        <true/>
                        <message class="confirm">The projector is NOT on!</message>
                    </clause>
                </cond>
            </macro>
        </macros>
    </macros>

    <macros name="AV-source-macros">

        <macros name="tunermacros">
            <description>Tuner</description>
            <macro name="listen-tuner">
                <description>Listen to the tuner</description>
                <command device="amp" command="in_tuner"/> <!-- toggles fm/am, grrr -->
                <command device="amp" command="fm"/>
            </macro>
        </macros>

        <macros name="DVD-macros">

            <macro name="dvd-ison" visibility="private">
	<!-- officially there is a get_power command, however, it does not work -->
                <command device="oppo" command="get_version"/> <!-- timesout if off -->
            </macro>

            <macro name="listen-dvd">
                <description>Listen to DVD.</description>
                <macrocall macro="assure-amp-on"/>
                <command device="dvd" command="power_on"/>
                <select-src device="main-receiver" src="dvd"/>
            </macro>

            <macro name="watch-dvd">
                <description>Watch to DVD on TV or projector.</description>
                <!--macrocall macro="tv-unless-projector"/-->
                <macrocall macro="listen-dvd"/>
                <command device="dvd" command="power_on"/>
                <select-src device="tv" src="denon" connectiontype="hdmi"/>
            </macro>

            <macro name="look-dvd">
                <description>Watch to DVD on TV, without sound.</description>
                <!--macrocall macro="tv-unless-projector"/-->
                <macrocall macro="assure-amp-on"/>
                <command device="dvd" command="power_on"/>
                <select-src device="main-receiver" src="dvd" mediatype="video_only"/>
            </macro>

            <macro name="watch-dvd-audio">
                <description>Sets up the system for DVD audio with 5.1 channels with support of back rear speakers. TV support.</description>
                <macrocall macro="listen-dvd-audio"/>
                <!--macrocall macro="tv-unless-projector"/-->
                <select-src device="tv" src="amp" connectiontype="hdmi"/>
	<!--set-variable name="Hometheatre.selectedDevice" value='"dvd"'/-->
            </macro>

            <macro name="listen-dvd-audio">
                <description>Sets up the system for DVD audio with 5.1 channels with support of back rear speakers. Leaves picture alone.</description>
                <macrocall macro="listen-dvd"/>
                <macrocall macro="assure-external-input"/>
                <command device="analog_8ch_switch" command="dvd_audio_bs"/>
	<!--set-variable name="Hometheatre.selectedDevice" value='"dvd"'/-->
            </macro>

            <macro name="pause-toggle-dvd">
                <description>Pause or unpause the dvd player</description>
                <command device="dvd" command="pause_toggle"/>
            </macro>

            <macro name="pause-off-dvd">
                <description>Unpause the dvd player</description>
                <command device="dvd" command="play"/>
            </macro>
      
            <macro name="pause-on-dvd">
                <description>pause the dvd player, safe but noisy version</description>
                <command device="dvd" command="play"/>
                <delay duration="1000"/>
                <command device="dvd" command="pause_toggle"/>
