=== bengtmartensson/oldharctoolbox/dtds/devices.dtd
<!-- Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  This file is offered as-is,
     without any warranty.
-->

<!-- Presently, id's for devices are not supported -->

<!ELEMENT devices (device)+ >

<!ELEMENT device (description?,comment?,attributes?,aliases?,delays?,jp1data?,(commandset|xi:include)*) >
<!ATTLIST device
        xmlns:xi CDATA #IMPLIED
        id ID #REQUIRED
        name CDATA #REQUIRED
        vendor CDATA #IMPLIED
        vendorurl CDATA #IMPLIED
        model CDATA #REQUIRED
        pingable_on (yes|no) #IMPLIED
        pingable_standby (yes|no) #IMPLIED
        type     (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|camera|other|dumb|undefined) "undefined"
        alt_type (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|camera|other|dumb|undefined) "undefined" >

<!ELEMENT xi:include (xi:fallback?)>
<!ATTLIST xi:include
    xmlns:xi        CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
    href            CDATA       #IMPLIED
    parse           (xml|text)  "xml"
    xpointer        CDATA       #IMPLIED
    encoding        CDATA       #IMPLIED
    accept          CDATA       #IMPLIED
    accept-language CDATA       #IMPLIED
>

<!ELEMENT xi:fallback ANY>
<!ATTLIST xi:fallback
    xmlns:xi   CDATA   #FIXED   "http://www.w3.org/2001/XInclude"
>

<!ELEMENT delays (delay)* >

<!ELEMENT delay EMPTY >
<!ATTLIST delay
        type NMTOKEN #REQUIRED
        delay NMTOKEN #REQUIRED >

<!ELEMENT attributes (attribute)+ >

<!ELEMENT attribute EMPTY >
<!ATTLIST attribute
	name NMTOKEN #REQUIRED
	defaultvalue CDATA #IMPLIED >

<!ELEMENT aliases (alias+) >

<!ELEMENT alias EMPTY >
<!ATTLIST alias
	name NMTOKEN #REQUIRED
        command NMTOKEN #REQUIRED >

<!ELEMENT jp1data (setupcode|fixed_data)+ >

<!ELEMENT setupcode EMPTY >
<!ATTLIST setupcode
	value CDATA #REQUIRED >

<!ELEMENT fixed_data EMPTY >
<!ATTLIST fixed_data
	data CDATA #REQUIRED >

<!ELEMENT commandset (commandgroup|commandgroupref|command|xi:include)* >
<!ATTLIST commandset
        type (ir|rf433|rf868|www|web_api|tcp|udp|serial|bluetooth|on_off|ip|special|telnet|sensor) "ir"
        ifattribute CDATA #IMPLIED
        protocol NMTOKEN #IMPLIED
        prefix CDATA ""
        suffix CDATA ""
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        portnumber CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        subdevice CDATA #IMPLIED
        fixed_data CDATA #IMPLIED
        user CDATA #IMPLIED
        password CDATA #IMPLIED
        toggle (yes|no) "no"
        name CDATA #IMPLIED
        original_remote CDATA #IMPLIED
        remotename NMTOKEN #IMPLIED
        delay_between_chars CDATA "0"
 	pseudo_power_on NMTOKEN #IMPLIED
 	delay_between_reps CDATA "0"
 	remark CDATA #IMPLIED
        charset CDATA "utf-8" >

<!ELEMENT commandgroup (commandgroup|command)+ >
<!ATTLIST commandgroup
        id ID #IMPLIED
        name CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        description CDATA #IMPLIED >

<!ELEMENT commandgroupref EMPTY >
<!ATTLIST commandgroupref
        commandgroup IDREF #REQUIRED >

<!-- For now, there are no more than one argument accepted -->
<!ELEMENT command (ccf_cooked?,(toggle_pair|ccf)?,remark?,argument*,returnvalues?) >
<!ATTLIST command
        cmdref NMTOKEN #REQUIRED
        cmdno CDATA #IMPLIED
        name CDATA #IMPLIED
	zone (1|2|3|record) #IMPLIED
        type (discrete|toggle|cyclic) #IMPLIED
	remark CDATA #IMPLIED
        ifattribute CDATA #IMPLIED
        wakeup (yes|no) #IMPLIED
        transmit CDATA #IMPLIED
        expected_response CDATA #IMPLIED
        response_ending CDATA #IMPLIED
        returntype CDATA #IMPLIED
        returnwidth CDATA #IMPLIED
        returncontent CDATA #IMPLIED
        response_lines CDATA #IMPLIED >

<!ELEMENT returnvalues (syntax?,semantics?,description?) >

<!ELEMENT syntax (returntype*) >
<!ATTLIST syntax
	parse CDATA #IMPLIED >

<!ELEMENT semantics (table) >
<!ELEMENT returntype EMPTY >
<!ATTLIST returntype
	type (string|texttable|decimal_integer|hexadecimal_integer|hh:mm:ss|dd.mm.yyyy|tv_radio|0_1|on_off|percent|4:3_16:9|dbox_videoformat|dbox_videooutput) #REQUIRED
	length CDATA #IMPLIED >

<!ELEMENT table (entry+,default?) >
<!ATTLIST table
	index (string|number|hexnumber) "string" >

<!ELEMENT entry EMPTY >
<!ATTLIST entry
	value CDATA #REQUIRED
	desc CDATA "" >

<!ELEMENT default EMPTY >
<!ATTLIST default
	desc CDATA "" >

<!ELEMENT remark (#PCDATA) >

<!ELEMENT argument (description)? >
<!ATTLIST argument
        name CDATA #REQUIRED
        semantic CDATA #IMPLIED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT comment (#PCDATA) >

<!ELEMENT ccf (#PCDATA) >
<!ATTLIST ccf
	toggle (0|1) #IMPLIED >

<!ELEMENT toggle_pair (ccf, ccf) >

<!ELEMENT ccf_cooked (#PCDATA) >

=== bengtmartensson/oldharctoolbox/devices/blind_nomemory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="blind_nomemory" name="Generic blind or screen that moves up (by power_reverse_on) or down (by power_on), stops when power removed" model="generic" type="dumb">
    <attributes>
      <attribute name="memory" value="no"/>
    </attributes>
    <aliases>
      <alias name="down" command="power_on"/>
      <alias name="up" command="power_reverse_on"/>
      <alias name="power_off" command="power_reverse_on"/>
    </aliases>
    <commandset type="on_off">
      <command cmdref="cmd_power_on"/>
      <command cmdref="cmd_power_reverse_on"/>
      <command cmdref="get_status"/>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/devices/philips_37pfl9603.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="philips_37pfl9603" name="Philips TV 37PFL9603" vendor="Philips" model="37PFL9603" type="tv" pingable_on="yes" pingable_standby="no">
  <jp1data>
    <setupcode value="1556"/>
  </jp1data>
  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="0"
    remotename="philips_37pfl9603">
    <command cmdref="cmd_0" 				cmdno="0"/>
    <command cmdref="cmd_1" 				cmdno="1"/>
    <command cmdref="cmd_2" 				cmdno="2"/>
    <command cmdref="cmd_3" 				cmdno="3"/>
    <command cmdref="cmd_4" 				cmdno="4"/>
    <command cmdref="cmd_5" 				cmdno="5"/>
    <command cmdref="cmd_6" 				cmdno="6"/>
    <command cmdref="cmd_7" 				cmdno="7"/>
    <command cmdref="cmd_8" 				cmdno="8"/>
    <command cmdref="cmd_9" 				cmdno="9"/>
    <command cmdref="power_toggle" 	name="power"	cmdno="12"/>
    <!--command cmdref="tv_mode"			cmdno="63"/-->
    <command cmdref="channel_up" 			cmdno="32"/>
    <command cmdref="channel_down" 			cmdno="33"/>
    <command cmdref="mute_toggle" 	name="mute"	cmdno="13"/>
    <command cmdref="last_channel" 			cmdno="34"/>
    <command cmdref="volume_up" 			cmdno="16"/>
    <command cmdref="volume_down" 			cmdno="17"/>
    <command cmdref="PP" 				cmdno="14"/>
    <command cmdref="info" 				cmdno="15"/>
    <command cmdref="brightness_down" 			cmdno="19"/>
    <command cmdref="brightness_up" 			cmdno="18"/>
    <command cmdref="aspectratio"	 		cmdno="126"/>
    <command cmdref="menu" 				cmdno="82"/>
    <command cmdref="up" 				cmdno="80"/>
    <command cmdref="down" 				cmdno="81"/>
    <command cmdref="left" 				cmdno="85"/>
    <command cmdref="right" 				cmdno="86"/>
    <command cmdref="ok" 				cmdno="87"/>
    <command cmdref="red" 				cmdno="107"/>
    <command cmdref="green" 				cmdno="108"/>
    <command cmdref="yellow" 				cmdno="109"/>
    <command cmdref="blue" 				cmdno="110"/>
    <command cmdref="white" 				cmdno="111"/>
    <command cmdref="menu_off" 				cmdno="83"/>
    <command cmdref="I_II" 				cmdno="35"/>
    <command cmdref="teletext" 				cmdno="60"/>
    <command cmdref="teletext_freeze" 			cmdno="41"/>
    <command cmdref="teletext_reveal" 			cmdno="44"/>
    <command cmdref="teletext_hide" 			cmdno="45"/>
    <command cmdref="teletext_translucent" 		cmdno="46"/>
    <command cmdref="teletext_doubleheight" 		cmdno="43"/>
    <command cmdref="teletext_time" 			cmdno="42"/>
    <command cmdref="PIP" 				cmdno="88"/>
    <command cmdref="PIP_source" 			cmdno="95"/>
    <command cmdref="PIP_exchange" 			cmdno="90"/>
    <command cmdref="PIP_freeze" 			cmdno="101"/>
    <command cmdref="PIP_position" 			cmdno="89"/>
    <command cmdref="PIP_ch_down" 			cmdno="103"/>
    <command cmdref="PIP_ch_up" 			cmdno="102"/>
    <!--command cmdref="freeze_toggle"			cmdno="93"/-->
    <!--command cmdref="DNR" 				cmdno="97"/-->
    <!--command cmdref="special" 			cmdno="94"/-->

    <command cmdref="in_ext2" 				cmdno="57"/>
    <command cmdref="power_on" 				cmdno="63"/>
    <command cmdref="power_off" 			cmdno="61"/>

    <command cmdref="input"				cmdno="56"/>
  </commandset>

  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="3" remotename="philips_37pfl9603">
<!--
Notes=Dummy device to support RC-5 commands on Philips TV discrete input selection for remotes w/o 2 byte code support (e.g. URC-6131).\n\nFunctions for this device\:\nav1\nav3\nhdmi1\nhdmi3\nside\nambilight discrete on\nambilight discrete off\nformat auto
-->

    <command cmdref="in_ext1"				cmdno="4"/>
    <command cmdref="in_side"				cmdno="5"/>
    <command cmdref="in_ext3"				cmdno="56"/>
    <command cmdref="in_hdmi1"				cmdno="57"/>
    <command cmdref="in_hdmi2"				cmdno="123"/>
    <command cmdref="in_hdmi3"				cmdno="6"/>
    <command cmdref="in_hdmi4"				cmdno="7"/>
    <command cmdref="tv_mode"				cmdno="72"/>
    <command cmdref="in_side"				cmdno="58"/>
    <command cmdref="ambilight_on"			cmdno="40"/>
    <command cmdref="ambilight_off"			cmdno="41"/>
    <!--command cmdref="aspectratio_automatic"		cmdno="61"/-->
  </commandset>

  <commandset remotename="philips_37pfl9603_rc6" type="ir" protocol="rc6" toggle="yes" deviceno="0">
    <command cmdref="power_toggle" 	cmdno="12"/>
    <command cmdref="input" 		cmdno="56"/>
    <command cmdref="teletext" 		cmdno="60"/>
    <command cmdref="teletext_pip" 	cmdno="93"/>
    <command cmdref="subtitle" 		cmdno="75"/>
    <command cmdref="aspectratio" 	cmdno="245"/>
    <command cmdref="red" 		cmdno="109"/>
    <command cmdref="green" 		cmdno="110"/>
    <command cmdref="yellow" 		cmdno="111"/>
    <command cmdref="blue" 		cmdno="112"/>
    <command cmdref="epg"		cmdno="204"/>
    <command cmdref="info"		cmdno="15"/>
    <command cmdref="up"		cmdno="88"/>
    <command cmdref="down"		cmdno="89"/>
    <command cmdref="left"		cmdno="90"/>
    <command cmdref="right"		cmdno="91"/>
    <command cmdref="ok"		cmdno="92"/>
    <command cmdref="cmd_return"	cmdno="10"/>
    <command cmdref="menu"		cmdno="84"/>

    <command cmdref="rewind"		cmdno="43"/>
    <command cmdref="play_pause"	cmdno="44"/>
    <command cmdref="fast_forward"	cmdno="40"/>
    <command cmdref="stop"		cmdno="49"/>
    <command cmdref="record_toggle"	cmdno="55"/>

    <command cmdref="volume_up"		cmdno="16"/>
    <command cmdref="volume_down"	cmdno="17"/>
    <command cmdref="mute_toggle"	cmdno="13"/>
    <command cmdref="cmd_0"		cmdno="0"/>
    <command cmdref="cmd_1"		cmdno="1"/>
    <command cmdref="cmd_2"		cmdno="2"/>
    <command cmdref="cmd_3"		cmdno="3"/>
    <command cmdref="cmd_4"		cmdno="4"/>
    <command cmdref="cmd_5"		cmdno="5"/>
    <command cmdref="cmd_6"		cmdno="6"/>
    <command cmdref="cmd_7"		cmdno="7"/>
    <command cmdref="cmd_8"		cmdno="8"/>
    <command cmdref="cmd_9"		cmdno="9"/>
    <command cmdref="clock_toggle"	cmdno="127"/>
    <command cmdref="PP"		cmdno="10"/>
    <command cmdref="ambilight_toggle"	cmdno="143"/>
    <command cmdref="ambilight_mode"	cmdno="144"/>
  </commandset>

  <xi:include href="ping.xi"/>
</device>

=== bengtmartensson/oldharctoolbox/src/main/devices/irtrans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="irtrans" name="IRTrans Ethernet" model="IRT-LAN-DB" pingable_on="yes">
  <commandset type="web_api">
    <!-- I have no idea if this is universally valid; at least it works for me -->
    <command cmdref="reboot" transmit="ridjeg3o5ew22.htm"
      response_lines="0" remark="Produces error despite success"/>
  </commandset>

  <commandset type="tcp" suffix="\r" open="ASCI" portnumber="21000">
    <command cmdref="get_version" transmit="Aver" response_lines="1"/>
  </commandset>
  <commandset type="tcp" portnumber="21000">
    <command cmdref="listen" transmit="ASCI" response_lines="-1"/>
  </commandset>
  <commandset type="tcp" portnumber="21000">
    <command cmdref="listen1" transmit="ASCI" response_lines="1"/>
  </commandset>

  <commandset type="special" portnumber="21000">
    <command cmdref="get_remotes"/>
    <command cmdref="get_commands">
      <argument name="remote"/>
    </command>
    <command cmdref="send_ir">
      <argument name="remote"/>
      <argument name="command"/>
    </command>
  </commandset>

  <xi:include href="ping.xi"/>
  <xi:include href="www.xi"/>
</device>

=== bengtmartensson/oldharctoolbox/src/main/devices/oppo_bdp83.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="oppo_bdp83" name="Oppo BDP-83" vendor="Oppo" model="bdp-83"
  type="dvd" pingable_on="yes" pingable_standby="no">

  <attributes>
    <!--attribute name="rs232_version1"/-->
    <attribute name="rs232"/>
    <attribute name="bluraychip_rs232"/>
    <attribute name="rc_1" defaultvalue="yes"/><!-- RC device 1 -->
    <attribute name="rc_2"/><!-- RC device 2 -->
    <attribute name="rc_3"/><!-- RC device 3 -->
  </attributes>
  <delays>
    <delay type="intra-command" delay="1500"/>
  </delays>
  <jp1data>
    <setupcode value="1525"/>
  </jp1data>
  <xi:include href="oppo_bdp_ir_commands_1.xi"/>
  <xi:include href="oppo_bdp_ir_commands_2.xi"/>
  <xi:include href="oppo_bdp_ir_commands_3.xi"/>
  <xi:include href="oppo_bdp_serial_commands.xi"/>
  <xi:include href="ping.xi"/>
</device>

=== bengtmartensson/oldharctoolbox/devices/rc5_cd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="rc5_cd" name="Canonical RC5 CD-Player" vendor="" model="" type="cd">
  <jp1data>
    <setupcode value="1351"/>
  </jp1data>
  <commandset type="ir" protocol="rc5" deviceno="20" toggle="yes" remotename="rc5_cd">
    <command cmdref="cmd_0" 			cmdno="0"/>
    <command cmdref="cmd_1" 			cmdno="1"/>
    <command cmdref="cmd_2" 			cmdno="2"/>
    <command cmdref="cmd_3" 			cmdno="3"/>
    <command cmdref="cmd_4" 			cmdno="4"/>
    <command cmdref="cmd_5" 			cmdno="5"/>
    <command cmdref="cmd_6" 			cmdno="6"/>
    <command cmdref="cmd_7" 			cmdno="7"/>
    <command cmdref="cmd_8" 			cmdno="8"/>
    <command cmdref="cmd_9" 			cmdno="9"/>
    <command cmdref="power_toggle" 		cmdno="12"/>
    <command cmdref="in_cd"			cmdno="63"/>
    <command cmdref="previous" 			cmdno="33"/>
    <command cmdref="next" 			cmdno="32"/>
    <command cmdref="play" 			cmdno="53"/>
    <command cmdref="rewind" 			cmdno="50"/>
    <command cmdref="fast_forward" 		cmdno="52"/>
    <command cmdref="stop" 			cmdno="54"/>
    <command cmdref="pause"      		cmdno="48"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/devices/panasonic_dvd_s75.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<device id="panasonic_dvd_s75" name="Panasonic DVD S75" vendor="Panasonic" model="S75" type="dvd">
  <commandset type="ir" protocol="panasonic" toggle="no" deviceno="176" subdevice="0" remotename="panasonic_dvd_s75">
<!--
    <command cmdref="cmd_0"		      cmdno="0x98"/>
    <command cmdref="cmd_1"		      cmdno="0x08"/>
    <command cmdref="cmd_2"		      cmdno="0x88"/>
    <command cmdref="cmd_3"		      cmdno="0x48"/>
    <command cmdref="cmd_4"		      cmdno="0xc8"/>
    <command cmdref="cmd_5"		      cmdno="0x28"/>
    <command cmdref="cmd_6"		      cmdno="0xa8"/>
    <command cmdref="cmd_7"		      cmdno="0x68"/>
    <command cmdref="cmd_8"		      cmdno="0xe8"/>
    <command cmdref="cmd_9"		      cmdno="0x18"/>
    <command cmdref="cmd_a_b"		      cmdno="0x12"/>
    <command cmdref="cmd_a_srd"		      cmdno="0x79"/>
    <command cmdref="cmd_angle"		      cmdno="0x09"/>
    <command cmdref="cmd_audio"		      cmdno="0xcc"/>
    <command cmdref="cmd_audio_only"		cmdno="0x87"/>
    <command cmdref="cmd_clear" name="cancel"	cmdno="0xc1"/>
    <command cmdref="cmd_depth_enh"	      cmdno="0x1b"/>
    <command cmdref="cmd_display"	      cmdno="0x49"/>
    <command cmdref="cmd_double_remaster"	cmdno="0x97"/>
    <command cmdref="cmd_down"		cmdno="0x61"/>
    <command cmdref="cmd_fast_forward"	cmdno="0xa0"/>
    <command cmdref="cmd_group"			cmdno="0x07"/>
    <command cmdref="cmd_left"		cmdno="0xe1"/>
    <command cmdref="cmd_marker"		cmdno="0x71"/>
    <command cmdref="cmd_menu"		cmdno="0x01"/>
    <command cmdref="cmd_next"		cmdno="0x52"/>
    <command cmdref="cmd_ok"			cmdno="0x41"/>
    <command cmdref="cmd_open_close"		cmdno="0x80"/>
    <command cmdref="cmd_still_advance"		cmdno="0x60"/>
    <command cmdref="cmd_play"		cmdno="0x50"/>
    <command cmdref="cmd_play_mode"		cmdno="0xb1"/>
    <command cmdref="cmd_pos_mem"		cmdno="0x62"/>
    <command cmdref="cmd_power_off"		cmdno="0xfc"/>
    <command cmdref="cmd_power_on"		cmdno="0x7c"/>
    <command cmdref="cmd_power_toggle"	cmdno="0xbc"/>
    <command cmdref="cmd_previous"		cmdno="0x92"/>
    <command cmdref="cmd_repeat"		cmdno="0x31"/>
    <command cmdref="cmd_return"		cmdno="0x81"/>
    <command cmdref="cmd_rewind"		cmdno="0x20"/>
    <command cmdref="cmd_right"			cmdno="0x11"/>
    <command cmdref="cmd_setup"			cmdno="0x29"/>
    <command cmdref="cmd_sleep"			cmdno="0xd7"/>
    <command cmdref="cmd_special"		cmdno="0xa2"/>
    <command cmdref="cmd_stop"		cmdno="0x00"/>
    <command cmdref="cmd_subtitle"		cmdno="0x89"/>
    <command cmdref="cmd_title"			cmdno="0xd9"/>
    <command cmdref="cmd_two_digit" name="./.." cmdno="0x91"/>
    <command cmdref="cmd_up"			cmdno="0xa1"/>
    <command cmdref="cmd_vss"		cmdno="0x79"/>
    <command cmdref="cmd_zoom"		cmdno="0x83"/>
    <command cmdref="cmd_0xfd"		cmdno="0xfd"/>
-->

    <command cmdref="cmd_0" 		cmdno="25"/>
    <command cmdref="cmd_1" 		cmdno="16"/>
    <command cmdref="cmd_2" 		cmdno="17"/>
    <command cmdref="cmd_3" 		cmdno="18"/>
    <command cmdref="cmd_4" 		cmdno="19"/>
    <command cmdref="cmd_5" 		cmdno="20"/>
    <command cmdref="cmd_6" 		cmdno="21"/>
    <command cmdref="cmd_7" 		cmdno="22"/>
    <command cmdref="cmd_8" 		cmdno="23"/>
    <command cmdref="cmd_9" 		cmdno="24"/>
    <command cmdref="cmd_a_b" 		cmdno="72"/>
    <command cmdref="cmd_a_srd" 	cmdno="158"/>
    <command cmdref="cmd_angle" 	cmdno="144"/>
    <command cmdref="cmd_audio" 	cmdno="51"/>
    <command cmdref="cmd_audio_only" 	cmdno="225"/>
    <command cmdref="cmd_clear" 	cmdno="131"/>
    <command cmdref="cmd_depth_enh" 	cmdno="216"/>
    <command cmdref="cmd_osd" 		cmdno="146"/>
    <command cmdref="cmd_double_remaster" cmdno="233"/>
    <command cmdref="cmd_down" 		cmdno="134"/>
    <command cmdref="cmd_fast_forward" 	cmdno="5"/>
    <command cmdref="cmd_group" 	cmdno="224"/>
    <command cmdref="cmd_left" 		cmdno="135"/>
    <command cmdref="cmd_marker" 	cmdno="142"/>
    <command cmdref="cmd_menu" 		cmdno="128"/>
    <command cmdref="cmd_next" 		cmdno="74"/>
    <command cmdref="cmd_ok" 		cmdno="130"/>
    <command cmdref="cmd_open_close" 	cmdno="1"/>
    <command cmdref="cmd_still_advance" cmdno="6"/>
    <command cmdref="cmd_play" 		cmdno="10"/>
    <command cmdref="cmd_play_mode" 	cmdno="141"/>
    <command cmdref="cmd_pos_mem" 	cmdno="70"/>
    <command cmdref="cmd_power_off" 	cmdno="63"/>
    <command cmdref="cmd_power_on" 	cmdno="62"/>
    <command cmdref="cmd_power_toggle" 	cmdno="61"/>
    <command cmdref="cmd_previous" 	cmdno="73"/>
    <command cmdref="cmd_repeat" 	cmdno="140"/>
    <command cmdref="cmd_return" 	cmdno="129"/>
    <command cmdref="cmd_rewind" 	cmdno="4"/>
    <command cmdref="cmd_right" 	cmdno="136"/>
    <command cmdref="cmd_setup" 	cmdno="148"/>
    <command cmdref="cmd_sleep" 	cmdno="235"/>
    <command cmdref="cmd_special" 	cmdno="69"/>
    <command cmdref="cmd_stop" 		cmdno="0"/>
    <command cmdref="cmd_subtitle" 	cmdno="145"/>
    <command cmdref="cmd_title" 	cmdno="155"/>
    <command cmdref="cmd_two_digit" 	cmdno="137"/>
    <command cmdref="cmd_up" 		cmdno="133"/>
    <command cmdref="cmd_vss" 		cmdno="158"/>
    <command cmdref="cmd_zoom" 		cmdno="193"/>
    <command cmdref="cmd_0xfd"		cmdno="0xfd"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/devices/panasonic_vcr_nvf55.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<device id="panasonic_dvd_s75" name="Panasonic DVD S75" vendor="Panasonic" model="S75" type="dvd">
  <!-- Use subdevice=32 for VCR2 -->
  <commandset type="ir" protocol="panasonic" toggle="no" deviceno="144" subdevice="0" remotename="panasonic_vcr_nvf55">
    <command cmdref="cmd_still_advance" 	cmdno="6"/>
    <command cmdref="cmd_stop" 			cmdno="0"/>
    <command cmdref="cmd_still_advance" 	cmdno="6"/>
    <command cmdref="cmd_rewind" 		cmdno="2"/>
    <command cmdref="cmd_play" 			cmdno="10"/>
    <command cmdref="cmd_fast_forward" 		cmdno="3"/>
    <command cmdref="cmd_record_on" 		cmdno="8"/>
    <command cmdref="cmd_slow_down" 		cmdno="143"/>
    <command cmdref="cmd_slow" 			cmdno="15"/>
    <command cmdref="cmd_slow_up" 		cmdno="142"/>
    <command cmdref="cmd_clock_counter" 	cmdno="86"/>
    <command cmdref="cmd_tape_remaining" 	cmdno="85"/>
    <command cmdref="cmd_reset" 		cmdno="84"/>
    <command cmdref="cmd_monitor" 		cmdno="145"/>
    <command cmdref="cmd_vcr_tv" 		cmdno="54"/>
    <command cmdref="cmd_input_select" 		cmdno="192"/>
    <command cmdref="cmd_index" 		cmdno="64"/>
    <command cmdref="cmd_time_search" 		cmdno="68"/>
    <command cmdref="cmd_tracking_down" 	cmdno="178"/>
    <command cmdref="cmd_tracking_up" 		cmdno="177"/>
    <command cmdref="cmd_repeat" 		cmdno="249"/>
    <command cmdref="cmd_memory" 		cmdno="244"/>
    <command cmdref="cmd_sleep" 		cmdno="242"/>
    <command cmdref="cmd_auto_rewind" 		cmdno="243"/>
    <command cmdref="cmd_audio" 		cmdno="51"/>
    <command cmdref="cmd_1" 			cmdno="16"/>
    <command cmdref="cmd_2" 			cmdno="17"/>
    <command cmdref="cmd_3" 			cmdno="18"/>
    <command cmdref="cmd_4" 			cmdno="19"/>
    <command cmdref="cmd_5" 			cmdno="20"/>
    <command cmdref="cmd_6" 			cmdno="21"/>
    <command cmdref="cmd_7" 			cmdno="22"/>
    <command cmdref="cmd_8" 			cmdno="23"/>
    <command cmdref="cmd_9" 			cmdno="24"/>
    <command cmdref="cmd_0" 			cmdno="25"/>
    <command cmdref="cmd_two_digit" 		cmdno="59"/>
    <command cmdref="cmd_timer" 		cmdno="180"/>
    <command cmdref="cmd_pal_secam" 		cmdno="201"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/devices/cyberhome-ch_dvd_402.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<device id="cyberhome-ch_dvd_402" name="Cyberhome DVD 402" vendor="Cyberhome" model="402" type="dvd">
  <commandset type="ir" protocol="nec1" toggle="no" deviceno="114" subdevice="205" remotename="cyberhome_dvd_402">
    <command cmdref="power_toggle" 	cmdno="14"/>
    <command cmdref="open_close" 	cmdno="26"/>
    <command cmdref="title" 	cmdno="64"/>
    <command cmdref="menu" 		cmdno="2"/>
    <command cmdref="setup" 	cmdno="65"/>
    <command cmdref="display" 	cmdno="80"/>
    <command cmdref="audio" 	cmdno="22"/>
    <command cmdref="angle" 	cmdno="84"/>
    <command cmdref="mute_toggle" 	cmdno="7"/>
    <command cmdref="cmd_goto"	 	cmdno="18"/>
    <command cmdref="subtitle" 	cmdno="88"/>

    <command cmdref="up" 		cmdno="68"/>
    <command cmdref="down" 		cmdno="29"/>
    <command cmdref="left" 		cmdno="28"/>
    <command cmdref="right" 	cmdno="72"/>
    <command cmdref="ok" 		cmdno="92"/>

    <command cmdref="rewind" 	cmdno="31"/>
    <command cmdref="fast_forward" 	cmdno="93"/>
    <command cmdref="play" 		cmdno="6"/>
    <command cmdref="previous" 	cmdno="24"/>
    <command cmdref="next" 		cmdno="25"/>
    <command cmdref="pause"     	cmdno="89"/>
    <command cmdref="still_advance" cmdno="27"/>
    <command cmdref="stop" 		cmdno="30"/>

    <command cmdref="cmd_0" 		cmdno="73"/>
    <command cmdref="cmd_1" 		cmdno="19"/>
    <command cmdref="cmd_2" 		cmdno="16"/>
    <command cmdref="cmd_3" 		cmdno="17"/>
    <command cmdref="cmd_4" 		cmdno="15"/>
    <command cmdref="cmd_5" 		cmdno="12"/>
    <command cmdref="cmd_6" 		cmdno="13"/>
    <command cmdref="cmd_7" 		cmdno="11"/>
    <command cmdref="cmd_8" 		cmdno="8"/>
    <command cmdref="cmd_9" 		cmdno="9"/>
    <command cmdref="plus10"	cmdno="77"/>
    <command cmdref="clear" 	cmdno="81"/>

    <command cmdref="program"	cmdno="21"/>
    <command cmdref="repeat" 	cmdno="3"/>
    <command cmdref="a_b" 		cmdno="4"/>
    <command cmdref="intro"		cmdno="69"/>
    <command cmdref="zoom" 		cmdno="23"/>
    <command cmdref="effect_toggle"	cmdno="5"/>
    <command cmdref="marker" 	cmdno="85"/>
    <command cmdref="cmd_return" 	cmdno="10"/>
  </commandset>
</device>
