=== bengtmartensson/oldharctoolbox/dtds/devices.dtd
<!-- Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  This file is offered as-is,
     without any warranty.
-->

<!-- Presently, id's for devices are not supported -->

<!ELEMENT devices (device)+ >

<!ELEMENT device (description?,comment?,attributes?,aliases?,delays?,jp1data?,(commandset|xi:include)*) >
<!ATTLIST device
        xmlns:xi CDATA #IMPLIED
        id ID #REQUIRED
        name CDATA #REQUIRED
        vendor CDATA #IMPLIED
        vendorurl CDATA #IMPLIED
        model CDATA #REQUIRED
        pingable_on (yes|no) #IMPLIED
        pingable_standby (yes|no) #IMPLIED
        type     (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|camera|other|dumb|undefined) "undefined"
        alt_type (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|camera|other|dumb|undefined) "undefined" >

<!ELEMENT xi:include (xi:fallback?)>
<!ATTLIST xi:include
    xmlns:xi        CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
    href            CDATA       #IMPLIED
    parse           (xml|text)  "xml"
    xpointer        CDATA       #IMPLIED
    encoding        CDATA       #IMPLIED
    accept          CDATA       #IMPLIED
    accept-language CDATA       #IMPLIED
>

<!ELEMENT xi:fallback ANY>
<!ATTLIST xi:fallback
    xmlns:xi   CDATA   #FIXED   "http://www.w3.org/2001/XInclude"
>

<!ELEMENT delays (delay)* >

<!ELEMENT delay EMPTY >
<!ATTLIST delay
        type NMTOKEN #REQUIRED
        delay NMTOKEN #REQUIRED >

<!ELEMENT attributes (attribute)+ >

<!ELEMENT attribute EMPTY >
<!ATTLIST attribute
	name NMTOKEN #REQUIRED
	defaultvalue CDATA #IMPLIED >

<!ELEMENT aliases (alias+) >

<!ELEMENT alias EMPTY >
<!ATTLIST alias
	name NMTOKEN #REQUIRED
        command NMTOKEN #REQUIRED >

<!ELEMENT jp1data (setupcode|fixed_data)+ >

<!ELEMENT setupcode EMPTY >
<!ATTLIST setupcode
	value CDATA #REQUIRED >

<!ELEMENT fixed_data EMPTY >
<!ATTLIST fixed_data
	data CDATA #REQUIRED >

<!ELEMENT commandset (commandgroup|commandgroupref|command|xi:include)* >
<!ATTLIST commandset
        type (ir|rf433|rf868|www|web_api|tcp|udp|serial|bluetooth|on_off|ip|special|telnet|sensor) "ir"
        ifattribute CDATA #IMPLIED
        protocol NMTOKEN #IMPLIED
        prefix CDATA ""
        suffix CDATA ""
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        portnumber CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        subdevice CDATA #IMPLIED
        fixed_data CDATA #IMPLIED
        user CDATA #IMPLIED
        password CDATA #IMPLIED
        toggle (yes|no) "no"
        name CDATA #IMPLIED
        original_remote CDATA #IMPLIED
        remotename NMTOKEN #IMPLIED
        delay_between_chars CDATA "0"
 	pseudo_power_on NMTOKEN #IMPLIED
 	delay_between_reps CDATA "0"
 	remark CDATA #IMPLIED
        charset CDATA "utf-8" >

<!ELEMENT commandgroup (commandgroup|command)+ >
<!ATTLIST commandgroup
        id ID #IMPLIED
        name CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        description CDATA #IMPLIED >

<!ELEMENT commandgroupref EMPTY >
<!ATTLIST commandgroupref
        commandgroup IDREF #REQUIRED >

<!-- For now, there are no more than one argument accepted -->
<!ELEMENT command (ccf_cooked?,(toggle_pair|ccf)?,remark?,argument*,returnvalues?) >
<!ATTLIST command
        cmdref NMTOKEN #REQUIRED
        cmdno CDATA #IMPLIED
        name CDATA #IMPLIED
	zone (1|2|3|record) #IMPLIED
        type (discrete|toggle|cyclic) #IMPLIED
	remark CDATA #IMPLIED
        ifattribute CDATA #IMPLIED
        wakeup (yes|no) #IMPLIED
        transmit CDATA #IMPLIED
        expected_response CDATA #IMPLIED
        response_ending CDATA #IMPLIED
        returntype CDATA #IMPLIED
        returnwidth CDATA #IMPLIED
        returncontent CDATA #IMPLIED
        response_lines CDATA #IMPLIED >

<!ELEMENT returnvalues (syntax?,semantics?,description?) >

<!ELEMENT syntax (returntype*) >
<!ATTLIST syntax
	parse CDATA #IMPLIED >

<!ELEMENT semantics (table) >
<!ELEMENT returntype EMPTY >
<!ATTLIST returntype
	type (string|texttable|decimal_integer|hexadecimal_integer|hh:mm:ss|dd.mm.yyyy|tv_radio|0_1|on_off|percent|4:3_16:9|dbox_videoformat|dbox_videooutput) #REQUIRED
	length CDATA #IMPLIED >

<!ELEMENT table (entry+,default?) >
<!ATTLIST table
	index (string|number|hexnumber) "string" >

<!ELEMENT entry EMPTY >
<!ATTLIST entry
	value CDATA #REQUIRED
	desc CDATA "" >

<!ELEMENT default EMPTY >
<!ATTLIST default
	desc CDATA "" >

<!ELEMENT remark (#PCDATA) >

<!ELEMENT argument (description)? >
<!ATTLIST argument
        name CDATA #REQUIRED
        semantic CDATA #IMPLIED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT comment (#PCDATA) >

<!ELEMENT ccf (#PCDATA) >
<!ATTLIST ccf
	toggle (0|1) #IMPLIED >

<!ELEMENT toggle_pair (ccf, ccf) >

<!ELEMENT ccf_cooked (#PCDATA) >

=== bengtmartensson/oldharctoolbox/src/main/devices/mce_rc1974502_00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<!-- experimental -->
<device id="mce_rc1975502_00" name="MCE" vendor="Microsoft" model="" type="other">
  <commandset type="ir" protocol="mce" deviceno="4" subdevice="15"
    toggle="yes">
    <command cmdref="power_toggle"	 cmdno="12"/>

    <command cmdref="cmd_0"		 cmdno="0"/>
    <command cmdref="cmd_1"		 cmdno="1"/>
    <command cmdref="cmd_2"		 cmdno="2"/>
    <command cmdref="cmd_3"		 cmdno="3"/>
    <command cmdref="cmd_4"		 cmdno="4"/>
    <command cmdref="cmd_5"		 cmdno="5"/>
    <command cmdref="cmd_6"		 cmdno="6"/>
    <command cmdref="cmd_7"		 cmdno="7"/>
    <command cmdref="cmd_8"		 cmdno="8"/>
    <command cmdref="cmd_9"		 cmdno="9"/>
    <command cmdref="star"	 	cmdno="29"/>
    <command cmdref="hash"	 	cmdno="28"/>

    <command cmdref="tv_mode"		 cmdno="72"/>
    <command cmdref="picture_mode"	 cmdno="38"/>
    <command cmdref="movie_mode"	 cmdno="37"/>
    <command cmdref="music_mode"	 cmdno="36"/>

    <command cmdref="clear"		 cmdno="10"/>
    <command cmdref="teletext"  	 cmdno="90"/>
    <command cmdref="select"		 cmdno="11"/>

    <command cmdref="up"		 cmdno="30"/>
    <command cmdref="left"		 cmdno="32"/>
    <command cmdref="ok"		 cmdno="34"/>
    <command cmdref="left"		 cmdno="33"/>
    <command cmdref="down"		 cmdno="31"/>

    <command cmdref="volume_up"		 cmdno="16"/>
    <command cmdref="volume_down"	 cmdno="17"/>
    <command cmdref="mute"      	 cmdno="14"/>
    <command cmdref="channel_up"	 cmdno="18"/>
    <command cmdref="channel_down"	 cmdno="19"/>

    <command cmdref="record"    	 cmdno="23"/>
    <command cmdref="pause"     	 cmdno="24"/>
    <command cmdref="stop"		 cmdno="25"/>
    <command cmdref="rewind"		 cmdno="21"/>
    <command cmdref="play"		 cmdno="22"/>
    <command cmdref="fast_forward"	 cmdno="20"/>
    <command cmdref="previous"		 cmdno="27"/>
    <command cmdref="next"		 cmdno="26"/>
    <command cmdref="mce"		 cmdno="13"/>
    <command cmdref="cmd_return"	 cmdno="35"/>
    <command cmdref="info"		 cmdno="15"/>

    <command cmdref="red"		 cmdno="91"/>
    <command cmdref="green"		 cmdno="92"/>
    <command cmdref="yellow"		 cmdno="93"/>
    <command cmdref="blue"		 cmdno="94"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/src/main/devices/lg_vcr_lv979.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="lg_vcr_xxx" name="LG VCR xxx" vendor="LG" model="VCR xxx" type="vcr">
  <commandset type="ir" deviceno="0" remotename="lg_vcr">
    <command cmdref="cmd_0" 				cmdno="0"/>
    <command cmdref="cmd_1" 				cmdno="1"/>
    <command cmdref="cmd_2" 				cmdno="2"/>
    <command cmdref="cmd_3" 				cmdno="3"/>
    <command cmdref="cmd_4" 				cmdno="4"/>
    <command cmdref="cmd_5" 				cmdno="5"/>
    <command cmdref="cmd_6" 				cmdno="6"/>
    <command cmdref="cmd_7" 				cmdno="7"/>
    <command cmdref="cmd_8" 				cmdno="8"/>
    <command cmdref="cmd_9" 				cmdno="9"/>
    <command cmdref="power_toggle" name="power"		cmdno="12"/>
    <command cmdref="tv_mode"				cmdno="63"/>
    <command cmdref="vcr_tv" 				cmdno="62"/>
    <command cmdref="previous" 				cmdno="37"/>
    <command cmdref="next" 				cmdno="38"/>
    <command cmdref="still_advance" 			cmdno="41"/>
    <command cmdref="open" 				cmdno="45"/>
    <command cmdref="clear" 				cmdno="49"/>
    <command cmdref="play" 				cmdno="53"/>
    <command cmdref="rewind" 				cmdno="50"/>
    <command cmdref="fast_forward" 			cmdno="52"/>
    <command cmdref="stop" 				cmdno="54"/>
    <command cmdref="channel_up" 			cmdno="32"/>
    <command cmdref="channel_down" 			cmdno="33"/>
    <command cmdref="record"    			cmdno="55"/>
    <command cmdref="info" 				cmdno="15"/>
    <command cmdref="smart_picture" 			cmdno="70"/>
    <command cmdref="ok" 				cmdno="87"/>
    <command cmdref="skip_search" 			cmdno="106"/>
    <command cmdref="rec_end_search" 			cmdno="117"/>
    <command cmdref="menu" 				cmdno="82"/>
    <command cmdref="timer" 				cmdno="69"/>
    <command cmdref="turbo_timer" 			cmdno="28"/>
    <command cmdref="lp_sp" 				cmdno="58"/>
    <command cmdref="I_II" 				cmdno="35"/>
    <command cmdref="standby_toggle"			cmdno="6"/>
<!--
  [power_toggle][T]0[D]S011101101000100100101000110101110
  [tv_vcr][T]0[D]S011101101000100110101000010101110
  [av][T]0[D]S011101101000100101101010100101010
  [open][T]0[D]S011101101000100100000000111111110
  [1][T]0[D]S011101101000100110100000010111110
  [2][T]0[D]S011101101000100101100000100111110
  [3][T]0[D]S011101101000100111100000000111110
  [c_lock][T]0[D]S011101101000100111111100000000110
  [4][T]0[D]S011101101000100100110000110011110
  [5][T]0[D]S011101101000100110110000010011110
  [6][T]0[D]S011101101000100101110000100011110
  [power_off][T]0[D]S011101101000100100011101111000100
  [7][T]0[D]S011101101000100111110000000011110
  [8][T]0[D]S011101101000100100111000110001110
  [9][T]0[D]S011101101000100110111000010001110
  [repeat][T]0[D]S011101101000100101101101100100100
  [cm_skip][T]0[D]S011101101000100110111011010001000
  [0][T]0[D]S011101101000100100100000110111110
  [lp][T]0[D]S011101101000100100010010111011010
  [info][T]0[D]S011101101000100101101000100101110
  [record][T]0[D]S011101101000100110010000011011110
  [play][T]0[D]S011101101000100100010000111011110
  [rewind][T]0[D]S011101101000100101000000101111110
  [pause][T]0[D]S011101101000100111010000001011110
  [ff][T]0[D]S011101101000100111000000001111110
  [ok][T]0[D]S011101101000100101110001100011100
  [stop][T]0[D]S011101101000100110000000011111110
  [up][T]0[D]S011101101000100101000001101111100
  [clear][T]0[D]S011101101000100111111000000001110
  [left][T]0[D]S011101101000100111000001001111100
  [reight][T]0[D]S011101101000100100001001111101100
  [down][T]0[D]S011101101000100110010001011011100
  [showview][T]0[D]S011101101000100111100010000111010
 -->
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/devices/toshiba_hd-ep30.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="toshiba_hd-ep30" name="Toshiba HD EP30" model="ep30" type="dvd"  pingable_on="yes" pingable_standby="no">
  <jp1data>
    <setupcode value="1069"/>
  </jp1data>
  <commandset type="ir" protocol="nec1" deviceno="69" subdevice="181" original_remote="SE-R0288" remotename="toshiba_hd-ep30">
    <!--    Manual:,,0 = 1-byte,LSB-COMP,88,NO,,,,,,, -->
    <command cmdref="cmd_0" cmdno="10"/>
    <command cmdref="cmd_1" cmdno="1" remark="requires OK to select tracks"/>
    <command cmdref="cmd_2" cmdno="2"/>
    <command cmdref="cmd_3" cmdno="3"/>
    <command cmdref="cmd_4" cmdno="4"/>
    <command cmdref="cmd_5" cmdno="5"/>
    <command cmdref="cmd_6" cmdno="6"/>
    <command cmdref="cmd_7" cmdno="7"/>
    <command cmdref="cmd_8" cmdno="8"/>
    <command cmdref="cmd_9" cmdno="9"/>
    <command cmdref="cmd_plus10" cmdno="37"/>
    <command cmdref="clear" cmdno="239"/>
    <command cmdref="title_search" cmdno="38"/><!-- ??? -->
    <command cmdref="up" cmdno="128"/>
    <command cmdref="down" cmdno="129"/>
    <command cmdref="left" cmdno="81"/>
    <command cmdref="right" cmdno="77"/>
    <command cmdref="ok" cmdno="33"/>
    <command cmdref="pause_toggle" cmdno="0"/>
    <command cmdref="play" wakeup="yes" cmdno="21"/>
    <command cmdref="stop" cmdno="20"/>
    <command cmdref="rewind" cmdno="25"/>
    <command cmdref="fast_forward" cmdno="19"/>
    <command cmdref="previous" cmdno="35"/>
    <command cmdref="next" cmdno="36"/>
    <!--command cmdref="resume" cmdno="56"/--> <!-- resume (return f/ menu) ??? -->
    <command cmdref="return" cmdno="34"/>
    <command cmdref="repeat" cmdno="43"/>
    <!--command cmdref="tab" cmdno="50"/--> <!-- ??? -->
    <!--command cmdref="cursor" cmdno="51"/--> <!-- ??? -->
    <command cmdref="slow" cmdno="13"/>
    <command cmdref="A" cmdno="52"/>
    <command cmdref="B" cmdno="53"/>
    <command cmdref="C" cmdno="54"/>
    <command cmdref="D" cmdno="55"/>
    <command cmdref="audio" cmdno="39"/>
    <command cmdref="subtitle" cmdno="40"/>
    <command cmdref="angle" cmdno="41"/>
    <command cmdref="dvd_menu" cmdno="132"/>
    <command cmdref="title" cmdno="222"/>
    <command cmdref="setup" cmdno="32"/>
    <!--command cmdref="video_output_HDMI" cmdno="159"/--><!-- ??? -->
    <command cmdref="cmd_resolution" cmdno="78"/> <!--  (I/P selector -->
    <command cmdref="display" cmdno="22"/>
    <command cmdref="dimmer" cmdno="65"/>
    <command cmdref="open_close" wakeup="yes" cmdno="245"/>
    <command cmdref="power_toggle" cmdno="18"/>
    <!--command cmdref="power_on" cmdno="146"/--><!-- not working -->
    <command cmdref="power_on" cmdno="254"/><!-- self discovered -->
    <command cmdref="power_off" cmdno="147"/><!-- ok -->
    <command cmdref="tray_lock_toggle" cmdno="202"/>
    <command cmdref="factory_reset" cmdno="205"/><!-- or 206? not tested -->
    <!--command cmdref="display_time" cmdno="203"/-->
    <!--command cmdref="display_firmware_ver" cmdno="195"/-->
    <command cmdref="up_right" cmdno="130"/>
    <command cmdref="down_right" cmdno="131"/>
    <command cmdref="up_left" cmdno="134"/>
    <command cmdref="down_left" cmdno="133"/>
    <command cmdref="cancel" cmdno="27"/>
    <command cmdref="resolution" cmdno="196"/><!-- ?? not work? -->
    <command cmdref="test_mode" cmdno="197"/><!-- not work -->
    <command cmdref="time" cmdno="203"/><!-- not work -->
    <command cmdref="firmware_version" cmdno="207"/><!-- not work -->
    <!--command cmdref="door" cmdno="73"/--> <!-- ??? -->
    <!-- 252: beep -->
    <!-- 
    DiscreteON,47 - discrete on
    DiscreteOFF,48 - discrete off
    -->
    <!--
Line Notes:
These codes were created for the Toshiba HD-A1/XA1 HD-DVD player.
All original functions of OEM remote are included, including
some extra functions not on the original remote.

Following functions *not* included on the OEM have been added:

discrete on (discrete off available but not tested)
tray lock/unlock
factory reset
display time
display firmware ver

Full set of function codes (OBC) from Toshiba can be found here
http://www.remotecentral.com/cgi-bin/mboard/rc-touch/thread.cgi?1160

Questions - PM sfhub at http://www.avsforum.com/

Rev 1.1 Added functions from Toshiba HD-XA1 RS232 list, but not tested
up-right, down-right, up-left, down-left, tab, cancel, door, discrete off

Thread: http://www.avsforum.com/avs-vb/showthread.php?t=940909

Here's how to get the above screen with the Tosh remote:

Display - 1 -9 - 5 - Display
    -->
  </commandset>
  <commandset type="ip">
    <command cmdref="ping"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/src/main/devices/philips_vr1100.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="philips_vr1100" name="Philips VCR VR1100" vendor="Philips" model="VR1100" type="vcr">
  <!-- Discrete commands for power on/off and inputs not known -->
  <jp1data>
    <setupcode value="1081"/>
  </jp1data>
  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="5" remotename="philips_vr1100">
    <command cmdref="cmd_0" 				cmdno="0"/>
    <command cmdref="cmd_1" 				cmdno="1"/>
    <command cmdref="cmd_2" 				cmdno="2"/>
    <command cmdref="cmd_3" 				cmdno="3"/>
    <command cmdref="cmd_4" 				cmdno="4"/>
    <command cmdref="cmd_5" 				cmdno="5"/>
    <command cmdref="cmd_6" 				cmdno="6"/>
    <command cmdref="cmd_7" 				cmdno="7"/>
    <command cmdref="cmd_8" 				cmdno="8"/>
    <command cmdref="cmd_9" 				cmdno="9"/>
    <command cmdref="power_toggle" name="power"		cmdno="12"/>
    <!--command cmdref="power_toggle" name="power"		cmdno="76"/-->
    <command cmdref="in_tv"				cmdno="63"/>
    <command cmdref="vcr_tv" 				cmdno="62"/>
    <command cmdref="previous" 				cmdno="37"/>
    <command cmdref="next" 				cmdno="38"/>
    <command cmdref="still_advance" 			cmdno="41"/>
    <command cmdref="open"		   wakeup="yes" cmdno="45"/>
    <command cmdref="clear" 				cmdno="49"/>
    <command cmdref="play" 				cmdno="53"/>
    <command cmdref="rewind" 				cmdno="50"/>
    <command cmdref="fast_forward" 			cmdno="52"/>
    <command cmdref="stop" 				cmdno="54"/>
    <command cmdref="channel_up" 			cmdno="32"/>
    <command cmdref="channel_down" 			cmdno="33"/>
    <command cmdref="record"    			cmdno="55"/>
    <command cmdref="info" 				cmdno="15"/>
    <command cmdref="smart_picture" 			cmdno="70"/>
    <command cmdref="ok" 				cmdno="87"/>
    <command cmdref="skip_search" 			cmdno="106"/>
    <command cmdref="rec_end_search" 			cmdno="117"/>
    <command cmdref="menu" 				cmdno="82"/>
    <command cmdref="timer" 				cmdno="69"/>
    <command cmdref="turbo_timer" 			cmdno="28"/>
    <command cmdref="lp_sp" 				cmdno="58"/>
    <command cmdref="I_II" 				cmdno="35"/>
    <command cmdref="standby_toggle"	 		cmdno="61"/>

    <!-- power_on = standby + power_toggle -->
    <!-- power_off = standby + standby -->
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/release-0.7.0/devices/coolstream_neo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device xmlns:xi="http://www.w3.org/2001/XInclude" id="coolstream_neo" name="coolstream_neo" vendor="Coolstream" model="neo" type="sat"
    alt_type="cable" pingable_on="yes" pingable_standby="no"> 
  <!-- answers ping in non-deep standby -->
  <jp1data>
    <setupcode value="999"/>
  </jp1data>
  <xi:include href="tuxbox_webapi.xi">
    <xi:fallback/>
  </xi:include>
  <xi:include href="coolstream_ir.xi">
    <xi:fallback/>
  </xi:include>
  <xi:include href="ping.xi"/>
  <xi:include href="www.xi"/>
</device>

=== bengtmartensson/oldharctoolbox/src/main/devices/rc5_tv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="rc5_tv" name="Canonical RC5 TV" vendor="" model="" type="tv">
    <commandset type="ir" protocol="rc5" deviceno="0" remotename="rc5_tv" toggle="yes">
      <command cmdref="cmd_0" 				cmdno="0"/>
      <command cmdref="cmd_1" 				cmdno="1"/>
      <command cmdref="cmd_2" 				cmdno="2"/>
      <command cmdref="cmd_3" 				cmdno="3"/>
      <command cmdref="cmd_4" 				cmdno="4"/>
      <command cmdref="cmd_5" 				cmdno="5"/>
      <command cmdref="cmd_6" 				cmdno="6"/>
      <command cmdref="cmd_7" 				cmdno="7"/>
      <command cmdref="cmd_8" 				cmdno="8"/>
      <command cmdref="cmd_9" 				cmdno="9"/>
      <command cmdref="power_toggle" 		cmdno="12"/>
      <command cmdref="in_tv"			cmdno="63"/>
      <command cmdref="channel_up" 			cmdno="32"/>
      <command cmdref="channel_down" 		cmdno="33"/>
      <command cmdref="mute_toggle" 		cmdno="13"/>
      <command cmdref="last_channel" 		cmdno="34"/>
      <command cmdref="volume_up" 			cmdno="16"/>
      <command cmdref="volume_down" 		cmdno="17"/>
      <command cmdref="PP" 				cmdno="14"/>
      <command cmdref="info" 			cmdno="15"/>
      <command cmdref="brightness_down" 		cmdno="19"/>
      <command cmdref="brightness_up" 		cmdno="18"/>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/src/main/devices/asus_oplay_hdp-r1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="asus_oplay_hdp-r1" name="ASUS O!Play HDP-R1" vendor="asus"
  model="oplay_hdp-r1" type="misc_audio" pingable_on="yes" pingable_standby="no">
  <jp1data>
    <setupcode value="1324"/>
  </jp1data>
  <commandset type="ir" protocol="nec1" deviceno="108" subdevice="104" remotename="asus_oplay">
    <command cmdref="power_toggle"	cmdno="86"/>
    <command cmdref="display"		cmdno="84"/>
    <command cmdref="rewind"		cmdno="65" remark="set speed backwards"/>
    <command cmdref="play_pause"	cmdno="24"/>
    <command cmdref="fast_forward"	cmdno="23" remark="set speed forwards"/>
    <command cmdref="previous"		cmdno="25"/>
    <command cmdref="stop"		cmdno="4"/>
    <command cmdref="next"		cmdno="19"/>
    <command cmdref="home"		cmdno="64"/>
    <command cmdref="cmd_return"	cmdno="68"/>
    <command cmdref="up"		cmdno="94"/>
    <command cmdref="left"		cmdno="88"/>
    <command cmdref="ok"		cmdno="93"/>
    <command cmdref="right"		cmdno="95"/>  
    <command cmdref="down"		cmdno="92"/>
    <command cmdref="volume_up"		cmdno="27"/>
    <command cmdref="setup"		cmdno="69"/>
    <command cmdref="volume_down"	cmdno="76"/>
    <command cmdref="shuffle"		cmdno="5"/>
    <command cmdref="mode"		cmdno="73" type="cyclic"/>
    <command cmdref="subtitle"		cmdno="91"/>
    <command cmdref="zoom"		cmdno="66"/>
    <command cmdref="audio"		cmdno="87"/> 
    <command cmdref="repeat"		cmdno="90"/>
  </commandset>
  <commandset type="telnet" portnumber="23" user="root" password="none"/>
  <xi:include href="www.xi"/> <!-- really just dummy -->
  <!--xi:include href="wol.xi"/-->
  <xi:include href="ping.xi"/>
</device>

=== bengtmartensson/oldharctoolbox/src/main/devices/samsung_bdp1400.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="samsung_bdp1400" name="Samsung BD-P1400" vendor="Samsung"
  model="BD-P1400" type="dvd" pingable_on="yes" pingable_standby="no">
  <jp1data>
    <setupcode value="0199"/>
<!--
Protocol=00 B5
Protocol.name=Manual Settings
ProtocolParms=4 0 224
FixedData=04 00 E0
DevParms=Device 1\=0,Device 2\=0,Device 3\=0
DeviceTranslator=Translator(0) Translator(1,8,8) Translator(2,8,16)
CmdParms=OBC
CmdTranslator=Translator(0)
DefaultCmd=00
CmdIndex=0
FixedData=04 00 E0
-->
  </jp1data>
  <commandset type="ir" protocol="samsung36" deviceno="32" remotename="samsung_bdp1400" original_remote="00070B" pseudo_power_on="play_pause">
    <command cmdref="cmd_0" 				cmdno="0xD0"/>
    <command cmdref="cmd_1" 				cmdno="0x40"/>
    <command cmdref="cmd_2" 				cmdno="0xC0"/>
    <command cmdref="cmd_3" 				cmdno="0x20"/>
    <command cmdref="cmd_4" 				cmdno="0xA0"/>
    <command cmdref="cmd_5" 				cmdno="0x60"/>
    <command cmdref="cmd_6" 				cmdno="0xE0"/>
    <command cmdref="cmd_7" 				cmdno="0x10"/>
    <command cmdref="cmd_8" 				cmdno="0x90"/>
    <command cmdref="cmd_9" 				cmdno="0x50"/>
    <command cmdref="next" 				cmdno="0x88"/>
    <command cmdref="a_b" 				cmdno="0x14"/>
    <command cmdref="audio" 				cmdno="0xA4"/>
    <command cmdref="yellow" 				cmdno="0xC4"/>
    <command cmdref="home" name="exit"			cmdno="0xD4"/><!-- ??? -->
    <command cmdref="open_close" name="open/close" 	wakeup="yes" cmdno="0x80"/>
    <command cmdref="slow_reverse" 			cmdno="0xF0"/>
    <command cmdref="repeat" 				cmdno="0xE4"/>
    <command cmdref="slow_forward" 			cmdno="0x08"/>
    <command cmdref="marker" 				cmdno="0x94"/>
    <command cmdref="power_toggle" wakeup="yes"		cmdno="0x00"/>
    <command cmdref="play_pause" name="play/pause" wakeup="yes" cmdno="0x28"/>
    <command cmdref="rewind" 				cmdno="0x48"/>
    <command cmdref="fast_forward"			cmdno="0xA8"/>
    <command cmdref="stop" 				cmdno="0xC8"/>
    <command cmdref="ok" 				cmdno="0x38"/>
    <command cmdref="title" name="disc_menu"		cmdno="0xB8"/>
    <command cmdref="up" 				cmdno="0x18"/>
    <command cmdref="down" 				cmdno="0x98"/>
    <command cmdref="left" 				cmdno="0xD8"/>
    <command cmdref="right" 				cmdno="0x58"/>
    <command cmdref="info" 				cmdno="0x78"/>
    <command cmdref="cmd_return" 			cmdno="0xE8"/>
    <command cmdref="previous" 				cmdno="0xB0"/>
    <command cmdref="dvd_menu" 				cmdno="0x68"/>
    <command cmdref="subtitle" 				cmdno="0x64"/>
    <command cmdref="zoom" 				cmdno="0x54"/>
    <command cmdref="slow" 				cmdno="0x70"/>
    <command cmdref="cancel" 				cmdno="0xF8"/>
    <command cmdref="scene_search" 			cmdno="0x30"/>
    <command cmdref="menu" name="popup menu"		cmdno="0x04"/>
    <command cmdref="red" 				cmdno="0x84"/>
    <command cmdref="green" 				cmdno="0x44"/>
    <command cmdref="blue" 				cmdno="0x24"/>
  </commandset>
  <commandset type="ip">
    <command cmdref="ping"/>
  </commandset>
</device>
