=== bengtmartensson/oldharctoolbox/dtds/devices.dtd
<!-- Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  This file is offered as-is,
     without any warranty.
-->

<!-- Presently, id's for devices are not supported -->

<!ELEMENT devices (device)+ >

<!ELEMENT device (description?,comment?,attributes?,aliases?,delays?,jp1data?,(commandset|xi:include)*) >
<!ATTLIST device
        xmlns:xi CDATA #IMPLIED
        id ID #REQUIRED
        name CDATA #REQUIRED
        vendor CDATA #IMPLIED
        vendorurl CDATA #IMPLIED
        model CDATA #REQUIRED
        pingable_on (yes|no) #IMPLIED
        pingable_standby (yes|no) #IMPLIED
        type     (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|camera|other|dumb|undefined) "undefined"
        alt_type (amplifier|receiver|projector|tv|vcr|cd|dvd|ha|sat|cable|ld|tape|misc_audio|camera|other|dumb|undefined) "undefined" >

<!ELEMENT xi:include (xi:fallback?)>
<!ATTLIST xi:include
    xmlns:xi        CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
    href            CDATA       #IMPLIED
    parse           (xml|text)  "xml"
    xpointer        CDATA       #IMPLIED
    encoding        CDATA       #IMPLIED
    accept          CDATA       #IMPLIED
    accept-language CDATA       #IMPLIED
>

<!ELEMENT xi:fallback ANY>
<!ATTLIST xi:fallback
    xmlns:xi   CDATA   #FIXED   "http://www.w3.org/2001/XInclude"
>

<!ELEMENT delays (delay)* >

<!ELEMENT delay EMPTY >
<!ATTLIST delay
        type NMTOKEN #REQUIRED
        delay NMTOKEN #REQUIRED >

<!ELEMENT attributes (attribute)+ >

<!ELEMENT attribute EMPTY >
<!ATTLIST attribute
	name NMTOKEN #REQUIRED
	defaultvalue CDATA #IMPLIED >

<!ELEMENT aliases (alias+) >

<!ELEMENT alias EMPTY >
<!ATTLIST alias
	name NMTOKEN #REQUIRED
        command NMTOKEN #REQUIRED >

<!ELEMENT jp1data (setupcode|fixed_data)+ >

<!ELEMENT setupcode EMPTY >
<!ATTLIST setupcode
	value CDATA #REQUIRED >

<!ELEMENT fixed_data EMPTY >
<!ATTLIST fixed_data
	data CDATA #REQUIRED >

<!ELEMENT commandset (commandgroup|commandgroupref|command|xi:include)* >
<!ATTLIST commandset
        type (ir|rf433|rf868|www|web_api|tcp|udp|serial|bluetooth|on_off|ip|special|telnet|sensor) "ir"
        ifattribute CDATA #IMPLIED
        protocol NMTOKEN #IMPLIED
        prefix CDATA ""
        suffix CDATA ""
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        portnumber CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        subdevice CDATA #IMPLIED
        fixed_data CDATA #IMPLIED
        user CDATA #IMPLIED
        password CDATA #IMPLIED
        toggle (yes|no) "no"
        name CDATA #IMPLIED
        original_remote CDATA #IMPLIED
        remotename NMTOKEN #IMPLIED
        delay_between_chars CDATA "0"
 	pseudo_power_on NMTOKEN #IMPLIED
 	delay_between_reps CDATA "0"
 	remark CDATA #IMPLIED
        charset CDATA "utf-8" >

<!ELEMENT commandgroup (commandgroup|command)+ >
<!ATTLIST commandgroup
        id ID #IMPLIED
        name CDATA #IMPLIED
        deviceno CDATA #IMPLIED
        description CDATA #IMPLIED >

<!ELEMENT commandgroupref EMPTY >
<!ATTLIST commandgroupref
        commandgroup IDREF #REQUIRED >

<!-- For now, there are no more than one argument accepted -->
<!ELEMENT command (ccf_cooked?,(toggle_pair|ccf)?,remark?,argument*,returnvalues?) >
<!ATTLIST command
        cmdref NMTOKEN #REQUIRED
        cmdno CDATA #IMPLIED
        name CDATA #IMPLIED
	zone (1|2|3|record) #IMPLIED
        type (discrete|toggle|cyclic) #IMPLIED
	remark CDATA #IMPLIED
        ifattribute CDATA #IMPLIED
        wakeup (yes|no) #IMPLIED
        transmit CDATA #IMPLIED
        expected_response CDATA #IMPLIED
        response_ending CDATA #IMPLIED
        returntype CDATA #IMPLIED
        returnwidth CDATA #IMPLIED
        returncontent CDATA #IMPLIED
        response_lines CDATA #IMPLIED >

<!ELEMENT returnvalues (syntax?,semantics?,description?) >

<!ELEMENT syntax (returntype*) >
<!ATTLIST syntax
	parse CDATA #IMPLIED >

<!ELEMENT semantics (table) >
<!ELEMENT returntype EMPTY >
<!ATTLIST returntype
	type (string|texttable|decimal_integer|hexadecimal_integer|hh:mm:ss|dd.mm.yyyy|tv_radio|0_1|on_off|percent|4:3_16:9|dbox_videoformat|dbox_videooutput) #REQUIRED
	length CDATA #IMPLIED >

<!ELEMENT table (entry+,default?) >
<!ATTLIST table
	index (string|number|hexnumber) "string" >

<!ELEMENT entry EMPTY >
<!ATTLIST entry
	value CDATA #REQUIRED
	desc CDATA "" >

<!ELEMENT default EMPTY >
<!ATTLIST default
	desc CDATA "" >

<!ELEMENT remark (#PCDATA) >

<!ELEMENT argument (description)? >
<!ATTLIST argument
        name CDATA #REQUIRED
        semantic CDATA #IMPLIED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT comment (#PCDATA) >

<!ELEMENT ccf (#PCDATA) >
<!ATTLIST ccf
	toggle (0|1) #IMPLIED >

<!ELEMENT toggle_pair (ccf, ccf) >

<!ELEMENT ccf_cooked (#PCDATA) >

=== bengtmartensson/oldharctoolbox/src/main/devices/philips_28ml8805.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="philips_28ml8805" name="Philips TV 28ML8805" vendor="Philips" model="28ML8805" type="tv">
  <jp1data>
    <setupcode value="1234"/>
  </jp1data>
  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="0"
    remotename="philips_28ml8805">
    <command cmdref="cmd_0" 				cmdno="0"/>
    <command cmdref="cmd_1" 				cmdno="1"/>
    <command cmdref="cmd_2" 				cmdno="2"/>
    <command cmdref="cmd_3" 				cmdno="3"/>
    <command cmdref="cmd_4" 				cmdno="4"/>
    <command cmdref="cmd_5" 				cmdno="5"/>
    <command cmdref="cmd_6" 				cmdno="6"/>
    <command cmdref="cmd_7" 				cmdno="7"/>
    <command cmdref="cmd_8" 				cmdno="8"/>
    <command cmdref="cmd_9" 				cmdno="9"/>
    <command cmdref="power_toggle" name="power"         cmdno="12"/>
    <command cmdref="tv_mode"			cmdno="63"/>
    <command cmdref="channel_up" 			cmdno="32"/>
    <command cmdref="channel_down" 			cmdno="33"/>
    <command cmdref="mute"      name="mute"     	cmdno="13"/>
    <command cmdref="last_channel" 			cmdno="34"/>
    <command cmdref="volume_up" 			cmdno="16"/>
    <command cmdref="volume_down" 			cmdno="17"/>
    <command cmdref="PP" 				cmdno="14"/>
    <command cmdref="info" 				cmdno="15"/>
    <command cmdref="brightness_down" 		cmdno="19"/>
    <command cmdref="brightness_up" 		cmdno="18"/>
    <command cmdref="aspectratio"	 		cmdno="126"/>
    <command cmdref="menu" 				cmdno="82"/>
    <command cmdref="up" 				cmdno="80"/>
    <command cmdref="down" 				cmdno="81"/>
    <command cmdref="red" 				cmdno="107"/>
    <command cmdref="green" 			cmdno="108"/>
    <command cmdref="yellow" 			cmdno="109"/>
    <command cmdref="blue" 				cmdno="110"/>
    <command cmdref="white" 			cmdno="111"/>
    <command cmdref="menu_off" 			cmdno="83"/>
    <command cmdref="I_II" 				cmdno="35"/>
    <command cmdref="teletext"   			cmdno="60"/>
    <command cmdref="teletext_freeze" 		cmdno="41"/>
    <command cmdref="teletext_reveal" 		cmdno="44"/>
    <command cmdref="teletext_hide" 		cmdno="45"/>
    <command cmdref="teletext_translucent" 		cmdno="46"/>
    <command cmdref="teletext_doubleheight" 	cmdno="43"/>
    <command cmdref="teletext_time" 		cmdno="42"/>
    <command cmdref="PIP" 				cmdno="88"/>
    <command cmdref="PIP_source" 			cmdno="95"/>
    <command cmdref="PIP_exchange" 			cmdno="90"/>
    <command cmdref="PIP_freeze" 			cmdno="101"/>
    <command cmdref="PIP_position" 			cmdno="89"/>
    <command cmdref="PIP_channel_down" 			cmdno="103"/>
    <command cmdref="PIP_channel_up" 			cmdno="102"/>
    <command cmdref="freeze"    			cmdno="93"/>
    <command cmdref="DNR" 				cmdno="97"/>
    <command cmdref="special" 			cmdno="94"/>
  </commandset>

  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="12"
    remotename="philips_28ml8805" pseudo_power_on="in_aux">
    <command cmdref="in_aux"		 	cmdno="63"/>
  </commandset>
  <commandset type="ir" protocol="rc5" toggle="yes" deviceno="5" remotename="philips_28ml8805">
    <command cmdref="in_vcr"			cmdno="63"/>
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/src/main/devices/pioneer_dvd525.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<devices>
  <device id="pioneer_dvd525" name="Pioneer DVD 525" vendor="Pioneer" model="DVD525" type="dvd">
    <commandset type="ir" toggle="no" deviceno="0" remotename="pioneer_dvd525">
<!--
stop		F1 Q 000 R 1110 S L
pause		F1 Q 111 R 0000 S L
prev		F1 Q 101 R 0100 S L
next		F1 Q 001 R 1100 S L
play		F1 Q 011 R 1000 S L
power_toggle	F2 Q 100 R 0110 S L A B T 0011110111000010L
open		F2 Q 100 R 0110 S L A B T 0110110110010010L
rewind		F1 Q 110 R 0010 S L
fast_forward	F1 Q 010 R 1010 S L
step_forward	F2 Q 100 R 0110 S L A B T 1110110100010010L
step_back	F2 Q 100 R 0110 S L A B T 0001110111100010L
up		F2 Q 100 R 0110 S L A B T 0100111110110000L
down		F2 Q 100 R 0110 S L A B T 1100111100110000L
left		F2 Q 100 R 0110 S L A B T 1100011000111001L
OK		F2 Q 100 R 0110 S L A B T 1111011100001000L
top		F2 Q 100 R 0110 S L A B T 0010110111010010L
return		F2 Q 100 R 0110 S L A B T 0010111111010000L
menu		F2 Q 100 R 0110 S L A B T 1001110101100010L
setup		F2 Q 100 R 0110 S L A B T 0000110111110010L
right		F2 Q 100 R 0110 S L A B T 0010011011011001L
1		F2 Q 100 R 0110 S L A B T 1000010101111010L
2		F2 Q 100 R 0110 S L A B T 0100010110111010L
3		F2 Q 100 R 0110 S L A B T 1100010100111010L
4		F2 Q 100 R 0110 S L A B T 0010010111011010L
5		F2 Q 100 R 0110 S L A B T 1010010101011010L
6		F2 Q 100 R 0110 S L A B T 0110010110011010L
7		F2 Q 100 R 0110 S L A B T 1110010100011010L
8		F2 Q 100 R 0110 S L A B T 0001010111101010L
9		F2 Q 100 R 0110 S L A B T 1001010101101010L
0		F2 Q 100 R 0110 S L A B T 0000010111111010L
???		F2 Q 100 R 0110 S L A B T 1010011101011000L
display		F2 Q 100 R 0110 S L A B T 1100011100111000L
two_dig 	F2 Q 100 R 0110 S L A B T 1111110100000010L
search mode	F2 Q 100 R 0110 S L A B T 1100110100110010L
vnr		F2 Q 100 R 0110 S L A B T 0000110011110011L
cond memory	F2 Q 100 R 0110 S L A B T 1000110101110010L
last memory	F2 Q 100 R 0110 S L A B T 0110111110010000L
subtitles	F2 Q 100 R 0110 S L A B T 0110110010010011L
angle		F2 Q 100 R 0110 S L A B T 1010110101010010L
audio		F2 Q 100 R 0110 S L A B T 0111110110000010L
random		F2 Q 100 R 0110 S L A B T 0111111110000000L
repeat		F2 Q 100 R 0110 S L A B T 0010011111011000L
program		F2 Q 100 R 0110 S L A B T 0011011111001000L
A-B		F2 Q 100 R 0110 S L A B T 0001011111101000L
power_on	F3 Q 100 R 0110 S L A B T 0101110110100010L
power_off	F3 Q 100 R 0110 S L A B T 1101110100100010L
-->
      <command cmdref="cmd_0"                   cmdno="0x98"/>
      <command cmdref="cmd_1"                   cmdno="0x08"/>
      <command cmdref="cmd_2"                   cmdno="0x88"/>
      <command cmdref="cmd_3"                   cmdno="0x48"/>
      <command cmdref="cmd_4"                   cmdno="0xc8"/>
      <command cmdref="cmd_5"                   cmdno="0x28"/>
      <command cmdref="cmd_6"                   cmdno="0xa8"/>
      <command cmdref="cmd_7"                   cmdno="0x68"/>
      <command cmdref="cmd_8"                   cmdno="0xe8"/>
      <command cmdref="cmd_9"                   cmdno="0x18"/>
      <command cmdref="a_b"                 cmdno="0x12"/>
      <command cmdref="a_srd"               cmdno="0x79"/>
      <command cmdref="angle"               cmdno="0x09"/>
      <command cmdref="audio"               cmdno="0xcc"/>
      <command cmdref="audio_only" 		cmdno="0x87"/>
      <command cmdref="clear" name="cancel"	cmdno="0xc1"/>
      <command cmdref="depth_enh"           cmdno="0x1b"/>
      <command cmdref="display"             cmdno="0x49"/>
      <command cmdref="double_remaster"	cmdno="0x97"/>
      <command cmdref="down" 		cmdno="0x61"/>
      <command cmdref="fast_forward" 	cmdno="0xa0"/>
      <command cmdref="group" 		cmdno="0x07"/>
      <command cmdref="left" 		cmdno="0xe1"/>
      <command cmdref="marker" 		cmdno="0x71"/>
      <command cmdref="menu" 		cmdno="0x01"/>
      <command cmdref="next" 		cmdno="0x52"/>
      <command cmdref="ok" 			cmdno="0x41"/>
      <command cmdref="open_close" 		cmdno="0x80"/>
      <command cmdref="still_advance" 	cmdno="0x60"/>
      <command cmdref="play" 		cmdno="0x50"/>
      <command cmdref="play_mode" 		cmdno="0xb1"/>
      <command cmdref="pos_mem" 		cmdno="0x62"/>
      <command cmdref="power_off" 		cmdno="0xfc"/>
      <command cmdref="power_on" 		cmdno="0x7c"/>
      <command cmdref="power_toggle" 	cmdno="0xbc"/>
      <command cmdref="previous" 		cmdno="0x92"/>
      <command cmdref="repeat" 		cmdno="0x31"/>
      <command cmdref="cmd_return" 		cmdno="0x81"/>
      <command cmdref="rewind" 		cmdno="0x20"/>
      <command cmdref="right" 		cmdno="0x11"/>
      <command cmdref="setup" 		cmdno="0x29"/>
      <command cmdref="sleep" 		cmdno="0xd7"/>
      <command cmdref="special" 		cmdno="0xa2"/>
      <command cmdref="stop" 		cmdno="0x00"/>
      <command cmdref="subtitle" 		cmdno="0x89"/>
      <command cmdref="title" 		cmdno="0xd9"/>
      <command cmdref="two_digit" name="./.." cmdno="0x91"/>
      <command cmdref="up" 			cmdno="0xa1"/>
      <command cmdref="vss" 		cmdno="0x79"/>
      <command cmdref="zoom" 		cmdno="0x83"/>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/devices/yamaha_rxv596.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="yamaha_rxv596" name="Yamaha RX-V 596 Receiver" vendor="Yamaha" model="RX-V 596" type="receiver">
    <commandset type="ir" protocol="nec1" deviceno="122" remotename="yamaha_rxv596" original_remote="xxx">

      <!-- Input -->
      <command cmdref="in_phono" 			cmdno="0x14"/>
      <command cmdref="in_cd" 			cmdno="0x15"/>
      <command cmdref="in_tuner" 			cmdno="0x16"/>
      <command cmdref="in_tape_mon"			cmdno="0x18"/>
      <command cmdref="in_dvd" 			cmdno="0x17"/>
      <command cmdref="in_dtv" 			cmdno="0x54"/>
      <command cmdref="in_cable" 			cmdno="0xc0"/>
      <command cmdref="in_vcr" 			cmdno="0x0f"/>
      <command cmdref="in_video_aux" 		cmdno="0x55"/>
      <!--command cmdref="input_mode" 		cmdno="0xc3"/-->

      <!-- System -->
      <command cmdref="volume_up" 			cmdno="0x1a"/>
      <command cmdref="volume_down" 		cmdno="0x1b"/>
      <command cmdref="power_on" 			cmdno="0x1d"/>
      <command cmdref="power_off" 			cmdno="0x1e"/>
      <command cmdref="power_toggle" 		cmdno="0x1f"/>
      <command cmdref="mute_toggle" 		cmdno="0x1c"/>
      <command cmdref="ext_input_toggle"		cmdno="0x87"/>
      <command cmdref="osd" 			cmdno="0xc2"/>
      <command cmdref="sleep" 			cmdno="0x57"/>
      <command cmdref="menu" 			cmdno="0x9c"/>	<!-- not in the list -->

      <!-- DSP -->
      <command cmdref="stereo"			cmdno="0x88"/>
      <command cmdref="hall" 			cmdno="0x89"/>
      <command cmdref="jazz_club" 			cmdno="0x8a"/>
      <command cmdref="rock_concert" 		cmdno="0x8b"/>
      <command cmdref="entertainment" 		cmdno="0x8c"/>
      <command cmdref="music_video" 		cmdno="0x8d"/>
      <command cmdref="tv_theatre" 			cmdno="0x8e"/>
      <command cmdref="movie_theatre" 		cmdno="0x8f"/>
      <command cmdref="thx" 			cmdno="0x90"/>
      <command cmdref="dolby_dts" 			cmdno="0x91"/>
      <command cmdref="ok" 			cmdno="0x96"/>
      <command cmdref="night_toggle" 		cmdno="0x95"/>
      <command cmdref="ex_es" 			cmdno="0x97"/>
      <command cmdref="effect_toggle" 		cmdno="0x56"/>
      <command cmdref="effect_level_select"		cmdno="0x86"/>
      <command cmdref="test_mode" 			cmdno="0x85"/>

      <!-- Other -->
      <command cmdref="up"				cmdno="0x98"/>
      <command cmdref="down" 			cmdno="0x99"/>
      <command cmdref="plus" 			cmdno="0x52"/>
      <command cmdref="minus" 			cmdno="0x53"/>
      
      <!-- Tuner -->
      <command cmdref="preset_page_toggle"		cmdno="0x12"/>
      <command cmdref="channel_up" 			cmdno="0x10"/>
      <command cmdref="channel_down" 		cmdno="0x11"/>
	
      <command cmdref="service_menu"		cmdno="0xdf"/>	<!-- undocumented -->

      <command cmdref="page_a"			cmdno="0xe0"/>	<!-- undocumented -->
      <command cmdref="page_b"			cmdno="0xe1"/>	<!-- undocumented -->
      <command cmdref="page_c"			cmdno="0xe2"/>	<!-- undocumented -->
      <command cmdref="page_d"			cmdno="0xe3"/>	<!-- undocumented -->
      <command cmdref="page_e"			cmdno="0xe4"/>	<!-- undocumented -->

      <command cmdref="cmd_1" 				cmdno="0xe5"/>	<!-- No cmd_0 and cmd_9! -->
      <command cmdref="cmd_2" 				cmdno="0xe6"/>
      <command cmdref="cmd_3"	 			cmdno="0xe7"/>
      <command cmdref="cmd_4" 				cmdno="0xe8"/>
      <command cmdref="cmd_5" 				cmdno="0xe9"/>
      <command cmdref="cmd_6" 				cmdno="0xea"/>
      <command cmdref="cmd_7" 				cmdno="0xeb"/>
      <command cmdref="cmd_8" 				cmdno="0xec"/>

    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/src/main/devices/lirc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="lirc" name="LIRC Server" model="-" pingable_on="yes">
  <commandset type="tcp" suffix="\n" portnumber="8765">
    <command cmdref="get_version" transmit="VERSION" response_lines="7"/>
  </commandset>

  <commandset type="special" portnumber="21000">
    <command cmdref="get_version"/>
    <command cmdref="get_remotes"/>
    <command cmdref="get_commands">
      <argument name="remote"/>
    </command>
    <command cmdref="send_ir">
      <argument name="remote"/>
      <argument name="command"/>
    </command>
  </commandset>

  <xi:include href="ping.xi"/>
</device>

=== bengtmartensson/oldharctoolbox/devices/pioneer_cld925.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<device id="pioneer_cld925" name="Pioneer CLD-925" vendor="Pioneer" model="CLD-925" type="ld">
  <commandset type="ir" protocol="pioneer" deviceno="168" remotename="pioneer_cld925" original_remote="cu-cld115">
    <command cmdref="cmd_power_toggle"		cmdno="28"/>
    <command cmdref="cmd_power_on"		cmdno="26"/>
    <command cmdref="cmd_power_off"		cmdno="27"/>
    <command cmdref="cmd_open_close"		cmdno=""/><!-- was 22 -->
    <command cmdref="cmd_digital_sound"		cmdno="12"/>
    <command cmdref="cmd_analog_sound"		cmdno=""/>
    <command cmdref="cmd_repeat"		cmdno="68"/>
    <command cmdref="cmd_a_b"			cmdno="72"/>
    <command cmdref="cmd_display"		cmdno="67"/>
    <command cmdref="cmd_1"			cmdno="1"/>
    <command cmdref="cmd_2"			cmdno="2"/>
    <command cmdref="cmd_3"			cmdno="3"/>
    <command cmdref="cmd_clear"			cmdno="69"/>
    <command cmdref="cmd_pgm"			cmdno="76"/>
    <command cmdref="cmd_4"			cmdno="4"/>
    <command cmdref="cmd_5"			cmdno="5"/>
    <command cmdref="cmd_6"			cmdno="6"/>
    <command cmdref="cmd_plus10"		cmdno="31"/>
    <command cmdref="cmd_chapter_time"		cmdno="19"/>
    <command cmdref="cmd_7"			cmdno="7"/>
    <command cmdref="cmd_8"			cmdno="8"/>
    <command cmdref="cmd_9"			cmdno="9"/>
    <command cmdref="cmd_0"			cmdno="0"/>
    <command cmdref="cmd_memory_play"		cmdno=""/>
    <command cmdref="cmd_speed_down"		cmdno="85"/>
    <command cmdref="cmd_speed_up"		cmdno="88"/>
    <command cmdref="cmd_step_back"		cmdno="80"/>
    <command cmdref="cmd_step_forward"		cmdno="84"/>
    <command cmdref="cmd_shuffle"		cmdno="94"/>
    <command cmdref="cmd_intro"	name="hilite intro" cmdno="90"/>
    <command cmdref="cmd_previous"		cmdno="83"/>
    <command cmdref="cmd_next"			cmdno="82"/>
    <command cmdref="cmd_rewind"		cmdno="17"/>
    <command cmdref="cmd_play"			cmdno="23"/>
    <command cmdref="cmd_play"			cmdno="22"/>
    <command cmdref="cmd_fast_forward"		cmdno="16"/>
    <command cmdref="cmd_side_a"		cmdno="77"/>
    <command cmdref="cmd_side_b"		cmdno="78"/>
    <command cmdref="cmd_stop"			cmdno="23"/>
    <command cmdref="cmd_pause_toggle"		cmdno="24"/>
    <command cmdref="cmd_aspectratio_16_9"	cmdno="18"/>
    <!--
    Disc Side Toggle*,021,,enter,23 - +10,not on OEM remote,,,,,,,
    edit,029,,up arrow,51 - Multi-Speed +,,,,,,,,
    Audio,030,,down arrow,50 - Multi-Speed -,,,,,,,,
    Jog Forward*,032,,right arrow,66 - Multi-Speed >,not on OEM remote,,,,,,,63 - step +
    Jog Forward x2*,033,,select,21 - edit,not on OEM remote,,,,,,,
    Jog Forward x3*,034,,sleep,,not on OEM remote,,,,,,,
    Jog Forward x4*,035,,pip,,not on OEM remote,,,,,,,
    Jog Reverse*,036,,info,47 - Display,not on OEM remote,,,,,,,
    Jog Reverse x2*,037,,swap,52 - Repeat A*,not on OEM remote,,,,,,,
    Jog Reverse x3*,038,,move,48 - Repeat (B),not on OEM remote,,,,,,,
    Jog Reverse x4*,039,,play,18 - play,not on OEM remote,,,,,,,
    shuttle forward,040,,pause,19 - pause,,,,,,,,
    shuttle forward x2,041,,rewind,14 - rewind,,,,,,,,
    shuttle forward x3,042,,fwd,13 - fast forward,,,,,,,,
    shuttle forward x4,043,,stop,17 - Stop/Eject,,,,,,,,
    shuttle back,044,,record,,,,,,,,,
    shuttle back x2,045,,exit,49 - Clear,,,,,,,,
    shuttle back x3,046,,surround,,,,,,,,,
    shuttle back x4,047,,input,,,,,,,,,
    Frame/Time Search*,065,,com/skip,,not on OEM remote,,,,,,,
    search memory*,066,,shift-right,,not on OEM remote,,,,,,,
    Display,067,,pip freeze,,,,,,,,,
    Repeat (B),068,,slow,,,,,,,,,
    Clear,069,,eject,,,,,,,,,
    Multi-Speed -,070,,slow+,,,,,,,,,
    Multi-Speed +,071,,slow-,,,,,,,,,
    Repeat A*,072,,x2,,not on OEM remote,,,,,,,
    2/R ch*,073,,center,,not on OEM remote,,,,,,,
    Stereo*,074,,rear,,not on OEM remote,,,,,,,
    1/L ch*,075,,phantom1,,not on OEM remote,,,,,,,
    Program,076,,phantom2,,,,,,,,,
    step -,080,,phantom6,,,,,,,,,
    Skip >>|,082,,phantom7,,,,,,,,,
    Skip |<<,083,,phantom8,,,,,,,,,
    step +,084,,phantom9,,,,,,,,,
    Multi-Speed <,085,,phantom10,,,,,,,,,
    D*,087,,setup,,not on OEM remote,,,,,,,
    Multi-Speed >,088,,light,,,,,,,,,
    still / strobe*,091,,home theater,,not on OEM remote,,,,,,,
    digital effect*,092,,M1,,not on OEM remote,,,,,,,
    1shot memory*,093,,M2,,not on OEM remote,,,,,,,
    random play,094,,M3,,,,,,,,,
    -->
  </commandset>
</device>

=== bengtmartensson/oldharctoolbox/devices/popcorn_hour_a100.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices PUBLIC "-//bengt-martensson.de//devices//en"
 "../dtds/devices.dtd">
<devices>
  <device id="popcorn_hour_a100" name="Popcorn Hour A100" vendor="Syabase Technology" model="A100" type="misc_audio">
    <jp1data>
      <setupcode value="1234"/>
    </jp1data>
    <commandset type="ir" protocol="nec1" toggle="no" remotename="popcorn_hour" deviceno="4" subdevice="203">
      <!-- Reference: http://support.popcornhour.com/article.aspx?id=1005 -->
      <command cmdref="cmd_0" 			cmdno="0x1b"/>
      <command cmdref="cmd_1" 			cmdno="0x41"/>
      <command cmdref="cmd_2" 			cmdno="0x03"/>
      <command cmdref="cmd_3" 			cmdno="0x42"/>
      <command cmdref="cmd_4" 			cmdno="0x45"/>
      <command cmdref="cmd_5" 			cmdno="0x07"/>
      <command cmdref="cmd_6" 			cmdno="0x46"/>
      <command cmdref="cmd_7" 			cmdno="0x55"/>
      <command cmdref="cmd_8" 			cmdno="0x17"/>
      <command cmdref="cmd_9" 			cmdno="0x56"/>
      <command cmdref="cmd_caps_num" 		cmdno="0x5a"/>
      <command cmdref="cmd_delete" 		cmdno="0x59" remark="power + delete to shutdown"/>
      <command cmdref="cmd_mute_toggle"		cmdno="0x51"/>
      <command cmdref="cmd_page_up" 		cmdno="0x4e"/>
      <command cmdref="cmd_page_down" 		cmdno="0x52"/>
      <command cmdref="cmd_power_toggle"	cmdno="0x4a"/>
      <command cmdref="cmd_return" 		cmdno="0x47"/>
      <command cmdref="cmd_source" 		cmdno="0x05"/>
      <command cmdref="cmd_info" 		cmdno="0x4b"/>
      <command cmdref="cmd_home" 		cmdno="0x09"/>
      <command cmdref="cmd_up" 			cmdno="0x06"/>
      <command cmdref="cmd_down" 		cmdno="0x0a"/>
      <command cmdref="cmd_left" 		cmdno="0x43"/>
      <command cmdref="cmd_right"	 	cmdno="0x01"/>
      <command cmdref="cmd_ok"		 	cmdno="0x02"/>
      <command cmdref="cmd_file_mode" 		cmdno="0x48"/>
      <command cmdref="cmd_setup" 		cmdno="0x0f"/>
      <command cmdref="cmd_suspend" 		cmdno="0x4d"/>
      <command cmdref="cmd_tv_mode" 		cmdno="0x13"/>
      <command cmdref="cmd_play" 		cmdno="0x50"/>
      <command cmdref="cmd_pause_toggle"	cmdno="0x54"/>
      <command cmdref="cmd_reverse" 		cmdno="0x0e"/>
      <command cmdref="cmd_fast_forward"	cmdno="0x0d"/>
      <command cmdref="cmd_stop" 		cmdno="0x4c"/>
      <command cmdref="cmd_slow" 		cmdno="0x15"/>
      <command cmdref="cmd_next" 		cmdno="0x11"/>
      <command cmdref="cmd_previous" 		cmdno="0x12"/>
      <command cmdref="cmd_repeat" 		cmdno="0x57"/>
      <command cmdref="cmd_zoom" 		cmdno="0x19"/>
      <command cmdref="cmd_angle" 		cmdno="0x16"/>
      <command cmdref="cmd_audio" 		cmdno="0x1a"/>
      <command cmdref="cmd_title" 		cmdno="0x4f"/>
      <command cmdref="cmd_subtitle" 		cmdno="0x58"/>
      <command cmdref="cmd_time_seek" 		cmdno="0x5b"/>
      <command cmdref="cmd_red" 		cmdno="0x5f"/>
      <command cmdref="cmd_green" 		cmdno="0x1e"/>
      <command cmdref="cmd_yellow" 		cmdno="0x5c"/>
      <command cmdref="cmd_blue" 		cmdno="0x1d"/>
      <command cmdref="cmd_open_close" 		cmdno="0x44" remark="power + open/close to reset"/>
      <command cmdref="cmd_menu" 		cmdno="0x53"/>
    </commandset>
  </device>
</devices>

=== bengtmartensson/oldharctoolbox/src/main/devices/panasonic_dp_ub424.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//bengt-martensson.de//devices//en" "../dtds/devices.dtd">
<device id="panasonic_dp_ub424" name="Panasonic DP UB424" vendor="Panasonic" model="DP-UB424" type="dvd" pingable_on="yes" pingable_standby="no">
    <commandset type="ir" protocol="panasonic" toggle="no" deviceno="176" subdevice="0" remotename="IR6">
        <command cmdref="power_toggle" cmdno="61"/>
        <command cmdref="cmd_1" cmdno="16"/>
        <command cmdref="cmd_2" cmdno="17"/>
        <command cmdref="cmd_3" cmdno="18"/>
        <command cmdref="open_close" cmdno="1"/>
        <command cmdref="cmd_4" cmdno="19"/>
        <command cmdref="cmd_5" cmdno="20"/>
        <command cmdref="cmd_6" cmdno="21"/>
        <command cmdref="status_toggle" cmdno="95"/>
        <command cmdref="cmd_7" cmdno="22"/>
        <command cmdref="cmd_8" cmdno="23"/>
        <command cmdref="cmd_9" cmdno="24"/>
        <command cmdref="cancel" cmdno="131"/>
        <command cmdref="cmd_0" cmdno="25"/>
        <command cmdref="audio" cmdno="51"/>
        <command cmdref="rewind" cmdno="4"/>
        <command cmdref="play" cmdno="10"/>
        <command cmdref="fast_forward" cmdno="5"/>
        <command cmdref="previous" cmdno="73"/>
        <command cmdref="pause" cmdno="6"/>
        <command cmdref="next" cmdno="74"/>
        <command cmdref="stop" cmdno="0"/>
        <command cmdref="top_menu" cmdno="155"/>
        <command cmdref="home" cmdno="87"/>
        <command cmdref="up" cmdno="133"/>
        <command cmdref="left" cmdno="135"/>
        <command cmdref="ok" cmdno="130"/>
        <command cmdref="right" cmdno="136"/>
        <command cmdref="option_menu" cmdno="128"/>
        <command cmdref="down" cmdno="134"/>
        <command cmdref="cmd_return" cmdno="129"/>
        <command cmdref="power_off" cmdno="63"/>
        <command cmdref="power_on" cmdno="62"/>
        <command cmdref="subtitle" cmdno="147"/>
        <command cmdref="still_advance" cmdno="12"/>
        <command cmdref="forward_1_min" cmdno="76"/>
        <command cmdref="back_10_seconds" cmdno="139"/>
        <command cmdref="lock_mode" cmdno="251"/>
        <command cmdref="service_mode" cmdno ="252"/>
    </commandset>
    <commandset type="ir" protocol="panasonic" toggle="no" deviceno="176" subdevice="1" remotename="IR6">
        <command cmdref="picture_menu" cmdno="38"/>
        <command cmdref="sound_effects_menu" cmdno="39"/>
        <command cmdref="factory_reset" cmdno="91"/>
        <command cmdref="playback_info" cmdno="37"/>
        <command cmdref="internet_menu" cmdno="89"/>
        <command cmdref="popup_menu" cmdno="80"/>
        <command cmdref="hdr_menu" cmdno="41"/>
        <command cmdref="netflix" cmdno="104"/>
        <command cmdref="red" cmdno="65"/>
        <command cmdref="green" cmdno="66"/>
        <command cmdref="yellow" cmdno="67"/>
        <command cmdref="blue" cmdno="64"/>
    </commandset>
    <xi:include href="ping.xi"/>
</device>
