=== bengtmartensson/oldharctoolbox/dtds/home.dtd
<!ELEMENT homemap ( aliases?,device-groups?, devices?, from-gateways?, gateways?) >

<!ELEMENT aliases (alias+) >

<!ELEMENT alias EMPTY >
<!ATTLIST alias
	id ID #REQUIRED
        device IDREF #REQUIRED >

<!ELEMENT device-groups ( device-group+ ) >

<!ELEMENT device-group ( deviceref+ ) >
<!ATTLIST device-group
        id ID #REQUIRED
        name CDATA #REQUIRED
        zone CDATA #IMPLIED >

<!ELEMENT deviceref (#PCDATA) >
<!ATTLIST deviceref
        device IDREF #REQUIRED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT devices (device+) >

<!ELEMENT device (description?,attribute*,(from-gateway|from-gateway-ref)*,inputs?) >
<!ATTLIST device
	name CDATA #IMPLIED
        id ID #REQUIRED
        model NMTOKEN #IMPLIED
        class NMTOKEN #REQUIRED >

<!ELEMENT inputs (input)+ >

<!ELEMENT input ((selectcommand+|zone+),connectiontype*,(deviceref|internalsrc|externalsrc)*) >
<!ATTLIST input
	name CDATA #REQUIRED
	myname CDATA #IMPLIED
	audio (yes|no) "yes"
	video (yes|no) "no" >

<!ELEMENT connectiontype EMPTY >
<!ATTLIST connectiontype
	type NMTOKEN #REQUIRED >

<!ELEMENT internalsrc EMPTY >
<!ATTLIST internalsrc
	name CDATA #REQUIRED >

<!ELEMENT externalsrc EMPTY >
<!ATTLIST externalsrc
	name CDATA #REQUIRED >

<!ELEMENT selectcommand EMPTY >
<!ATTLIST selectcommand
	select NMTOKEN #REQUIRED
	audio_only NMTOKEN #IMPLIED
	video_only NMTOKEN #IMPLIED >

<!ELEMENT zone (selectcommand|querycommand)* >
<!ATTLIST zone
        name (1|2|3|record) #REQUIRED >

<!ELEMENT querycommand EMPTY >
<!ATTLIST querycommand
        cmd NMTOKEN #REQUIRED
        val CDATA #REQUIRED
        mediatype (audio_only|video_only|audio_video) "audio_video" >

<!ELEMENT dumb-device (commands?) >
<!ATTLIST dumb-device
	type (on_off|up_down|open_close) "on_off"
        forget (yes|no) #IMPLIED
        memory (direction|position|none) "none"
        pulse CDATA #IMPLIED >

<!ELEMENT commands (command|on|off|toggle|open_close|up|down)+ >

<!ELEMENT attribute EMPTY >
<!ATTLIST attribute
	name NMTOKEN #REQUIRED
	value CDATA "yes" >

<!ELEMENT from-gateways (from-gateway)+ >

<!ELEMENT from-gateway EMPTY >
<!ATTLIST from-gateway
        id ID #IMPLIED
        gateway IDREF #REQUIRED
        connector NMTOKEN "1"
        hostname CDATA #IMPLIED
 	portnumber CDATA #IMPLIED
 	mac CDATA #IMPLIED
 	wol (yes|no) #IMPLIED >

<!ELEMENT from-gateway-ref EMPTY >
<!ATTLIST from-gateway-ref
	from-gateway IDREF #REQUIRED >

<!ELEMENT gateways (gateway+) >

<!ELEMENT gateway  ((lan|hostname|(from-gateway|from-gateway-ref)+),output+,commands?,presets?) >
<!ATTLIST gateway
        class NMTOKEN #REQUIRED
        model NMTOKEN #IMPLIED
        interface NMTOKEN #IMPLIED
        deviceclass NMTOKEN #IMPLIED
        firmware CDATA #IMPLIED
	www (yes|no) "no"
	web_api (yes|no) "no"
	web_api_portnumber CDATA "80"
        name CDATA #IMPLIED
        id ID #REQUIRED >

<!ELEMENT hostname EMPTY >
<!ATTLIST hostname
        ipname CDATA #REQUIRED >

<!ELEMENT lan EMPTY >

<!ELEMENT output (commands?) >
<!ATTLIST output
        type (ir|rf433|rf868|serial|bluetooth|on_off|tcp|web_api|www|ip) "ir"
        baud CDATA #IMPLIED
        connector NMTOKEN "1" >

<!ELEMENT command EMPTY >
<!ATTLIST command
	cmd NMTOKEN #REQUIRED
	house NMTOKEN #IMPLIED
	deviceno NMTOKEN #IMPLIED
	commandname NMTOKEN #REQUIRED
	remotename NMTOKEN #REQUIRED >

<!ELEMENT presets (preset+) >

<!ELEMENT preset EMPTY >
<!ATTLIST preset
        programno CDATA #REQUIRED
        device IDREF #REQUIRED >

=== bengtmartensson/oldharctoolbox/harctoolbox/tags/commandnames_old/config/home.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE homemap PUBLIC "-//bengt-martensson.de//home//en" "../dtds/home.dtd">
<!--
Description of devices, applications, gateways, groups, zones.
-->
<homemap>
  <aliases>
    <alias id="main-receiver" device="denon"/>
    <alias id="receiver" device="denon"/>
    <alias id="amp" device="denon"/>
    <alias id="sat-receiver" device="dbox"/>
    <alias id="cable-receiver" device="dbox"/>
    <alias id="digital-receiver" device="dbox"/>
    <alias id="dvd" device="oppo"/>
    <alias id="hddvd" device="toshiba"/>
    <alias id="bluray" device="samsung"/>
    <alias id="tv" device="philips_37pfl9603"/>
    <alias id="vcr" device="vr1100"/>
    <alias id="projector" device="z2000"/>
  </aliases>
  <device-groups>
    <device-group id="light" name="Light">
      <deviceref device="front_light"/>
      <deviceref device="left_light"/>
      <deviceref device="right_light"/>
      <deviceref device="shelf_light"/>
      <deviceref device="work_light"/>
      <!--deviceref device="tv_light"/-->
      <deviceref device="lamp_column"/>
      <deviceref device="floor_lamp_1"/>
      <deviceref device="floor_lamp_2"/>
      <deviceref device="floor_lamp_3"/>
      <deviceref device="bedroom_light"/>
      <deviceref device="hall_light"/>
      <deviceref device="kitchen_light"/>
      <!--deviceref device="bathroom_light"/-->
    </device-group>

    <device-group id="blinds" name="Blinds">
      <deviceref device="large_blind"/>
      <deviceref device="small_blind"/>
      <deviceref device="balcony_blind"/>
      <deviceref device="kitchen_blind"/>
      <deviceref device="bedroom_blind"/>
    </device-group>

    <device-group id="misc" name="Misc.">
      <deviceref device="balcony_door"/>
      <deviceref device="screen"/>
      <deviceref device="rotating_flower"/>
      <deviceref device="water"/>
      <deviceref device="water_wall"/>
      <deviceref device="column_pump"/>
      <deviceref device="lamp_column"/>
      <!--deviceref device="aux_1"/-->      
      <!--deviceref device="aux_2"/-->      
      <deviceref device="aux_3"/>   
      <deviceref device="floor_fan"/>   
      <deviceref device="desk_fan"/>   
      <deviceref device="conrad_test"/>  
      <deviceref device="x10-N1"/>  
      <deviceref device="x10-N2"/>  
      <deviceref device="x10-N3"/>  
    </device-group>

    <device-group id="living_room" name="Living Room">
      <deviceref device="front_light">Front Lightning</deviceref>
      <deviceref device="left_light">Left Lightning</deviceref>
      <deviceref device="right_light">Right Lightning</deviceref>
      <deviceref device="shelf_light">Shelf Lightning</deviceref>
      <deviceref device="work_light">Work Lightning</deviceref>
      <deviceref device="balcony_door">Balcony Door</deviceref>
      <!--deviceref device="tv_light"/-->
      <deviceref device="rotating_flower"/>
      <deviceref device="screen"/>
      <deviceref device="water"/>
      <deviceref device="lamp_column"/>
      <deviceref device="column_pump"/>
      <deviceref device="water_wall"/>
      <deviceref device="large_blind"/>
      <deviceref device="small_blind"/>
      <deviceref device="balcony_blind"/>
      <deviceref device="floor_lamp_1"/>
      <deviceref device="floor_lamp_2"/>
      <deviceref device="floor_lamp_3"/>
      <deviceref device="floor_fan"/>   
      <deviceref device="desk_fan"/>   
    </device-group>

    <device-group id="kitchen_hall_bedroom" name="Kitchen/Hall/Bedroom">
      <deviceref device="kitchen_light"/>
      <deviceref device="kitchen_blind"/>
      <deviceref device="hall_light"/>
      <!--deviceref device="bathroom_light"/-->
      <deviceref device="bedroom_light"/>
      <deviceref device="bedroom_blind"/>
    </device-group>

    <device-group id="bedroom" name="Bedroom zone" zone="2">
      <!--from-gateway gateway="globalcache" connector="2"/-->
      <deviceref device="yamaha_bedroom"/>
      <deviceref device="pioneer_cld925"/>
      <deviceref device="marantz_cd42"/>
      <deviceref device="marantz_tape"/>
      <deviceref device="marantz_ipod_dock"/>
      <!--deviceref device="pioneer_dvd525"/-->
      <!--deviceref device="lg_vcr"/-->
      <deviceref device="panasonic_dvd_s75"/>
      <!--deviceref device="panasonic_dvd_s33"/-->
      <deviceref device="tiny_tv"/>
    </device-group>

    <device-group id="deskzone" name="desk" zone="3">
       <!--from-gateway gateway="globalcache" connector="3"/-->
       <deviceref device="yamaha_desk"/>
       <deviceref device="godzilla"/>
    </device-group>

    <device-group id="main" name="Main Devices" zone="1">
      <deviceref device="denon"/>
      <deviceref device="denon_ipod_dock"/>
      <!--deviceref device="pioneer_cld925"/-->
      <deviceref device="vr1100"/>
      <deviceref device="oppo"/>
      <deviceref device="popcorn"/>
      <!--deviceref device="panasonic_dvd_s75"/-->
      <deviceref device="toshiba"/>
      <deviceref device="samsung"/>
      <deviceref device="analog-8ch-switch"/>
      <deviceref device="dbox"/>
      <deviceref device="thorens"/>
      <!--deviceref device="philips_28ml8805"/-->
      <deviceref device="philips_37pfl9603"/>
      <deviceref device="nubert"/>
      <deviceref device="z2000"/>
    </device-group>

    <device-group id="mobiles" name="Mobile devices">
      <deviceref device="zoom_vaio"/>
      <deviceref device="sagem_dbox"/>
      <deviceref device="philips_dbox"/>
    </device-group>
  </device-groups>

  <devices>
    <device id="denon" class="denon_avr3808" name="Denon AVR-3808">
      <from-gateway gateway="lan" connector="tcp" hostname="denon" portnumber="23"/>
      <from-gateway gateway="lan" connector="www" hostname="denon" portnumber="80"/>
      <!--from-gateway gateway="dbox_lirc"/-->
      <from-gateway-ref from-gateway="globalcache_mainzone"/>
      <from-gateway-ref from-gateway="irtrans_mainzone"/>
      <from-gateway-ref from-gateway="denon_serial_gw"/>
      <inputs>
	<input name="phono" video="no">
	  <zone name="1">
	    <selectcommand select="cmd_in_phono" audio_only="cmd_in_phono"/>
	    <querycommand cmd="get_input" val="SIPHONO"/>
	  </zone>
	  <zone name="2">
	    <selectcommand select="cmd_zone2_phono" audio_only="cmd_zone2_phono"/>
	    <querycommand cmd="get_zone2" val="Z2PHONO"/>
	  </zone>
	  <zone name="3">
	    <selectcommand select="cmd_zone3_phono" audio_only="cmd_zone3_phono"/>
	    <querycommand cmd="get_zone3" val="Z3PHONO"/>
	  </zone>
	  <zone name="record">
	    <selectcommand select="cmd_recordsrc_phono"/>
	    <querycommand cmd="get_recordsrc" val="SRPHONO"/>
	  </zone>
	  <deviceref device="thorens"/>
	</input>
	<input name="cd" myname="tv/pc" video="no">
	  <zone name="1">
	    <selectcommand select="cmd_in_cd" audio_only="cmd_in_cd"/>
	    <querycommand cmd="get_input" val="SICD"/>
	  </zone>
	  <zone name="2">
	    <selectcommand select="cmd_zone2_cd" audio_only="cmd_zone2_cd"/>
	    <querycommand cmd="get_zone2" val="Z2CD"/>
	  </zone>
	  <zone name="3">
	    <selectcommand select="cmd_zone3_cd" audio_only="cmd_zone3_cd"/>
	    <querycommand cmd="get_zone3" val="Z3CD"/>
	  </zone>
	  <zone name="record">
	    <selectcommand select="cmd_recordsrc_cd" audio_only="cmd_recordsrc_cd"/>
	    <querycommand cmd="get_recordsrc" val="SRCD"/>
	  </zone>
	  <deviceref device="philips_37pfl9603"/>
	  <!--deviceref device="godzilla"/-->
	</input>
	<input name="tuner" video="no">
	  <zone name="1">
	    <selectcommand select="cmd_in_tuner" audio_only="cmd_in_tuner"/>
	    <querycommand cmd="get_input" val="SITUNER"/>
	  </zone>
	  <zone name="2">
	    <selectcommand select="cmd_zone2_tuner" audio_only="cmd_zone2_tuner"/>
	    <querycommand cmd="get_zone2" val="Z2TUNER"/>
	  </zone>
	  <zone name="3">
	    <selectcommand select="cmd_zone3_tuner" audio_only="cmd_zone3_tuner"/>
	    <querycommand cmd="get_zone3" val="Z3TUNER"/>
	  </zone>
	  <zone name="record">
	    <selectcommand select="cmd_recordsrc_tuner" audio_only="cmd_recordsrc_tuner"/>
	    <querycommand cmd="get_recordsrc" val="SRTUNER"/>
	  </zone>
	  <internalsrc name="tuner"/>
	</input>
	<input name="dvd" audio="yes" video="yes">
	  <zone name="1">
	    <selectcommand select="cmd_in_dvd" video_only="cmd_videoinput_dvd"/>
	    <querycommand cmd="get_input" val="SIDVD"/>
	    <querycommand cmd="get_videoinput" val="SVDVD"/>
	  </zone>
	  <zone name="2">
	    <selectcommand select="cmd_zone2_dvd"/>
	    <querycommand cmd="get_zone2" val="Z2DVD"/>
	  </zone>
	  <zone name="3">
	    <selectcommand select="cmd_zone3_dvd"/>
	    <querycommand cmd="get_zone3" val="Z3DVD"/>
	  </zone>
	  <zone name="record">
	    <selectcommand select="cmd_recordsrc_dvd"/>
	    <querycommand cmd="get_recordsrc" val="SRDVD"/>
	  </zone>
	  <deviceref device="oppo"/>
	</input>
	<input name="hdp" myname="Blu Ray" audio="yes" video="yes">
	  <zone name="1">
	    <selectcommand select="cmd_in_hdp" video_only="cmd_videoinput_hdp"/>
	    <querycommand cmd="get_input" val="SIHDP"/>
	    <querycommand cmd="get_videoinput" mediatype="video_only" val="SVHDP"/>
	  </zone>
	  <zone name="2">
	    <selectcommand select="cmd_zone2_hdp"/>
	    <querycommand cmd="get_zone2" val="Z2HDP"/>
	  </zone>
	  <zone name="3">
	    <selectcommand select="cmd_zone3_hdp"/>
	    <querycommand cmd="get_zone3" val="Z3HDP"/>
	  </zone>
	  <zone name="record">
	    <selectcommand select="cmd_recordsrc_hdp"/>
	    <querycommand cmd="get_recordsrc" val="SRHDP"/>
	  </zone>
	  <deviceref device="samsung"/>
	</input>
	<input name="tv/cbl" myname="iPod" audio="yes" video="yes">
	  <zone name="1">
	    <selectcommand select="cmd_in_tv_cbl" video_only="cmd_videoinput_tv_cbl"/>
	    <querycommand cmd="get_input" val="SITV/CBL"/>
	    <querycommand cmd="get_videoinput" mediatype="video_only" val="SVTV/CBL"/>
	  </zone>
	  <zone name="2">
	    <selectcommand select="cmd_zone2_tv_cbl"/>
	    <querycommand cmd="get_zone2" val="Z2TV/CBL"/>
	  </zone>
	  <zone name="3">
