=== bengtmartensson/oldharctoolbox/src/main/dtds/home.dtd
<!-- Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  This file is offered as-is,
     without any warranty.
-->

<!ELEMENT homemap ( aliases?,device-groups?, devices?, gateways?, gateway-ports? ) >

<!ELEMENT aliases (alias+) >

<!ELEMENT alias EMPTY >
<!ATTLIST alias
	id ID #REQUIRED
        device IDREF #REQUIRED >

<!ELEMENT device-groups ( device-group+ ) >

<!ELEMENT device-group ( deviceref+ ) >
<!ATTLIST device-group
        id ID #REQUIRED
        name CDATA #REQUIRED
        zone CDATA #IMPLIED >

<!ELEMENT deviceref (#PCDATA) >
<!ATTLIST deviceref
        device IDREF #REQUIRED
        permanent (yes|no) "yes" >

<!ELEMENT description (#PCDATA) >

<!ELEMENT devices (device+) >

<!ELEMENT device (description?,notes?,attribute*,powered-through?,(gateway-port|gateway-port-ref)*,inputs?) >
<!ATTLIST device
	name CDATA #IMPLIED
        id ID #REQUIRED
        canonical NMTOKEN #IMPLIED
        model NMTOKEN #IMPLIED
        class NMTOKEN #REQUIRED
        firmware CDATA #IMPLIED
        pin NMTOKEN #IMPLIED
        defaultzone NMTOKEN #IMPLIED >

<!ELEMENT powered-through EMPTY >
<!ATTLIST powered-through
    device IDREF #REQUIRED >

<!ELEMENT notes (#PCDATA) >

<!ELEMENT inputs (connectors*,(input)+) >

<!ELEMENT input (((selectcommand?,querycommand*)|zone+),connector*,internalsrc*,externalsrc*) >
<!ATTLIST input
	name CDATA #REQUIRED
	myname CDATA #IMPLIED
	audio (yes|no) "yes"
	video (yes|no) "no" >

<!ELEMENT connectors (connector+) >
<!ATTLIST connectors
          connectiontype (analog|s_video|yuv|scart|spdif|hdmi|cvbs|rgb|denon_link|external_analog|other) #REQUIRED
        version CDATA #IMPLIED
        hardware CDATA #IMPLIED >

<!ELEMENT connector (deviceref*) >
<!ATTLIST connector
          connectiontype  (analog|s_video|yuv|spdif|hdmi|cvbs|rgb|denon_link|external_analog|other) #IMPLIED 
          hardware CDATA #IMPLIED
          number NMTOKEN "1"
          remark CDATA #IMPLIED >

<!ELEMENT internalsrc EMPTY >
<!ATTLIST internalsrc
	name CDATA #REQUIRED >

<!ELEMENT externalsrc EMPTY >
<!ATTLIST externalsrc
	name CDATA #REQUIRED >

<!ELEMENT selectcommand EMPTY >
<!ATTLIST selectcommand
	audio_video NMTOKEN #REQUIRED
	audio_only NMTOKEN #IMPLIED
	video_only NMTOKEN #IMPLIED >

<!ELEMENT zone (selectcommand?,querycommand*) >
<!ATTLIST zone
        name (1|2|3|4|record) #REQUIRED >

<!ELEMENT querycommand EMPTY >
<!ATTLIST querycommand
        cmd NMTOKEN #REQUIRED
        val CDATA #REQUIRED
        mediatype (audio_only|video_only|audio_video) "audio_video" >

<!ELEMENT commandmappings (commandmapping)+ >

<!ELEMENT attribute EMPTY >
<!ATTLIST attribute
	name NMTOKEN #REQUIRED
	value CDATA "yes" >

    <!-- Previously called from-gateway -->
<!ELEMENT gateway-ports (gateway-port)+ >

<!ELEMENT gateway-port EMPTY >
<!ATTLIST gateway-port
        id ID #IMPLIED
        gateway IDREF #REQUIRED
        connectorno NMTOKEN "1"
        connectortype (ir|rf|serial|bluetooth|on_off|tcp|web_api|www|ip|virtual|sensor|special) #REQUIRED
        hostname CDATA #IMPLIED
 	portnumber CDATA #IMPLIED
 	mac CDATA #IMPLIED
 	timeout CDATA "10000"
 	wol (yes|no) #IMPLIED >

<!ELEMENT gateway-port-ref EMPTY >
<!ATTLIST gateway-port-ref
	gateway-port IDREF #REQUIRED >

<!ELEMENT gateways (gateway+) >

<!ELEMENT gateway  ((gateway-port|gateway-port-ref)*,ports+,commandmappings?) >
<!ATTLIST gateway
        class NMTOKEN #REQUIRED
        model NMTOKEN #IMPLIED
        interface NMTOKEN #IMPLIED
        deviceclass NMTOKEN #IMPLIED
        firmware CDATA #IMPLIED
	www (yes|no) "no"
	web_api (yes|no) "no"
	web_api_portnumber CDATA "80"
        name CDATA #IMPLIED
        hostname CDATA #IMPLIED
        timeout CDATA "4242"
        id ID #REQUIRED >

<!ELEMENT ports (port+) >
<!ATTLIST ports
        type (ir|rf|serial|bluetooth|on_off|tcp|web_api|www|ip|virtual|sensor|special) #REQUIRED >

<!ELEMENT port (commandmappings?) >
<!ATTLIST port
        baud CDATA #IMPLIED
        number NMTOKEN "1" >

<!ELEMENT commandmapping EMPTY >
<!ATTLIST commandmapping
	cmd NMTOKEN #REQUIRED
	house NMTOKEN #IMPLIED
	deviceno NMTOKEN #IMPLIED
	commandname NMTOKEN #REQUIRED
	remotename NMTOKEN #REQUIRED >

=== bengtmartensson/oldharctoolbox/src/main/config/home_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE homemap PUBLIC "-//bengt-martensson.de//home//en" "../dtds/home.dtd">
<!--
Description of devices, applications, gateways, groups, zones.

This is a sample file.
-->
<homemap>
  <aliases>
    <alias id="main-receiver" device="denon"/>
    <alias id="receiver" device="denon"/>
    <alias id="amp" device="denon"/>
    <alias id="sat-receiver" device="dbox"/>
    <alias id="cable-receiver" device="dbox"/>
    <alias id="digital-receiver" device="dbox"/>
    <alias id="dvd" device="oppo"/>
    <alias id="bluray" device="samsung"/>
    <alias id="tv" device="philips_37pfl9603"/>
    <alias id="projector" device="z2000"/>
  </aliases>
  <device-groups>
    <device-group id="light" name="Light">
      <deviceref device="front_light"/>
      <deviceref device="work_light"/>
      <deviceref device="hall_light"/>
      <deviceref device="kitchen_light"/>
    </device-group>

    <device-group id="blinds" name="Blinds">
      <deviceref device="large_blind"/>
      <deviceref device="bedroom_blind"/>
    </device-group>

    <device-group id="misc" name="Misc.">
      <deviceref device="balcony_door"/>
      <deviceref device="screen"/>
      <deviceref device="x10-N1"/>  
    </device-group>

    <device-group id="living_room" name="Living Room">
      <deviceref device="front_light">Front Lightning</deviceref>
      <deviceref device="work_light">Work Lightning</deviceref>
      <deviceref device="balcony_door">Balcony Door</deviceref>
      <deviceref device="screen"/>
      <deviceref device="large_blind"/>
    </device-group>

    <device-group id="kitchen_hall_bedroom" name="Kitchen/Hall/Bedroom">
      <deviceref device="kitchen_light"/>
      <deviceref device="hall_light"/>
      <deviceref device="bedroom_blind"/>
    </device-group>

    <device-group id="bedroom" name="Bedroom zone" zone="2">
      <!--from-gateway gateway="globalcache" connector="2"/-->
      <deviceref device="yamaha_bedroom"/>
      <deviceref device="pioneer_cld925"/>
      <deviceref device="marantz_cd42"/>
      <deviceref device="marantz_tape"/>
      <deviceref device="panasonic_dvd_s75"/>
      <deviceref device="tiny_tv"/>
    </device-group>

    <device-group id="deskzone" name="desk" zone="3">
       <!--from-gateway gateway="globalcache" connector="3"/-->
       <deviceref device="yamaha_desk"/>
    </device-group>

    <device-group id="main" name="Main Devices" zone="1">
      <deviceref device="denon"/>
      <!--deviceref device="pioneer_cld925"/-->
      <deviceref device="oppo"/>
      <deviceref device="popcorn"/>
      <!--deviceref device="panasonic_dvd_s75"/-->
      <deviceref device="samsung"/>
      <deviceref device="dbox"/>
      <!--deviceref device="philips_28ml8805"/-->
      <deviceref device="philips_37pfl9603"/>
      <deviceref device="z2000"/>
    </device-group>

    <device-group id="gateways" name="Intelligent Gateways">
      <deviceref device="gc_dev"/>
      <deviceref device="gc2_dev"/>
      <deviceref device="irtrans_dev"/>
      <deviceref device="t10_dev"/>
    </device-group>
  </device-groups>

  <devices>
    <device id="denon" class="denon_avr3808" name="Denon AVR-3808">
      <!-- Here, order is significant, and denotes preference.
      In particular, make sure that www comes last! -->
      <gateway-port gateway="lan" connectortype="tcp" hostname="denon" portnumber="23"/>
      <gateway-port-ref gateway-port="globalcache_mainzone"/>
      <gateway-port-ref gateway-port="irtrans_mainzone"/>
      <gateway-port gateway="lan" connectortype="ip" hostname="denon" wol="no"/>
      <gateway-port gateway="lan" connectortype="www" hostname="denon" portnumber="80"/>
      <inputs>
	<!-- Order in usability order -->
	<input name="sat" myname="dBox" audio="yes" video="yes">
	  <zone name="1">
	    <selectcommand audio_video="in_sat" video_only="videoinput_sat"/>
	    <querycommand cmd="get_input" val="SISAT"/>
	    <querycommand cmd="get_videoinput" mediatype="video_only" val="SVSAT"/>
	  </zone>
	  <zone name="2">
	    <selectcommand audio_video="zone2_sat"/>
	    <querycommand cmd="get_zone2" val="Z2SAT"/>
	  </zone>
	  <zone name="3">
	    <selectcommand audio_video="zone3_sat"/>
	    <querycommand cmd="get_zone3" val="Z3SAT"/>
	  </zone>
	  <zone name="record">
	    <selectcommand audio_video="recordsrc_sat"/>
	    <querycommand cmd="get_recordsrc" val="SRSAT"/>
	  </zone>
	  
          <connector connectiontype="cvbs">
	    <!--deviceref device="dbox"/-->
	    <deviceref device="dbox"/>
	  </connector>
	  <connector connectiontype="analog">
	    <!--deviceref device="dbox"/-->
	    <deviceref device="dbox"/>
	  </connector>
	  <connector connectiontype="spdif" hardware="optical" number="1">
	    <!--deviceref device="dbox"/-->
	    <deviceref device="dbox"/>
	  </connector>
	  <!--connector connectiontype="yuv" number="3">
	    <deviceref device="dbox"/>
	  </connector-->
	  <connector connectiontype="hdmi" number="3">
	    <deviceref device="dbox"/>
	  </connector>
	</input>
	<input name="dvd" audio="yes" video="yes">
	  <zone name="1">
	    <selectcommand audio_video="in_dvd" video_only="videoinput_dvd"/>
	    <querycommand cmd="get_input" val="SIDVD"/>
	    <querycommand cmd="get_videoinput" mediatype="video_only" val="SVDVD"/>
	  </zone>
	  <zone name="2">
	    <selectcommand audio_video="zone2_dvd"/>
	    <querycommand cmd="get_zone2" val="Z2DVD"/>
	  </zone>
	  <zone name="3">
	    <selectcommand audio_video="zone3_dvd"/>
	    <querycommand cmd="get_zone3" val="Z3DVD"/>
	  </zone>
	  <zone name="record">
	    <selectcommand audio_video="recordsrc_dvd"/>
	    <querycommand cmd="get_recordsrc" val="SRDVD"/>
	  </zone>
	   <connector connectiontype="cvbs">
	    <deviceref device="oppo"/>
	  </connector>
	  <connector connectiontype="analog">
	    <deviceref device="oppo"/>
	  </connector>
	  <connector connectiontype="external_analog">
	    <deviceref device="oppo"/>
	  </connector>
	  <!--connector connectiontype="spdif" hardware="optical" number="2">
	  </connector-->
	  <!--connector connectiontype="yuv" number="1">
	    <deviceref device="oppo"/>
	  </connector-->
	  <connector connectiontype="hdmi" number="2">
	    <deviceref device="oppo"/>
	  </connector>
	</input>
	<input name="hdp" myname="Blu Ray" audio="yes" video="yes">
	  <zone name="1">
	    <selectcommand audio_video="in_hdp" video_only="videoinput_hdp"/>
	    <querycommand cmd="get_input" val="SIHDP"/>
	    <querycommand cmd="get_videoinput" mediatype="video_only" val="SVHDP"/>
	  </zone>
	  <zone name="2">
	    <selectcommand audio_video="zone2_hdp"/>
	    <querycommand cmd="get_zone2" val="Z2HDP"/>
	  </zone>
	  <zone name="3">
	    <selectcommand audio_video="zone3_hdp"/>
	    <querycommand cmd="get_zone3" val="Z3HDP"/>
	  </zone>
	  <zone name="record">
	    <selectcommand audio_video="recordsrc_hdp"/>
	    <querycommand cmd="get_recordsrc" val="SRHDP"/>
	  </zone>
	  
	</input>
	<input name="dvr" myname="HD-DVD" audio="yes" video="yes">
	  <zone name="1">
	    <selectcommand audio_video="in_dvr" video_only="videoinput_dvr"/>
        <querycommand cmd="get_input" val="SIDVR"/>
	    <querycommand cmd="get_videoinput" mediatype="video_only" val="SVDVR"/>
	  </zone>
	  <zone name="2">
	    <selectcommand audio_video="zone2_dvr"/>
	    <querycommand cmd="get_zone2" val="Z2VCR"/>
	  </zone>
	  <zone name="3">
	    <selectcommand audio_video="zone3_dvr"/>
	    <querycommand cmd="get_zone3" val="Z3VCR"/>
	  </zone>
	  <zone name="record">
	    <selectcommand audio_video="recordsrc_dvr"/>
	    <querycommand cmd="get_recordsrc" val="SRDVR"/>
	  </zone>
	</input>
	<input name="phono" video="no">
	  <zone name="1">
	    <selectcommand audio_video="in_phono" audio_only="in_phono"/>
	    <querycommand cmd="get_input" val="SIPHONO"/>
	  </zone>
	  <zone name="2">
	    <selectcommand audio_video="zone2_phono" audio_only="zone2_phono"/>
	    <querycommand cmd="get_zone2" val="Z2PHONO"/>
	  </zone>
	  <zone name="3">
	    <selectcommand audio_video="zone3_phono" audio_only="zone3_phono"/>
	    <querycommand cmd="get_zone3" val="Z3PHONO"/>
	  </zone>
	  <zone name="record">
	    <selectcommand audio_video="recordsrc_phono"/>
	    <querycommand cmd="get_recordsrc" val="SRPHONO"/>
	  </zone>
	</input>
	<input name="cd" myname="tv/pc" video="no">
	  <zone name="1">
	    <selectcommand audio_video="in_cd" audio_only="in_cd"/>
	    <querycommand cmd="get_input" val="SICD"/>
	  </zone>
	  <zone name="2">
	    <selectcommand audio_video="zone2_cd" audio_only="zone2_cd"/>
	    <querycommand cmd="get_zone2" val="Z2CD"/>
	  </zone>
	  <zone name="3">
	    <selectcommand audio_video="zone3_cd" audio_only="zone3_cd"/>
	    <querycommand cmd="get_zone3" val="Z3CD"/>
	  </zone>
	  <zone name="record">
	    <selectcommand audio_video="recordsrc_cd" audio_only="recordsrc_cd"/>
	    <querycommand cmd="get_recordsrc" val="SRCD"/>
	  </zone>
	  <!--deviceref device="philips_37pfl9603"/-->
	</input>
	<input name="tuner" video="no">
	  <zone name="1">
	    <selectcommand audio_video="in_tuner" audio_only="in_tuner"/>
	    <querycommand cmd="get_input" val="SITUNER"/>
	  </zone>
	  <zone name="2">
	    <selectcommand audio_video="zone2_tuner" audio_only="zone2_tuner"/>
	    <querycommand cmd="get_zone2" val="Z2TUNER"/>
	  </zone>
	  <zone name="3">
	    <selectcommand audio_video="zone3_tuner" audio_only="zone3_tuner"/>
	    <querycommand cmd="get_zone3" val="Z3TUNER"/>
	  </zone>
	  <zone name="record">
	    <selectcommand audio_video="recordsrc_tuner" audio_only="recordsrc_tuner"/>
	    <querycommand cmd="get_recordsrc" val="SRTUNER"/>
	  </zone>
	  <internalsrc name="tuner"/>
	</input>
	<input name="tv/cbl" myname="iPod" audio="yes" video="yes">
	  <zone name="1">
	    <selectcommand audio_video="in_tv_cbl" video_only="videoinput_tv_cbl"/>
	    <querycommand cmd="get_input" val="SITV/CBL"/>
	    <querycommand cmd="get_videoinput" mediatype="video_only" val="SVTV/CBL"/>
	  </zone>
	  <zone name="2">
