=== bengtmartensson/oldharctoolbox/src/main/dtds/tasks.dtd
<!-- Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  This file is offered as-is,
     without any warranty.
-->

<!--
This is, at this time being at least, not a universal solution, but just, essentially, all that *I* need for the moment.
-->

<!--- A collection of tasks. -->
<!ELEMENT tasks (task)+>

<!--- A task is similar to a timer. -->
<!ELEMENT task (time,commandline+)>
<!ATTLIST task
    name NMTOKEN #REQUIRED
  >

<!--- Indicates that the task is to be perioidically executed. -->
<!ELEMENT period EMPTY>
<!ATTLIST period
    days CDATA "0"
    hours CDATA "0"
    minutes CDATA "1"
    seconds CDATA "0"
  >

<!--- Commandline to be executed by the engine. -->
<!ELEMENT commandline (#PCDATA)>

<!ELEMENT last-of (absolute-time|sunrise|sunset)+>

<!ELEMENT first-of (absolute-time|sunrise|sunset)+>

<!--- A time when the task is being executed. -->
<!ELEMENT time (last-of|first-of|absolute-time|period|weekdays|sunrise|sunset)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT absolute-time EMPTY>
<!ATTLIST absolute-time
    minute CDATA #REQUIRED
    hour CDATA #REQUIRED
    second CDATA "00"
  >

<!--- The sunrise time. -->
<!ELEMENT sunrise EMPTY>
<!ATTLIST sunrise
    tz CDATA #IMPLIED
    latitude CDATA #REQUIRED
    longitude CDATA #REQUIRED
    degrees NMTOKEN "-1"
  >

<!--- The sunset time. -->
<!ELEMENT sunset EMPTY>
<!ATTLIST sunset
    tz CDATA #IMPLIED
    latitude CDATA #REQUIRED
    longitude CDATA #REQUIRED
    degrees NMTOKEN "-1"
      >

<!ELEMENT weekdays (weekday)*>

<!--- Absolute time, dependent on weekday. -->
<!ELEMENT weekday (last-of|first-of|absolute-time|sunrise|sunset)>
<!ATTLIST weekday
    day (Sun|Mon|Tue|Wed|Thu|Fri|Sat) #REQUIRED
  >

=== bengtmartensson/oldharctoolbox/harctoolbox/trunk/config/tasks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tasks SYSTEM "../dtds/tasks.dtd">

<tasks>
  <!--task name="pinger">
    <time>
      <period minutes="0" seconds="10"/>
    </time>
    <commandline>denon ping</commandline>
    <commandline>dbox ping</commandline>
    <commandline>axim ping</commandline>
    <commandline>asus ping</commandline>
  </task-->

  <task name="morning-screen-up">
    <time>
      <absolute-time hour="6" minute="58"/>
    </time>
    <commandline>screen up</commandline>
  </task>

  <task name="sunrise-blinds-up">
    <time>
      <last-of>
	<absolute-time  hour="7" minute="0"/>
	<sunrise latitude="48.13" longitude="11.5" degrees="-3"/>
      </last-of>
    </time>
    <!--commandline>sunrise</commandline-->
    <commandline>large_blind up</commandline>
    <commandline>small_blind up</commandline>
    <commandline>balcony_blind up</commandline>
    <commandline>kitchen_blind up</commandline>
    <commandline>large_blind up</commandline>
    <commandline>small_blind up</commandline>
    <commandline>balcony_blind up</commandline>
    <commandline>kitchen_blind up</commandline>
  </task>

  <task name="sunset-blinds-down">
    <time>
      <sunset latitude="48.13" longitude="11.5" degrees="-3"/>
    </time>
    <!--commandline>sunset</commandline-->
    <commandline>large_blind down</commandline>
    <commandline>small_blind down</commandline>
    <commandline>balcony_blind down</commandline>
    <commandline>kitchen_blind down</commandline>
    <commandline>bedroom_blind down</commandline>
    <commandline>large_blind down</commandline>
    <commandline>small_blind down</commandline>
    <commandline>balcony_blind down</commandline>
    <commandline>kitchen_blind down</commandline>
    <commandline>bedroom_blind down</commandline>
  </task>

  <task name="bedroom-blind-up">
    <time>
      <weekdays>
	<weekday day="Mon">
	  <absolute-time hour="7" minute="45"/>
	</weekday>
	<weekday day="Tue">
	  <absolute-time hour="7" minute="45"/>
	</weekday>
	<weekday day="Wed">
	  <absolute-time hour="7" minute="45"/>
	</weekday>
	<weekday day="Thu">
	  <absolute-time hour="7" minute="45"/>
	</weekday>
	<weekday day="Fri">
	  <absolute-time hour="7" minute="45"/>
	</weekday>
	<weekday day="Sat">
	  <absolute-time hour="9" minute="0"/>
	</weekday>
	<weekday day="Sun">
	  <absolute-time hour="9" minute="0"/>
	</weekday>
      </weekdays>
    </time>
    <commandline>bedroom_blind up</commandline>
  </task>
</tasks>
